### PR TITLE
Adding ES OMX Player Experimental module

### PR DESCRIPTION
**Pull request by pjft**
Hi,

I have been maintaining a build based on @fieldofcows ' OMX Player and screensaver work, with a few other quality of life features, such as random game selection from the screensaver, captions for showing the screensaver game name.

Given that we're still a ways off from getting HW acceleration on VLC, this build is being used by a few people in the community, but it's kind of a suboptimal flow to update it.

I'm planning on keeping the source branch up-to-date with the master RetroPie/EmulationStation branch on a regular-ish basis (2 months, monthly, or on the odd occasion sooner if relevant), so that people can keep up with the majority of new developments but still keep OMX Player as an option, as well as having screensaver support.

Hence, I'd like to ask if it it's possible to add this to the experimental section of RetroPie-Setup. If so, I'll add it to the wiki then as a separate page, similar to the ES-Kids fork one.

Open to recommendations - and explicitly calling out @fieldofcows in case he has any further feedback, as well as in case the emails I have tried to reach out to him on aren't being monitored anymore. If you have any concerns or aren't supportive of this, I'm happy to withdraw this change, but it's an easier way for people to have access to this work.

Thanks.

### CODE REVIEW

**Comment by joolswills** [comment]
Not too keen on having another ES module. I would prefer to wait/accept the changes to our main module when they are ready.

**Comment by pjft** [comment]
Thanks for the quick responses. I'm certainly not keen on having an
experimental module either, but I wasn't sure you'd support including OMX
player as an option inside the main ES. It really is the only difference to
the main branch, give or take any more recent commit since yesterday.

If that would be an option, though, I'm more than keen to pursue that
route, as I've been pretty much using it for a months now with no
complaints, together with a few others on the forums. I was just looking
for a way to help the community have easier access to this, so I'm happy to
explore alternatives.

There's also the problem that a significant part of the code was developed
by @fieldofcows though I haven't been able to contact him for the past
month or so, so I hope that everything is alright with him. I wouldn't feel
well in it being me to submit some of his code to the master branch, even
though I've built quite a few things on top of it. The only option I'd see
for that to be something I'd feel OK with would be if he'd explicitly state
that he wouldn't be able to do so and would give me his blessing, in the
sense that it would help him - and even so, I'd like to be 100% sure of his
approval as I'm not keen on being credited for others' achievements.
@fieldofcows: Any thoughts or considerations in regards to this option?
And, while you're at it, is everything OK with you? I sincerely hope so.

Worst case scenario I can keep on providing pre compiled builds on request,
or have others install this script themselves, though I'm never keen on
keeping multiple sources.

So that's kind of it! Let me know your thoughts, as well as feel free to
call me out and point me in the right direction in regards to project
etiquette - whether I'm doing things I shouldn't, or not doing things I
could - and thanks in advance for your time in keeping the project healthy!

**Comment by joolswills** [comment]
So long as the omxplayer stuff is ifdef'd out / disabled for other platforms I'm fine with it to be included as an option - at least until we can include hardware acceleration via VLC in the future etc.. 

Appreciate everything you have done for the project :) Thanks.

**Comment by pjft** [comment]
It is ifdef'd out, definitely. Let me then try to break it in a few more
manageable commits, and double check if everything is as it should, though
I'll also give it a couple of weeks in hopes that we hear anything from
@fieldofcows.

Thanks for the kind words and have a great evening! :)

I'll close this tomorrow when on my laptop.

**Comment by joolswills** [comment]
I think I would like to move the settings around a bit. As on X86 there is a video player settings menu with just one item in it. I was thinking:

* put video player audio setting in the Audio Settings.
* put the omxplayer setting in Other Settings.

**Comment by joolswills** [comment]
I'm on the wrong tracker sorry.

**Pull request closed without merging**
