### PR TITLE
Always use all CPUs for build

### PR DESCRIPTION
**Pull request by Pitel**
At least fix `-j 2` typo, causing infinte jobs

### CODE REVIEW

**Comment by joolswills** [comment]
It is set to -j2 intentionally on the RPI due to memory constraints you can override it with `sudo MAKEFLAGS="-jX" ./retropie_setup.sh` etc

**Comment by joolswills** [comment]
Will fix the space (it's not a supported platform yet btw)

**Comment by joolswills** [comment]
The space is technically correct according to make man file.

**Comment by Pitel** [comment]
Oh, I remembered vaguely it once wasn't, and caused unlimited jobs. But it might be many years ago. :)

**Pull request closed without merging**
