### PR TITLE
Ports

### PR DESCRIPTION
**Pull request by joolswills**
It was getting confusing with so many "ports" config folders in /opt/retropie/configs/

this changeset moves all ports configs to $configdir/ports/NAME and that location is now used.

`$md_conf_root` points to $configdir usually, but is adjusted to "$configdir/ports" in addPort (addPort needs to be first now so this variable is set correctly).

This needs some testing.

### CODE REVIEW

**Comment by zerojay** [comment]
Let me know and I'll tackle converting my scripts over ASAP. I agree with this change, config was getting very crowded.

**Comment by joolswills** [comment]
basically - to update a module

* Put addPorts first
* Use $md_conf_root instead of "$configdir" (you till need to include the name after eg $md_id or doom (configs for doom go in doom, but there are multiple modules that implement a doom port)
* no need for mkRomDir "$roms" (but subfolders have to be made if needed)

**Comment by HerbFargus** [comment]
All seems fine to me, tested all the defaults and a few experimental like cgenius and xrick, no issues. 

One thing that I wasn't sure about was with my keyboard before I was pretty sure I could use hotkeys to exit but now it uses the escape key so I'm wonder if its missing a retroarch.cfg somewhere when it loads the libretro ports. which its looking like you may have addressed above

**Comment by joolswills** [comment]
aah no. There is a bug with the paths hmm and I may need to introduce a new function to set the configdir perhaps rather than doing it in addPorts (so addPorts can be at the end like addSystem, but another function would need to be called first).

**Comment by joolswills** [comment]
I need to have a think about the cleanest way of doing this, so that I don't have to keep reworking the modules :-)

**Comment by joolswills** [comment]
I want to keep it so the same variables are used between modules, to keep it simple, but the problem is we have a inconsistent structure currently (eg love is in ports, but is actually a system in regards to config / rom folder structure, some ports are actually libretro cores and so on)

**Comment by InsecureSpike** [comment]
I hope you don't mind me throwing in an idea, if the ports at the moment are including actual ports and systems could these not be split into two? ports stay as ports but experimental systems could go under another menu as experimental, then when they have been tested then they get moved out as normal and have their own system menus?

**Comment by joolswills** [comment]
I'm going with a solution that means another function call is needed to set the config location for things that don't use the obvious default for the scriptmodule type (eg ports in libretrocores)

**Comment by joolswills** [comment]
@InsecureSpike the way stuff is organised in the retropie-setup menu will be changed, with "core, main, and optional, and experimental modules" - that is separate from the work I am doing now, which is basically reorganising the config structure to match the roms directory structure more closely (so ports are not mixed amongst all the system folders)

**Comment by InsecureSpike** [comment]
ahh I see, sorry for the confusion

**Comment by joolswills** [comment]
@HerbFargus updated branch - I think the libretro ports should load their configs correctly now

**Comment by HerbFargus** [comment]
Can confirm the libretro configs are fixed

**Comment by joolswills** [comment]
Thanks for testing. I will merge.

**Comment by joolswills** [comment]
One thing to note is for existing libretro ports (lr-prboom / lr-tyrquake / lr-nxengine)  - when it moves their configs, it won't overwrite the retroarch.cfg after with a new config so the retroarch.cfg will contain an old path for "input_remapping_directory" - it will create a retroarch.cfg.rp-dist with the new config though which can be copied over.

**Pull request merged**
