### PR TITLE
lr-vice: preset a couple of SID options on ARMv6

### PR DESCRIPTION
**Pull request by cmitu**
The options changed are similar to the configuration used for the standalone VICE:

* Set the SID implementation to FastSID
* Decrease the sound sample rate to 22050

### CODE REVIEW

**Comment by cmitu** [comment]
For standalone `vice`, we preset the options for any non `x11` platform, not sure if we should do the same for the libretro core (hence the draft).

**Comment by joolswills** [comment]
Actually Vice should be updated. It's old code. I'll take a look

**Comment by joolswills** [comment]
This looks good btw. Thanks.

**Comment by joolswills** [comment]
So looking at the vice code, the original old logic was intended as: If not x86 then use fastsid. If armv6 then half sample rate.

With the RPI3/RPI4 the floating point Sid emulation is fine but it probably is still a big overhead for RPI2. I actually think it may still be worth defaulting to fastsid on all arm. As we.do in the standalone core.

I'm adjusting the logic in the standalone now to update it taking into account new flags etc.

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/commit/a39f05d72f2fe2d6604ee646a761d2ac0689a1b7

**Comment by cmitu** [comment]
OK, I'll sync the changes to a39f05d.

**Comment by cmitu** [comment]
OK, the options should be similar to the `vice` changes.

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
