### PR TITLE
joy2key - added repeat support for easier navigation of large menus

### PR DESCRIPTION
**Pull request by joolswills**
Remove unneeded loop from read_event.

Make process_event return the chars to output and split out code to write to terminal so it can
be called from the added repeat code in the main processing loop

Added a JS_DEL (delay before repeat) and use JS_REP (time betweeen repeats) for the key repeat speed

Added js_hold variable, where we store the last button press input received. If no other button press
or release is done, we do a repeat of the last output.

### CODE REVIEW

**Comment by joolswills** [comment]
Fixed the analogue stick logic issues. Was a simple check needed if the js_hold was set for that joystick. If so, we ignore any input other than release. This makes.the analogue sticks function like a digital pad in the menus. Put the ranges and thresholds back as they were.

Would appreciate if you can test this @cmitu

**Comment by cmitu** [comment]
I gave it a try and the scrolling behavior via the analog joystick has some quirks:
- up/down scrolls, but skips about 1-2 entries, depending on how fast the stick is pushed. What's more annoying is that sometimes an extra scroll is generated when the stick is put back into position.
- keeping the joypad at max up/down doesn't always trigger a continuous scroll in the list, just like when D-Pad up/down are kept pressed.

I tested using the left joystick on a DuasShock 4 (v2) connected via USB. The right joystick has a different behavior - up/down switches between the buttons, while left/right scroll up/down in the list (but it behaves similarly w.r.t. scrolling).

I tried to get an event list via `evtest`, but the DS spams a continuous `EV_SYN` event that makes the events logging impractical.

**Comment by joolswills** [comment]
Strange, didn't get that in my 8bitdo and the newest changes were to make the analogue stick behave better not worse - annoying. I don't have that joystick but I have a ds3. I'll recheck.

**Comment by joolswills** [comment]
Does the joypad have an accelerometer that creates events when tilting etc?

**Comment by cmitu** [comment]
Yes, it has, but it's created as a separate input device:
```
/dev/input/event3:	Sony Interactive Entertainment Wireless Controller Touchpad
/dev/input/event4:	Sony Interactive Entertainment Wireless Controller Motion Sensors
/dev/input/event5:	Sony Interactive Entertainment Wireless Controller
```

**Comment by joolswills** [comment]
I wonder if it could still be interfering - can you test forcing to just the pad device? Also do you have any other analogue sticks to test with?

**Comment by cmitu** [comment]
I'll give it a try with an Wii U Pro (no motion sensors) and re-check I'm using the latest `joy2key`.

**Comment by cmitu** [comment]
I re-rested using a PS3 controller and it's behaving better - doesn't jump over lines during scrolling, but auto-scrolling when the joystick is at max up/down doesn't always triger, just like for the DS4.

**Comment by madmodder123** [comment]
> 
> 
> I re-rested using a PS3 controller and it's behaving better - doesn't jump over lines during scrolling, but auto-scrolling when the joystick is at max up/down doesn't always triger, just like for the DS4.

Same behavior with wired PS2 controllers using the blue dual port USB adapters, the right stick is also mapped but the mapping is incorrect (Left goes up, Right goes down, Up goes left, Down goes right), not sure if it matters since most will use the left stick but I thought I should mention it.

**Comment by Gemba** [comment]
Hmmm.
If this change relates to my [suggested changes](https://retropie.org.uk/forum/topic/27128/enhancements-for-dialog-navigation-controls) feel free to yank some parts of it for your change here.
I tested my proposed change and it works correctly with D-pad as well as with analog hat.

**Comment by cmitu** [comment]
I re-tested using a Wii U Pro controller, which doesn't have motion sensors.
The behavior for scrolling is similar to the PS3 - it doesn't skip the entries on the list when operating the analog joysticks. What's different is that the right joystick works similar to the left one - i.e. up/down scrolls in the list, while left/right switches between the dialog buttons.

For comparison here is the auto-configuration for both controllers - https://gist.github.com/cmitu/df5fc1cb0d6441566593a6cd7aa7613e.

**Comment by joolswills** [comment]
I didn't make any changes regarding the mapping btw. Just auto repeat behaviour, or are you saying mapping stuff has changed?

**Comment by joolswills** [comment]
@Gemba I'll take a look. My changes did actually work fine with the controller's I tested on.

**Comment by joolswills** [comment]
Closing as the sdl2 solution is better.

**Pull request closed without merging**
