### PR TITLE
Wonderswan and Neogeo Seperations

### PR DESCRIPTION
**Pull request by Omnija**
Would like Neogeo Pocket/Color and Wonderswan/Color as seperate folders.
1 for organization purposes and as well to maintain seperate folders for seperate systems.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks but I don't want to split these up currently as it means lots of theme work, and for most people I think it's fine with a single rom folder for them.

**Comment by Omnija** [comment]
I already submitted a small update to the theme so you wouldn't have to worry about it. I also thought it would be a good idea for the same reasons gb and gbc are seperate.

**Comment by joolswills** [comment]
OK. I will get some feedback from others and decide. @HerbFargus / @gizmo98 - what do you think ?

**Comment by HerbFargus** [comment]
I have no problem with it, as he does make a valid point that they are technically closer to the gb and gbc than they are the Genesis/megadrive. And he did add them to the theme, so that's not an issue (and I don't mind updating themes for some others)

**Comment by gizmo98** [comment]
Makes sense. We have separate folders for handhelds gb and gbc as well.

**Comment by joolswills** [comment]
ok. Will merge. thanks for feedback.

**Pull request merged**
