### PR TITLE
retroarch - install minimal assets by default

### PR DESCRIPTION
**Pull request by joolswills**
@psyke83 please give this a go. It's much the same as your PR, but without using svn and just grabbing a tar.gz from our own server.

### CODE REVIEW

**Comment by psyke83** [comment]
Working perfectly - same behaviour as my patch. When installing full assets, update_assets_retroarch will delete the assets folder and avoid causing issues, and uninstalling full assets (whether installed or not) will trigger redownload of the minimal assets.

One extremely nitpicky observation (happened in my patch too) is that the filenames during untar will be visible after choosing the "uninstall assets" menu option. If that bothers you, perhaps a redirect to /dev/null might be in order for that specific function call.

**Comment by psyke83** [comment]
No, sorry. A potential oversight in your patch is that you didn't chmod the assets. They've got root privileges now.

**Comment by joolswills** [comment]
I don't mind the output - it gets logged etc which can be useful. I'll fix the permissions

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
