### PR TITLE
Fixed paths of Super Mario War for RetroPie

### PR DESCRIPTION
**Pull request by HerbFargus**
I created a new repo with a more complete commit history as well as
reprogrammed the splashscreens to be raspberry pi specific and also
fixed the paths so all game files are installed into
/opt/retropie/ports/smw

### CODE REVIEW

**Comment by joolswills** [comment]
thanks.

**Comment by HerbFargus** [comment]
I just tested it from a fresh image just to be sure, and it works great. so since the paths have changed does that now mean that binaries would be able to be built?

**Comment by joolswills** [comment]
yep. I will test it, build binaries, and then move it out of experimental - but not right now as I'm off to bed ;-)

**Comment by HerbFargus** [comment]
goodness mate-- yeah thats a great idea :P thanks :)

**Pull request merged**
