### PR TITLE
skyscraper - change location of deployed bash completion file

### PR DESCRIPTION
**Pull request by s1eve-mcdichae1**
Ref: https://serverfault.com/a/1013395

### CODE REVIEW

**Comment by cmitu** [comment]
How about copying it directly into `/etc/bash_completion.d`, it's easier to manage and we get the same result.

**Comment by joolswills** [comment]
Thanks. If someone updates they will be left with the old file so maybe a good idea to delete the old location during install.

**Comment by cmitu** [comment]
> Yes this works as well. I suppose we don't need to `chown` the file here. 

 No.

> Do we ever need to make the directory first or will that always exist?

 In theory, yes, but in practice without `bash-completion` installed (which creates the folder) it won't work anyway. Let's not bother with the creation, but you can add a check to skip the completion if the folder is missing.

**Comment by s1eve-mcdichae1** [comment]
> Thanks. If someone updates they will be left with the old file so maybe a good idea to delete the old location during install.

Do you want to remove the directory too, or just the file?

**Comment by cmitu** [comment]
> Do you want to remove the directory too, or just the file?

I think we want just the file.

**Comment by joolswills** [comment]
Thanks for this - however I decided to merge https://github.com/RetroPie/RetroPie-Setup/pull/3875 which includes this but also has another change.

**Pull request closed without merging**
