### PR TITLE
Lr dosbox pure

### PR DESCRIPTION
**Pull request by joolswills**
Have done limited testing. Put together quickly so need to do some more work (module based off lr-dosbox which was pretty basic).

### CODE REVIEW

**Comment by joolswills** [comment]
Oops. Need to rebase.

**Comment by hlad** [comment]
there should be more valid extensions, not just .zip [https://github.com/schellingb/dosbox-pure/blob/main/dosbox_pure_libretro.cpp#L1765](https://github.com/schellingb/dosbox-pure/blob/main/dosbox_pure_libretro.cpp#L1765)

**Comment by joolswills** [comment]
Thanks - I'll add them.

**Comment by kashkash18** [comment]
When will be add to experimental packets in retropie?

**Pull request merged**
