### PR TITLE
Update in Retropie shortcuts

### PR DESCRIPTION
**Pull request by luizoti**
Update in retropie shortcut
Added Retropie-setup shortcut

### CODE REVIEW

**Comment by joolswills** [comment]
Please can you provide details for this change. Makes it easier to.reciew with an overview. Thank.

**Comment by luizoti** [comment]
1. retropie.desktop, It makes the icon more 'pleasant' for those who use graphical interfaces, no longer be rpi and become Retropie.

2 retropie_setup.desktop, facilitates the opening of 'retropie_setup.sh', as it opens with a simple shortcut.

Is this information you want?

**Comment by luizoti** [comment]
Hi,

Retropie project is giant, but this is a very simple PR, anyone can check and Merge if is valid?

**Comment by joolswills** [comment]
Sorry. I've just not had a chance to test. Also your changes include other bits that are not really needed like the German translation etc. 

Just to check the main issue is the naming of the desktop shortcut?

**Comment by luizoti** [comment]
Ok bro

**Comment by luizoti** [comment]
I dont add de_DE.

**Comment by luizoti** [comment]
This is a pretty simple PR, but it's been months here without being analyzed, I'm going to close.

**Pull request closed without merging**
