### PR TITLE
stella - update to version 6.7

### PR DESCRIPTION
**Pull request by joolswills**
Fixes building on GCC 10+ (The configure script bailed out on GCC 10+ on 6.0.1 which is from 2019)

Changelog since 6.0.1 copied from https://stella-emu.github.io/changelog.html

#### **June 13, 2022**

Stella release 6.7 for Linux, macOS and Windows is now available.

* **IMPORTANT NOTES:**
    * Because of fixes to JSON handling, all remappings will be reset to defaults; if you had custom mappings, they will need to be re-entered again.
    * Because of internal changes, all state files are now invalid.
* Completely reworked the file launcher:
    * Redesigned user interface
    * Added tracking of user favorites, recently played and most popular games
    * Added virtual directories for selecting tracked games
    * Added quick path navigation
    * Added navigation history
    * Added icons for files and directories
    * Added option to show/hide file extensions
    * Extended context menu and shortcuts
    * Fixed sluggish behaviour when reading large and/or invalid files
* Added hotkey display to tooltips.
* Added option to automatically pause emulation when focus is lost.
* Added option to toggle autofire mode.
* Improved controller mappings for Paddles.
* Improved controller mappings for Driving controllers.
* Improved Mindlink support.
* Added another oddball TIA glitch option for score mode color.
* Enhanced TV jitter emulation (TODO: doc).
* Enhanced support for CDFJ+ bankswitching type.
* Added 0FA0 bankswitching for Fotomania ROMs.
* Added ARM chip auto detection.
* Extended support for older BUS (experimental) ROMs that worked with an older, obsolete version of the BUS scheme; special thanks to SpiceWare for the code.
* Fixed Stella crash due to invalid ZIP files.
* Fixed TV mode auto detection in some ARM ROMs.
* Fixed color loss when switching TV mode from/to PAL.
* Fixed score mode glitch emulation corner case.
* Fixed state messages staying on screen forever.
* Added M1 support for the macOS build.
* Debugger improvements:
    * added PlusROM information
    * fixed patching code in ZP-RAM
    * improved bank origin detection
* Updated internal ROM properties database to ROM-Hunter version 17 (thanks go to RomHunter for his tireless research in this area). Related to this, updated the snapshot collection.

-Have fun!

#### **November 16, 2021**

Stella release 6.6 for Linux, macOS and Windows is now available.

* Added preliminary PlusROM support for saving high scores.
* Added preliminary support for 'MVC' bankswitching scheme by Rob Bairos.
* Added web links for many games.
* Added dead zone and linearity settings for analog controllers.
* Added 'Check for Update' button to Help dialog.
* Added different mask patterns for scanline emulation.
* Fixed MindLink controller.
* Fixed SaveKey not working with QuadTari.
* Added TIA randomization on startup option.
* Added different debug color luminances for player and missile copies.
* Added hotkeys for TV roll speed and toggling 'Developer settings' sets.
* Debugger: enhanced prompt's auto complete and history.
* Debugger: added optional logging of breaks and traps.
* Debugger: added Thumb cycle counting.

#### **April 20, 2021**

Stella release 6.5.3 for Linux, macOS and Windows is now available.

* Added context-sensitive help.
* Improved support of multiple monitors with different resolutions.
* Improved analog input reading (Paddles, Keyboards...).
* Fixed QuadTari support for controller types other than Joysticks.
* Fixed palette and TV effects saving for Retron77.
* Fixed immediate disassembling when switching options in debugger.

#### **February 25, 2021**

Stella release 6.5.2 for Linux, macOS and Windows is now available.

* Fixed broken Driving Controller support for Stelladaptor/2600-daptor devices.
* Fixed missing QuadTari option in UI.
* Improved QuadTari timing.
* Added CPU usage stats to ARM cart classes debug widgets.

#### **January 24, 2021**

Stella release 6.5.1 for Linux, macOS and Windows is now available.

* Fixed paddle button bug for jittering controllers.
* Improve switching between joysticks and paddles on Retron77 port.
* Improve memory usage on Retron77 port.

#### **January 9, 2021**

Stella release 6.5 for Linux, macOS and Windows is now available.

* Added high scores saving.
* Improved text editing functionality (except PromptWidget):
    * Enhanced selection and cut/copy/paste from keyboard.
    * Added undo and redo support.
    * Added mouse support (selection, cut/copy/paste).
    * All actions have keyboard shortcuts.
* Various improvements to the ROM launcher:
    * Added wildcard support to the dialog filter
    * Added option to search subdirectories
* Added static tooltips to some UI items.
* Added dynamic tooltips to most debugger items.
* Added sound to Time Machine playback.
* Added browser dialogs for user saved files.
* Extended global hotkeys for input devices & ports settings.
* Moved to using an SQLite database for storing user settings, properties and highscores. More work will follow in future releases.
* Increased sample size for CDFJ+.
* Fixed autofire bug for trackball controllers.
* Fixed bug in TV autodetection in filenames; a filename containing 'PAL' inside a word would sometimes misdetect as a PAL ROM.
* Fixed Stelladaptor/2600'daptor devices sometimes not being assigned correct default mappings.
* Codebase now uses C++17 features, which means a minimum of gcc7 or clang5 for Linux/Mac, and Visual Studio 2019 for Windows.

#### **November 2, 2020**

Stella release 6.4 for Linux, macOS and Windows is now available.

* Added basic (entire and single line only) text cut/copy and paste.
* Added color parameters to 'Custom' palette.
* Some improvements to AtariVox-USB adaptor functionality:
    * Made serial port used for an AtariVox-USB adaptor editable.
    * Autodetection of serial ports no longer messes up devices plugged into other serial ports.
* Added CPU load stats to debugger. Related to this, added debugger pseudo-registers '_ftimreadcycles' and '_fwsynccycles' to show the number of cycles since the start of frame under certain circumstances (see manual for more details).
* Fixed bug with aspect correction and fullscreen mode; snapshots from such a mode are now pixel-exact.
* Fixed a bug that caused CDF ROMs to crash on the Retron77 and reduced ARM emulation performance for CDF ROMs on other platforms.
* Fixed crash with missing or incorrectly sized SaveKey data file, and with certain functions not working (erase pages, erase entire EEPROM).
* Fixed Atari mouse autodetection.
* Fixed bug in ROM launcher, with last ROM selected not being remembered when exiting and re-entering a directory.

#### **October 7, 2020**

Stella release 6.3 for Linux, macOS and Windows is now available.

* Added adjustable autofire.
* Added 'Dark' UI theme.
* Extended global hotkeys for debug options.
* Added option to playback a game using the Time Machine.
* Allow taking snapshots from within the Time Machine dialog.
* Added the ability to access most files that Stella uses from within a ZIP file. This includes the following:
    * Per-ROM properties file (so one can distribute a ROM and its associated properties).
    * Debugger symbol (.sym) and list (.lst) files, etc.
    * Several others, as we extend the support.
* Basically, you are now able to put many files that Stella uses inside one ZIP file, and distribute just that file.
* Extended AtariVox support to handle flow control, so that long phrases are no longer corrupted/cut off. This includes properly supporting the 2600-daptor II, which is flashable to an AVox-USB converter.
* Added auto-detection of the serial port used for an AtariVox-USB adaptor.
* Added QuadTari controller support.
* Added option to select the audio device.
* Added support for CDFJ+ bankswitching type.
* Further enhanced UA bankswitching to support more Brazilian carts.
* Added option to display detected settings info when a ROM is loaded.
* Added another oddball TIA glitch option for delayed background color.
* Added option to disable aspect ratio correct scaling.
* Added debugger pseudo-registers '_timwrapread' and '_timwrapwrite', which are set when the RIOT timer is read/written on timer wraparound, respectively.
* Bankswitching schemes BUS, DPC+ and CDFx now work when startup bank randomization is enabled (these schemes now ignore that setting).
* Replaced "Re-disassemble" with "Disassemble @ current line" in debugger.
* Fixed bug when taking fullscreen snapshots; the dimensions were sometimes cut off.

#### **June 20, 2020**

Stella release 6.2.1 for Linux, macOS and Windows is now available.

* Fixed Pitfall II ROM not working correctly.
* Fixed crashes when using some combinations of bankswitching schemes on incorrect ROMs, or when using invalid ROM file sizes, etc.
* Fixed RIOT timer behaviour on reading/writing at the wraparound cycle.
* Fixed incorrectly setting D6 bit on TIA reads in some cases. Related to this, improve 'tiadriven' option to randomize only D5..D0 bits.
* Fixed custom palette and TV effects adjustable slider rounding issue.
* Fixed some bugs in 3E+ scheme when using non-standard ROM sizes.
* Fixed crash in Audio & Video dialog when opened from debugger, and the debugger window sometimes being resized when using the Options dialog.
* Make NTSC custom phase shift not affect Yellow anymore.
* Fixed '1x' snapshot mode; TV effects are now disabled. This mode now generates a clean, pixel-exact image.
* Fixed mappings sometimes not being saved in the Retron77 port.
* A ROM properties file may now be placed next to the ROM (with the same name as the ROM, except ending in .pro), and Stella will automatically apply the properties to the ROM. [NOTE: this was present in 6.2, but was mistakenly left out of the changelog]
* Added button to Game Info dialog to save properties of the currently loaded ROM to a separate properties file (in the default save directory). This is useful in conjunction with the previous item.
* Allow changing custom palette and TV effects adjustables in 1% steps again.
* Updated documentation for changes in ROM properties key names.
* The codebase now compiles under gcc6 again. Future versions will require gcc7, though.

#### **June 7, 2020**

Stella release 6.2 for Linux, macOS and Windows is now available.

* Added interactive palette to Video & Audio settings.
* Added 'Custom' palette, generated from user controlled phase shifts.
* Added that adjustable audio & video settings are displayed as gauge bars.
* Added four global hotkeys which allow selecting and changing numerous audio & video settings without having to remember the dedicated hotkeys.
* Added 'Turbo' mode, runs the game as fast as the computer allows.
* Added that paddle centering (per ROM) and sensitivity can be adjusted.
* Added that mouse sensitivity for Driving controller can be adjusted.
* Added paddle filtering in UI to avoid unwanted navigation events.
* Added selectable dialog fonts.
* Added separate positioning of launcher, emulator and debugger.
* Added optional display to game refresh rate adaption in fullscreen mode.
* Added option which lets default ROM path follow launcher navigation.
* Added debugger 'saveaccess' function, which saves memory access counts to a CSV file.
* Added displaying last write address in the debugger.
* Added debugger pseudo-register '_scanend', which gives the number of scanlines at the end of the last frame.
* Added detection of color and audio data in DiStella.
* Restored 'cfg' directory for Distella config files.
* Added TV Boy and 3EX bank switching types.
* Removed unused CV+ and DASH bank switching types.
* Added support for loading grayscale PNG images in the ROM launcher.

#### **April 25, 2020**

Stella release 6.1.2 for Linux, macOS and Windows is now available.

* Fixed bug with remapped events not being reloaded in certain cases.
* Fixed bug in debugger for 3E scheme when displaying active RAM bank.
* Fixed bug in "Dragon Defender" ROM being misconfigured for Mindlink controller.

#### **April 4, 2020**

Stella release 6.1.1 for Linux, macOS and Windows is now available.

* Fixed crash in 3E bankswitching scheme when writing to ROM addresses.
* Fix snapshots on Retina HiDPI displays capturing only the top-left corner.
* Fixed wrong color for BK (background) swatch in the debugger.
* Fixed 'Right Diff' button in Command menu changing left difficulty instead.
* Fixed compilation of libretro port on Debian Buster.

#### **March 22, 2020**

Stella release 6.1 for Linux, macOS and Windows is now available.

* **IMPORTANT NOTES:**
    * Because of major event remapping changes, all remappings will be reset to defaults; if you had custom mappings, they will need to be re-entered again.
    * Because of major internal changes, all state files are now invalid.
    * Support for Windows XP has been discontinued as of this version. WinXP is now completely out of support from Microsoft, so we are doing the same.
* Major improvements to display mode handling in NTSC vs. PAL. The window is now the same size for both modes, and scaling is applied to simulate the height of scanlines (in PAL mode, there are more scanlines and hence each is narrower). This more properly emulates how the display would look on a real TV.
* Removed the 'Display_Height' property, changing it to 'Display_VCenter'. This new feature, along with the display mode changes above, almost completely eliminate having to manually tweak each ROM so that it will not have part of the image cut off.
* Removed the 'Display_YStart' property and all automatic detection of ystart. It caused problems on some ROMs, and was not the way a real console would work anyway. Related to this, ROMs now load much faster.
* Major improvements to event remapping:
    * Allow mapping of modifier-key and button-direction combinations
    * Physical controllers can map the same action to different events on different virtual controllers
    * Many more events can be remapped
    * Events can be filtered by type in UI
* Paths have been simplified:
    * The following file/directory locations are no longer configurable (statedir, nvramdir, cheatfile, palettefile, propsfile); they are now all under the base directory
    * Removed cfgdir; Distella config files are now placed with their associated ROMs
    * Added 'basedir' commandline argument, which allows to change the base directory where almost all config-related items are stored; related to this, discontinued the 'basedir.txt' functionality
    * Added 'baseinappdir' commandline argument, which sets the base directory to the application folder (Windows only for now); this replaces the functionality of 'basedir.txt'
* Added automatic controller detection.
* Controllers can be changed during emulation (no ROM reload required anymore).
* Added support for Light Gun controller.
* Added limited KidVid support (8, 9 and 0 start the games).
* Removed superfluous controller option 'PADDLES_IDIR'.
* Added configurable paddle dejittering.
* Key-repeat mode improved; entering Time Machine by holding down a key combo continues to send events (previously, you had to release and then press the combo again).
* Certain buttons in the UI can now be activated repeatedly by holding down the mouse button (Time Machine, debugger step/trace/frame advance, etc.)
* Added option to configure mouse double click speed.
* Added option to configure controller input repeat speed.
* Added high quality scaling.
* Made scanlines better aligned to scaling.
* Added 'HiDPI' mode, which scales the UI by 2x when enabled. This is meant for 4k and above monitors, but can actually be used at any lower resolution that is large enough to display the scaled UI.
* Fixed TIA 'Center' option, Stella now remembers the last windowed position.
* Added fractional (25% increments) TIA zooms.
* Removed 'tia.fsfill' option, replacing it with 'tia.fs_stretch'. This new option allows to preserve TIA image aspect ratio in fullscreen mode, or stretch to fill the entire screen.
* Added configurable 'Overscan' option for fullscreen modes.
* Fullscreen TIA modes no longer assume that desktop taskbars, etc are present, hence they are scaled to the proper fullscreen size.
* Added option to display dialogs in screen corners.
* Added hotkey for sound on/off.
* Enhanced 'Command' menu to display current state and more commands.
* Added option to save and load all TimeMachine states at once.
* Added option to automatically load/save states when entering/exiting emulation.
* Added option to change pitch of Pitfall II music.
* ROM Info Viewer size is not limited to fixed zoom steps anymore.
* ROM Info Viewer can now display multiple lines per property and the bank switching type.
* In file listings, you can now select directories by holding 'Shift' on the first character entered. Entering characters in lowercase still selects files, as before.
* Fixed bug when starting ROMs via MacOS finder.
* Added various developer options for oddball TIAs:
    * stuffed player, missiles and ball move
    * delayed playfield bits and color
    * delayed players and ball VDEL swap
* Disabled some developer options for 'Player settings'.
* Writes to RAM read ports are ignored now.
* Added Developer setting, which breaks on writes to read ports.
* Improved breakpoints to now consider the banks.
* Improved debugger's TIA display and zoom windows.
* Improved hotkeys, now many emulation keys work in debugger too.
* Fixed display of negative values in debugger; sometimes they were shown as positive.
* Reworked ROM properties database, making it load faster in certain cases.
* Updated internal ROM properties database to ROM-Hunter version 16 (thanks go to RomHunter for his tireless research in this area). Related to this, updated the snapshot collection.
* Fixed 'Dancing Plate (Unknown) (PAL)' to use joystick.
* Fixed cheatcode handling in 2K and 4K ROMs.
* Fixed bug where ROMs smaller than 64 bytes were not recognized.
* Fixed bug where frying one ROM was continued with the next ROM.
* Fixed not working 7800 pause key.
* Enhanced UA bankswitching to support certain Brazilian carts.
* Fixed WD bankswitching.
* Added FC bankswitching for Amiga's Power Play Arcade Video Game Album.
* Added auto-detection of display format based on filename.
* Auto-detection of bankswitch scheme by file extension now includes more human-readable formats (not restricted to DOS 3-char length). See the documentation for the new names.
* Fixed bug in DPC+ scheme; 'fast fetch mode' was enabled at startup, when it should be disabled by default.
* Some more work on DPC+ playfield 'jitter' effect for certain older DPC+ driver versions; more ROMs are now detected properly. Special thanks to SpiceWare for his research in this area.
* Added proper Retron77 port.
* Added proper libretro port, and fixed display for OpenGLES renderers.
* PNG/ZIP image support is now conditionally compiled into Stella. All major ports (Linux/macOS/Windows) have it enabled by default.
* SDL/GUI support is now conditionally compiled into Stella. All major ports (Linux/macOS/Windows) have it enabled by default. This is currently needed by the libretro port.
* Updated included PNG library to latest stable version.
* Updated UNIX configure script to work with the gcc version 10 and above.

#### **October 11, 2019**

Stella release 6.0.2 for Linux, macOS and Windows is now available.

* Updated properties database for Pink Panther ROM.

### CODE REVIEW

**Comment by joolswills** [comment]
Have tested this on a RPI4 with Buster and Ubuntu 22.10.

**Comment by fdr4prez** [comment]
I am using RetroPie 4.8 and I've updated the retrorpie script (it now says 4.8.4) and I went into the optional packages and I've attempted to install from source.

I shows that Stella 6.7 is going to be installed, but it fails at the very end.

Did I do something wrong?

Any estimate when this will be added to the standard retropie release?

[rps_2023-03-21_230120.log](https://github.com/RetroPie/RetroPie-Setup/files/11055240/rps_2023-03-21_230120.log)

**Comment by joolswills** [comment]
@fdr4prez This PR is not the place for an error report. Please use the RetroPie forum first for issues.

The error is you ran out of memory. You can install from binary or make sure you have exited ES for additional free memory.

**Comment by joolswills** [comment]
Binaries should have been updated 2-3 weeks ago. Please try again and if you have an issue, open a topic on the forum. Thanks - https://retropie.org.uk/forum/

**Pull request merged**
