### PR TITLE
Suport for i.MX6 platforms

### PR DESCRIPTION
**Pull request by mbroncano**
Added detection and compiler flags for Freescale i.MX6 platforms such as Udoo

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks!

**Comment by joolswills** [comment]
So how well does it all work so far ? Do you have accelerated framebuffer with GLES or does it all run under X? (In which case the x11 flag should be added).

**Comment by mbroncano** [comment]
So far I have tested:
- emulation station
- xboxdrv

It works well under X (I'll be adding the flag right away) and I have still to try in with the FB. 

Later today I'll be starting testing emulators, but it seems to be working quite well already.

**Comment by joolswills** [comment]
the flags are used by modules - so some stuff won't show up if it doesn't have the x11 flag (eg sdl1.2 emulators require rpi or x11)

**Comment by joolswills** [comment]
actually, not quite true, as many of them just have !mali (no framebuffer sdl1.x on odroid-c1), but some will check platforms flags to set the configure options etc.

**Comment by mbroncano** [comment]
I see it now. By the way, maybe the worst problem I'm finding so far if the poor state of the udon repo, missing packages and all (e.g. libcaca-dev, required for libsdl1.2-dev). But it is certainly progressing.

**Pull request merged**
