### PR TITLE
retroarch - update to new version including modules that require new brcm library names - #2091

### PR DESCRIPTION
**Pull request by joolswills**
* include patches for lr-mupen64plus and lr-parallel-n64 until upstream accepts the PRs - https://github.com/libretro/mupen64plus-libretro/pull/39 / https://github.com/libretro/parallel-n64/pull/469

@psyke83 tagging you for review.

### CODE REVIEW

**Comment by psyke83** [comment]
For now, I can confirm that retroarch, lr-parallel-n64 and lr-mupen64plus compile OK. Will be able to actually test later tonight.

Keep in mind that lr-mupen64plus uses audio/video plugins that use SDL2. Please don't forget to cherry-pick my patch to the rpi-2.0.7 branch to make sure jessie is stable.

**Comment by psyke83** [comment]
Update: tested retroarch with lr-mupen64plus, lr-parallel-n64, and some other cores that aren't changed by this PR, and all seems to be working OK.

Maybe it's time to get rid of commit ee41a3f6138aca92ad63cb3179a3634298f1759a, as long as the SDL2 commit is added (as modules not using the flag will no longer have the library names force)? I'm not sure that it's preventing breakage any longer. If you don't want to get rid of that commit yet, RetroArch itself has an SDL2 video option which, although not the default, would necessitate the RP-NEWBRCMLIBS flag to be added to the retroarch scriptmodule.

**Comment by joolswills** [comment]
Yep. Cheers. I plan to remove the flag soon.

**Comment by joolswills** [comment]
Soon= probably right after I bud the bins and merge this.

**Comment by joolswills** [comment]
Build even!

**Comment by joolswills** [comment]
Quick question - why do you think your sdl2 patch is required to remove the NEWBRCMLIBS flag ?

**Pull request merged**
