### PR TITLE
amiberry - add support for whdload auto-load - #2327

### PR DESCRIPTION
**Pull request by joolswills**
* add lha extension
 * adjust launch script to use new -autowhdload parameter
 * rework whdboot folder set-up

### CODE REVIEW

**Comment by HoraceAndTheSpider** [comment]
Visual review, this is looking good - i will try and get a chance for a proper install test later.

**Comment by HoraceAndTheSpider** [comment]
Worked for me from source, but not from binary (the latter only created the whdboot folder?)

**Comment by HoraceAndTheSpider** [comment]
One thing i have noticed is the defaults in `hostprefs.conf` are wrong ... I can fix default on the Dev branch of Amiberry, but it might be a little while till pushed to the Master

basically it tries to use joystick number 2 as a the mouse controller by default. 

```
CONTROLLER_MOUSE_1=joy1
CONTROLLER_MOUSE_2=joy2
```

**Comment by joolswills** [comment]
It won't work from binary until the bins are updated. Can't do much about the hostprefs until it's merged to master. Perhaps upstream can cherry pick that fix for master.

**Comment by HoraceAndTheSpider** [comment]
Great stuff.

The hostconfig fix will be in the next master update, which I am discussing with Dimitris so hopefully we can push that out soon as well.

**Pull request merged**
