### PR TITLE
packages - handle git repositories with two tag references

### PR DESCRIPTION
**Pull request by joolswills**
When the remote repository uses an annotated Git tag, the real commit is found
by looking for the "tag^{}" reference, since the the tag ref will point to the
tag object itself, instead of the tagged commit. See gitrevisions(7).

### CODE REVIEW

**Comment by cmitu** [comment]
Looks fine, but for some reason `advmame` still shows that it needs an update. Need to test more

The description could be shorter:

> When the remote repository used an annotated Git tag, the real commit is found by looking for the "tag^{}" reference, since the the tag ref will point to the tag object itself, instead of the tagged commit. See gitrevisions(7).

**Comment by cmitu** [comment]
I'm thinking that it fails here
https://github.com/RetroPie/RetroPie-Setup/blob/fb5a22cfb75ea977484a0631949c80a263ce39c7/scriptmodules/packages.sh#L628-L635

because `$__ignore_module_date` is un-intialized.

**Comment by cmitu** [comment]
OK, re-tested with `advmame` (where I noticed the issue) and looks fine.

**Comment by cmitu** [comment]
I've found out why the date diff occurs: `${__mod_info[$id/path]}` isnewer than the `pkg_date` because the scriptmodule was updated after building from source happened. Looks reasonable enough - scripmodule changes could produce different results.

**Review by cmitu — APPROVED** [review]

**Comment by joolswills** [comment]
Updated the commit msg / PR description and code comment as suggested.

**Comment by cmitu** [comment]
Mis-spelled the 'the the', copied from my description.

**Comment by joolswills** [comment]
I completely missed that. I changed one word but my brain skipped that. I'll do a cosmetic commit for the comment.

**Comment by joolswills** [comment]
Not the first time "the the" has made trouble hehe

**Pull request merged**
