### PR TITLE
openbor: properly enable dispmanx

### PR DESCRIPTION
**Pull request by cmitu**

### CODE REVIEW

**Comment by joolswills** [comment]
You will a launch script. See xrick for example.

**Comment by cmitu** [comment]
That would work better.

**Comment by joolswills** [comment]
There's logic to switch off dispmanx if launched from X. Also it can be switched off manually for videocore so it can't be hardcoded. Thanks

**Comment by cmitu** [comment]
@joolswills yes, it felt like a hack, 'twas a hack. Should be better now.

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
