### PR TITLE
lipebello themes don't exist anymore :(

### PR DESCRIPTION
**Pull request by meleu**
lipebello deleted his github account due to personal attacks from greedy people plagiarizing and selling his work.
He posted a comment about it on his video here: https://www.youtube.com/watch?v=n7eN4HBcWmc
This is sad... :(

### CODE REVIEW

**Comment by lilbud** [comment]
Well then, thats the first time I've seen that happen.

**Comment by joolswills** [comment]
It's their choice, but I think this is a bit of an overreaction. Oh well.

**Comment by joolswills** [comment]
Sorry but I'm not going to merge this as is as I feel the commit message is unsuitable. I may squash and merge and rewrite it or just remove myself.

**Comment by johnmanko** [comment]
That's so unfortunate. :(

**Pull request closed without merging**
