### PR TITLE
Allow advmame to compile on ODROID, fix ODROID device_keyboard error …

### PR DESCRIPTION
**Pull request by zerojay**
…on launch.

### CODE REVIEW

**Comment by joolswills** [comment]
I had segfaults when launching roms when testing previously on the XU4. This won't work on the C1 as it will enable the module but won't set the options.

**Comment by zerojay** [comment]
No segfault problems for me on XU4 with both advmame-0.94/1.4. Haven't tried 3.5/3.6 though.
I purposely limited the device_keyboard error fix for XU3/4 because I don't know if C1 needs it or not.

**Comment by joolswills** [comment]
it was the 3.5/3.6 versions which I tested.

The C1 would need that change also, but it needs to be tested.

**Comment by joolswills** [comment]
Otherwise you would need to just exclude the c1/c2 boards (if enabling only for the XU).

**Comment by zerojay** [comment]
3.6 segfaults on me with the one game I set up for it. I'll do more extensive testing soon.

**Comment by zerojay** [comment]
A question for you. Since 3.5 and 3.6 seem to not function (to this point anyways), can we remove the !mail flag from 0.94 and 1.4 but keep it on the latest (3.5/3.6)? Does having !mali on 3.5/3.6 cause the calls to use the configure function from the 3.5/3.6 script to not get called? (I believe it's the case but can't say for sure.)

**Comment by joolswills** [comment]
Yes. 

BTW you have put an unrelated to jzintv on here. That uses SDL1 as I remember and it never did used to work, since it didn't work directly on the framebuffer before. I would prefer not to have this on this PR. I'm going to close this and look into advmame later when I have some free time.

**Comment by zerojay** [comment]
Uh, that's strange as that was supposed to be a separate pull request.

**Pull request closed without merging**
