### PR TITLE
uae4arm - game launch script / enhancements

### PR DESCRIPTION
**Pull request by joolswills**
* add default a500 / a1200 configs
 * allow launching directly from adf/dms/zip
 * support multiple disks in zip or if named *Disk1.adf *Disk2.adf as separate files
 * choose a1200 config if filename contains AGA or CD32 else use a500 config

### CODE REVIEW

**Comment by joolswills** [comment]
If anyone has time to test this it would be appreciated - thanks!

**Comment by Darknior** [comment]
Woaw a really great update :D 
@Waal will be very happy with these news features to port our xBox Amiga Pack to Retropie :)
It lacks only the auto whdload now :)

**Comment by skaba** [comment]
Can we make this reusable in other uae forks?

**Comment by joolswills** [comment]
Not unless they use the same commandline parameters and configuration as uae4arm.

**Comment by skaba** [comment]
I don't think I can reuse it directly, I want to port this to lr-puae but addEmulator helper function makes the command retroarch

$emudir/retroarch/bin/retroarch -L $cmd --config $md_conf_root/$system/retroarch.cfg %ROM%

I would need a whole script to run and generate a uae file and pass that as argument instead of %ROM%. I could possibly not name it as lr-puae but would that be the best way?

**Pull request merged**
