### PR TITLE
raspbiantools: Add option to enable compressed memory (ZRAM)

### PR DESCRIPTION
**Pull request by gizmo98**
Add an option which enables ZRAM. ZRAM will which can hold up to 50% of the physical ram.

Compressed memory (ZRAM) can be used with low memory embedded devices. ZRAM has compression ratio of up to 4:1. 256MB of physical memory can store up to 1024MB. It is only used if free memory is getting low. It is much faster than disk swapping. It also prevents linux from using disk swap until ZRAM is full.
https://wiki.debian.org/ZRam
https://haydenjames.io/raspberry-pi-performance-add-zram-kernel-parameters/

Tested with a 2GB Raspberry Pi 4, emulationstation, some retroarch cores and some memory intensive source builds.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks. I think it might be nice to have an option to disable it (and perhaps show whether it's enabled or not ?)

**Comment by gizmo98** [comment]
> Thanks. I think it might be nice to have an option to disable it (and perhaps show whether it's enabled or not ?)

I take a look into /proc/swaps now if a zram device exists. If no zram device exists i only allow to enable zram. If a zram device exists i only allow to disable zram. Please take a look. If everything is right i will squash all commits.

**Comment by joolswills** [comment]
Looks good thanks. Happy to include it.

**Comment by gizmo98** [comment]
Thanks for review! Everything is squashed now. Commit message is updated.

**Comment by joolswills** [comment]
Thank you.

**Pull request merged**
