### PR TITLE
Update Solarus broken game links

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
I updated Solarus to 1.6.0 and fixed the broken Solarus game source links.  I could not find the game source on the Solarus page so I pulled it from gitlab release branches.

### CODE REVIEW

**Comment by hhromic** [comment]
Hi @TechnologyClassroom , I've been also been working on an update Solarus scriptmdule. My current branch is here: https://github.com/hhromic/RetroPie-Setup/tree/solarus

At the moment I've been delaying sending a PR here because I'm working with the Solarus devs upstream to fix some minor things regarding fullscreen mode and improve the usability in RetroPie without a keyboard/manual configuration (gamepad-only setups). Also, because Solarus now supports standalone single `.solarus` files directly for its quests, I'm planning on switching Solarus from Ports-based to a System-based setup using "roms", very much like an emulator for `.solarus` files.

Lastly, did you test your PR on a Raspberry Pi device? In my early tests using the tagged `1.6.0` version it doesn't work on RPI because it needs more recent commits related to the new OpenGL backend. That's why my branch uses the `master` branch from Gitlab.

**Comment by TechnologyClassroom** [comment]
@hhromic I tried it last night and 1.6.0 does not compile.  I could modify this request to use Solarus 1.4.5 in the meantime and the games would be fixed at least.

**Comment by hhromic** [comment]
@TechnologyClassroom I might take a bit more to complete the fixes to the `1.6.x` branch to be fully usable on RetroPie without a keyboard.  So, yes, in the meantime it would be worth to update to a previous version that still works. Just make sure it works on Raspberry Pi devices at very minimum. Thanks!

**Comment by TechnologyClassroom** [comment]
@hhromic I reverted back to 1.4.5.  This patch is still relevant because the game links were broken before.

**Comment by TechnologyClassroom** [comment]
This pull request is not ready yet.  Here is what I have found so far:

My test machine is a Raspberry Pi 3 A+.  I tried to build from source using the original master branch and failed.  I tried my branch the the game folders changed names.  I fixed that.  I reverted the games back to the versions compatible with 1.4.5 while keeping the gitlab links.  Instead of changing the version numbers in four places for each game, I am attempting to configured version variables.

In addition to the packages listed, Solarus 1.6 requires `qtbase5-dev` and `qttools5-dev` dependency packages.

My config for full-screen across all Solarus games I have tried looks like this:
```
$ cat /opt/retropieconfigs/all/videomodes.cfg
solarus_fb = "640x480"
solarus = "DMT-4"
```

**Comment by hhromic** [comment]
@TechnologyClassroom as I said before, Solarus 1.6.x is not really ready yet as it needs improvements at the engine level to compile/work correctly on Raspberry Pi without an X-system. I'm currently working with the upstream developers on fixing these issues and hope to have a fully working version soon so we can update the scriptmodule here in RetroPie accordingly. I will be handling all this later when time allows.

The version of the scriptmodule in my branch (also linked before) is able to compile and run Solarus 1.6 (and I don't need the QT5 dependencies as these are for the quest editor), however the issues I mention in https://github.com/RetroPie/RetroPie-Setup/pull/2453#issuecomment-481909300 (that I'm working on) must still be addressed. I don't think setting `videomodes.cfg` is a suitable solution as that is a very personal file for each user's setup.

At the moment, if you really need it, you can try to fix the older version for this PR. However my priority is on getting Solarus 1.6 working.

**Comment by TechnologyClassroom** [comment]
I am glad that front is moving forward.  I fixed my bugs on my development machine and I should upload them later this evening or tomorrow.  That will at least fix what is there.

**Comment by TechnologyClassroom** [comment]
@hhromic This PR is complete.  The engine and games compile and play on the Raspberry Pi 3 A+.

**Comment by TechnologyClassroom** [comment]
ping

PR is complete.  This fixes what is currently broken.

**Comment by hhromic** [comment]
While it is not in my power to merge pull requests, I have some more updates regarding Solarus 1.6 in https://github.com/RetroPie/RetroPie-Setup/pull/2453#issuecomment-496728813

**Comment by hhromic** [comment]
I finally managed to finish the new scriptmodule for Solarus 1.6.
Please see the forum topic: https://github.com/RetroPie/RetroPie-Setup/pull/2453#issuecomment-504776164

So far all seems to be working fine and feedback is highly appreciated.

Note that the new scriptmodule makes this PR obsolete in case you want to wait for it to be submitted and merged.

**Comment by joolswills** [comment]
Thanks for your work on this. Looks great. Please submit the PR as soon as you are happy.

**Comment by hhromic** [comment]
I finally got some time to finish the new scriptmodule that will supersede this one.
See #2813. Once merged, this PR will be closed. Thanks for your patience!

**Pull request closed without merging**
