### PR TITLE
The Kodi installer adds a new Tab for Kodi to EmulationStation

### PR DESCRIPTION
**Pull request by cschlonsok**
Most users want to use Retropie and Kodi. If they want to install Kodi out of RetroPie, it would be nice to give Kodi a separated Tab.

### CODE REVIEW

**Comment by robertybob** [comment]
+1 for the idea

**Comment by HerbFargus** [comment]
I also like this idea.

**Comment by taalas** [comment]
I would like that as well!

I do have an open Pull Request with the RetroPie fork of Emulationstation which adds the option to have direct launch items in the Emulationstation menu, meaning Kodi would start without the need for a sub-menu. Might be relevant here, I thought :)

**Comment by polzy** [comment]
Hi,
i need OSMC :(  It's possible to chose kodi or OSMC ?

**Comment by HerbFargus** [comment]
Also just for reference- I've added the imagery from above into the simple theme repo which simplifies the script. An updated script can be found here:

https://github.com/RetroPie/RetroPie-Setup/wiki/KODI#kodi-15

**Comment by mcobit** [comment]
| i need OSMC :( It's possible to chose kodi or OSMC ? 

OSMC is a distribution using kodi. There is no choice ;-)
But there is a way to have both now:
https://discourse.osmc.tv/t/howto-retrosmc-retrogaming-on-osmc/6671

**Comment by HerbFargus** [comment]
This may be more viable now that we have the direct launch function.

**Comment by joolswills** [comment]
This is now implemented.

**Pull request closed without merging**
