### PR TITLE
downloadAndExtract() Allow sending additional options to the unzip pr…

### PR DESCRIPTION
**Pull request by sigboe**
downloadAndExtract() Allow sending additional options to the unzip program, like how the description of the function says.

I tried to edit the previously opened [pull request](https://github.com/RetroPie/RetroPie-Setup/pull/2628), but when I deleted all the commits the pull request got closed. :smile: 

I have made the changes the way @joolswills asked.

### CODE REVIEW

**Comment by joolswills** [comment]
There is a minor change needed, but I think it might just be easier for me to make the changes myself than update this PR and squash etc. But thanks for the heads up.

**Comment by joolswills** [comment]
BTW checking the original code code - this worked before due to the fact `$opts` is not quoted when sent to zip. with your changes it should be quoted though. What problem were you having with the function? Are you sure it's broken and if so can you give an example?

**Comment by joolswills** [comment]
And the documentation for the function would need to be updated also with your changes. Please give me your example that doesnt work and I will adjust the function as needed.

**Comment by joolswills** [comment]
allowing additional arguments is more flexible of course, as you could include parameters with spaces then, but I may be inclined if changing it to multiple arguments, so change the way the tar code works with the stripping of components.

**Comment by sigboe** [comment]
@joolswills I was unable to only extract one file from a tar archive. Beacuse it didn't pass the next argument into tar.

**Comment by joolswills** [comment]
ok. I will extend it to support passing additional arguments to tar - your PR title didn't mention this but instead said it was a problem with unzip parameters.

**Comment by hhromic** [comment]
@joolswills the scriptmodule for hexen2 in PR #2595 also would benefit from this improvement. See my comments left to the author https://github.com/RetroPie/RetroPie-Setup/pull/2595#issuecomment-467061776, in particular for the `game_data_hexen2()` function.
In that function, the author also needs to extract only one folder from within the tgz file.

**Comment by sigboe** [comment]
@joolswills Here is an example of what I need to do without this PR

```
downloadAndExtract "http://constexpr.org/innoextract/files/snapshots/innoextract-${innoversion}/innoextract-${innoversion}-linux.tar.xz" "$md_inst/innotemp" 2
		mv "$md_inst/innotemp/armv6j-hardfloat/innoextract" "$md_inst/"
rm -rf "$md_inst/innotemp"
```

Here is what I can do with this PR

    	isPlatform "arm" && downloadAndExtract "http://constexpr.org/innoextract/files/snapshots/innoextract-${innoversion}/innoextract-${innoversion}-linux.tar.xz" "$md_inst" 3 innoextract-${innoversion}-linux/bin/armv6j-hardfloat/innoextract

You see I just use the following argument to say what file I want. Instead of extracting many and pick the file I want. I can even drill down deeper, since there are several files of the same name (in directories for different architectures), and they overwrite each other if I strip 3 without picking one to extract instead of extracting everyone.

**Comment by sigboe** [comment]
@joolswills 

1. I updated both the comment, and quoted the array for unzip, like you wanted.
2. I fixed a typo in the tar cmd array (ops it was not in my previous PR)
3. I squashed it.
4. I learned to squash a commit (but I still need to google it the next time lol)

**Comment by joolswills** [comment]
Thanks. Appreciate the changes - however, I may not use this PR as I am considering to re-factor the arguments so the strip components part is not included at all (and adjust our other modules etc).

**Comment by hhromic** [comment]
@joolswills was thinking exactly on the same :), that it should be more generic. Great you want to improve it.

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/pull/2634

I just threw this together quickly. I will need to double check everything looks and test before merging.

**Comment by sigboe** [comment]
This has been implemented in another way now.

**Pull request closed without merging**
