### PR TITLE
Add licence and package flag summary pages

### PR DESCRIPTION
**Pull request by mmatyas**
As discussed on [the forum](https://retropie.org.uk/forum/topic/24210/pi-4-support-progress-and-other-package-infos/), this patch adds two new admin modules for generating visual package informations, for listing licences and platform support based on the package flags.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks. Appreciated - this is probably my fault for not being clearer but my idea was for something like this to be integrated into RetroPie-Setup rather than using external repos - and for example using our arrays with the package information rather than grepping etc. So all the code would be part of RetroPie-Setup.

**Comment by joolswills** [comment]
(The javascript could be pulled in, but I would like all custom code to be included as part of our codebase - and so on).

**Comment by mmatyas** [comment]
Ah I see, sure, that could be done too. Should I just place the static website files in a new directory under `admin`?

**Comment by joolswills** [comment]
Yeah same name as module. You can access via `$md_data`

**Comment by joolswills** [comment]
Happy to give some examples/help if it's useful. Check out `scriptmodules/packages.sh` as for example the code to list all modules etc is in there. The arrays with all the module info are defined in that file also.

**Comment by mmatyas** [comment]
Ok, updated, now everything happens locally and using the module infos.

**Comment by hhromic** [comment]
This is really fantastic, thanks for the contribution!

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
