### PR TITLE
Update lr-stella due to rebrand

### PR DESCRIPTION
**Pull request by LeePorte**
stella has rebranded to become stella2014. This commit reflects that
change and now enable the build and install to complete.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks. However, it requires a little more than just renaming. I will sort this out later / over the weekend.

**Comment by LeePorte** [comment]
It ran without issue from my branch, though I'm interested to learn if there are additional changes required.

Every day is a learning day :)

**Comment by joolswills** [comment]
I will rename the module and shift configs.

**Comment by joolswills** [comment]
see https://github.com/RetroPie/RetroPie-Setup/pull/2691

**Pull request closed without merging**
