### PR TITLE
RPi stretch binary-only compatibility patching

### PR DESCRIPTION
**Pull request by psyke83**
Hi @joolswills,

This seems like the ideal solution for our legacy/binary only items. I've confirmed that giana, rpix86 and coolcv work perfectly on stretch after patching with this PR.

This PR can be expanded to all other binary packages. Can you let me know what other binary-only software is distributed by the script and thus may potentially need patching?

Should help towards resolving #2091.

### CODE REVIEW

**Comment by joolswills** [comment]
Can't think of any others currently. Could use a function to de-dupe here a bit, but maybe not worth it if there are only 4 needed (and this is hopefully temporary until the upstream projects rebuild etc).

Please use printMsgs instead of echo.

**Comment by psyke83** [comment]
I think the helper would be a good idea (as it can catch all possible renamed libraries in case we find more software needing patching), but where would t be acceptable for you? Here?

```
diff --git a/scriptmodules/system.sh b/scriptmodules/system.sh
index 6155e240..68f9bd00 100644
--- a/scriptmodules/system.sh
+++ b/scriptmodules/system.sh
@@ -191,6 +191,20 @@ function get_rpi_video() {
     export PKG_CONFIG_PATH="$pkgconfig"
 }

+function patch_rpi_video() {
+    local filename="$1"
+
+    getDepends patchelf
+    # replace all instances of old graphics library names with new names
+    printMsgs "console" "patching: $filename"
+    patchelf --replace-needed libEGL.so libbrcmEGL.so \
+             --replace-needed libGLES_CM.so libbrcmGLESv2.so \
+             --replace-needed libGLESv1_CM.so libbrcmGLESv2.so \
+             --replace-needed libGLESv2.so libbrcmGLESv2.so \
+             --replace-needed libOpenVG.so libbrcmOpenVG.so \
+             --replace-needed libWFC.so libbrcmWFC.so "$filename"
+}
+
```
I'm not sure it's worth putting in helpers.sh, as runcommand would never need it (and we've already got get_rpi_video right there in system.sh).

**Comment by joolswills** [comment]
I would prefer helpers.sh - thanks.

**Comment by joolswills** [comment]
Thanks!

**Pull request merged**
