### PR TITLE
addPort - remove script parameter and handle in scriptmodule

### PR DESCRIPTION
**Pull request by joolswills**
@hhromic I was thinking to just to it like this - simplifies it I think.

### CODE REVIEW

**Comment by hhromic** [comment]
Yep, definitively this looks cleaner/simpler.
Perhaps I would only add a small comment in the scriptmodule to explain why this "override" is done, future devs might appreciate. Something like this:
```sh
addPort "$md_id" "cavestory" "Cave Story" "$md_inst/nxengine_libretro.so"
# custom launch script: if the main executable is not found, warn the user
local file="$romdir/ports/Cave Story.sh"
```

ps: ah sorry forgot to remove the stdin snippet in the help before :)

**Comment by hhromic** [comment]
looks good to me

**Comment by actraiser30** [comment]
Hi, where is the addPort_custom_script in the retropie setup menu?

**Comment by joolswills** [comment]
Please use the forum for help.

**Comment by actraiser30** [comment]
i cannot find any info in the forum

**Comment by joolswills** [comment]
You can ask - this is not the right place for help.

**Comment by actraiser30** [comment]
anyway,it will be great to add such a feature to retropie so people can add a custom port by them self.

**Comment by joolswills** [comment]
you can do this already by writing a scriptmodule.

**Comment by actraiser30** [comment]
Anyway thanks it will be great to include such a script in the retropie setup menu for manual port installing
sorry for mess with your post here.

**Pull request merged**
