### PR TITLE
Pass platform through to make commands (at least for Raspberry Pi).

### PR DESCRIPTION
**Pull request by c0d3h4x0r**
This is a partial fix for https://github.com/libretro/mame2010-libretro/issues/130

### CODE REVIEW

**Comment by c0d3h4x0r** [comment]
Please read https://github.com/libretro/mame2010-libretro/issues/130 — it should answer all of your questions.

**Comment by dankcushions** [comment]
given that mame2003's makefile had similar requirements, i presumed we passed platform in by default: https://github.com/libretro/mame2003-libretro/blob/master/Makefile#L166

but i guess we don't? maybe we should? in the case of mame2003 i think we do all/most of those compiler flags by default, so maybe it doesn't make a difference. i guess it depends on whether you want to be in control of the compiler flags, or let the upstream makefile. personally i would probably want the makefiles to be the master.

in the case of mame2010, it looks like you could use the ARM_ENABLED flag that we DO pass through already to avoid these x86 specific paths, but that would require a further change to https://github.com/libretro/mame2010-libretro/pull/132/files, when it probably already solves the issue for lakka and so forth, who presumably use the platform flag.

**Comment by joolswills** [comment]
we intentionally don't pass platform flags in most cases as we want to handle compiler flags etc ourselves. I would prefer to handle any other makefile flags ourselves rather than using the platform=

**Comment by joolswills** [comment]
I checked out the makefile. In this case passing just platform=rpi would be sufficient (so we avoid the cpu flags). although probably we could just set signed-char (if it's needed) and FORCE_DRC_C_BACKEND = 1 if that's the actual fix (The other changes look just like whitespace changes - would be better in another commit btw - makes things more readable).

**Comment by c0d3h4x0r** [comment]
lr-mame2010 maintainers have accepted my pull request for the related changes on their side, so now it’s just up to you to decide whether you want to take this fix or come up with your own different approach.  I’ve done my part by making you aware of the issue and proposing a reasonable (and working) fix.

**Comment by ginkage** [comment]
Just to add my 5p, this does fix the aforementioned error for me on RPi4 with mame2010.
The core itself is still painfully slow, but at least this fix makes it work.

**Comment by joolswills** [comment]
Closing as should have been resolved in 77005667

**Pull request closed without merging**
