### PR TITLE
sdl2 - update to 2.28.5

### PR DESCRIPTION
**Pull request by joolswills**

### CODE REVIEW

**Comment by cmitu** [comment]
I've been updating my repo with our patches over the SDL2's releases.
Latest SDL2 version (right now) is 2.30.2, rebased at https://github.com/cmitu/SDL/tree/retropie-2.30.2.

**Comment by cmitu** [comment]
Latest SDL2 release (2.30.4) is rebased in the [2.30.4](https://github.com/cmitu/SDL/tree/retropie-2.30.4) branch.

**Comment by cmitu** [comment]
[retropie-2.30.5](https://github.com/cmitu/SDL/tree/retropie-2.30.5) is now available, based on the recent 2.30.5 SDL2 release.

**Comment by cmitu** [comment]
[retropie-2.30.7](https://github.com/cmitu/SDL/tree/retropie-2.30.7) branch has rebased patches over the latest SDL2 release.

**Comment by joolswills** [comment]
Closing in favour of #3975

**Pull request closed without merging**
