### PR TITLE
mupen64plus: Pi: temporarily workaround texture rendering/segfault issue

### PR DESCRIPTION
**Pull request by psyke83**
May be reverted later - see: https://github.com/gonetz/GLideN64/issues/1665

### CODE REVIEW

**Comment by psyke83** [comment]
Confirmed to resolve the texture issue (only tested on stretch but I don't imagine issues with jessie).

BTW - I can see a black/semi-transparent(?) FPS counter. It's caused by this:
```
            # Enable FPS Counter. Fixes zelda depth issue
            iniSet "ShowFPS " "True"
            iniSet "fontSize" "14"
            iniSet "fontColor" "1F1F1F"
```
Is this workaround still necessary or can we get rid of it?

**Comment by gizmo98** [comment]
FPS Counter is necessary to fix depth issues with fb emulation.

**Comment by joolswills** [comment]
thanks.

**Comment by joolswills** [comment]
(rebuilding bins)

**Pull request merged**
