### PR TITLE
runcommand.sh: assign space to button B

### PR DESCRIPTION
**Pull request by crcerror**
This change will make radiolists and checklists useable

```
#!/bin/bash
pizza=`dialog --checklist "Pizza with ..." 0 0 4 \
 cheese "" on\
 chicken "" off\
 ham "" off\
 tuna "" off 3>&1 1>&2 2>&3`
dialog --clear
clear
echo "Your order: Pizza with $pizza"
```

### CODE REVIEW

**Comment by joolswills** [comment]
We don't include any radiolists / checklists. But we need tab - 227b65e5ef6c3dcf05ead85819e1053ae13c7a58

**Comment by joolswills** [comment]
If you have some additional dialog, you can include joy2key in it and remap additional buttons.

**Comment by crcerror** [comment]
I know how to utilize the joy2key script.
But checklists may be usefull if you want to install more than one theme/emulator/port

I can show you a good usecase of such dialogs (hopefully) soon. But I must admit I was not aware that the space key was utilzed in 2015 :)

**Comment by crcerror** [comment]
> 
> 
> If you have some additional dialog, you can include joy2key in it and remap additional buttons.

[Midnight Joy --- Midnight Commander useable with joypad](https://retropie.org.uk/forum/topic/19267/)

**Comment by joolswills** [comment]
How about we map button 3 as space?

**Comment by crcerror** [comment]
honestly I think it is not neccesary. As you said we can source the code in own scripts and exchange the button. As long as there is no need because you always use `--menu` form for all dialogs we can left code as it is.
Maybe for RetroPie v4.5 if you decide to use radio/selection lists then it would make sense. Just my opinion.

**Comment by crcerror** [comment]
@joolswills As promised usage of this feature can be found here
https://retropie.org.uk/forum/topic/15961
Thank you for maintaining RetroPie :)

**Pull request closed without merging**
