### PR TITLE
$biosdir needs to be initialised in runcommand launch scripts

### PR DESCRIPTION
**Pull request by dankcushions**

### CODE REVIEW

**Comment by hhromic** [comment]
What this change really addresses?
The correct display of the dialog box message if there are no BIOSes found (which uses `$biosdir`)?

**Comment by dankcushions** [comment]
precisely. it also tidies up the code a little.

**Comment by hhromic** [comment]
Just wanted to confirm. I agree with your changes :)

**Comment by joolswills** [comment]
Where does it hardcode it twice? I only see one change here?

Actually really this should be passed in from calling script so it's not hardcoded at all. But I'm also not sure we need this "helper" dialog.

**Comment by joolswills** [comment]
Ah I see. It referenced it before so it wasn't working (missed that). I think I'd just remove the dialog still.

**Comment by dankcushions** [comment]
You don't think it's useful? It was useful to me as I didn't have the BIOS files in the right place (they were changed to a /dc/ subfolder since the last time I used it. It just had a small bug :)

**Comment by joolswills** [comment]
We don't do it for other platforms that need bios files so it seems inconsistent. If we are to have this we shouldn't hardcode this at all in the file though.

**Comment by joolswills** [comment]
I'll merge it, as it had a bug, but I think I'd rather remove it still tbh.

**Pull request merged**
