### PR TITLE
Changed default video_smooth from true to false.

### PR DESCRIPTION
**Pull request by dankcushions**
As per https://github.com/RetroPie/RetroPie-Setup/issues/1288
Looks like debate has settled in the forum thread.

### CODE REVIEW

**Comment by joolswills** [comment]
it would have been polite to wait for agerement on the ticket from me - Don't know why you think I would need a one line pull request on this ?

**Comment by dankcushions** [comment]
No offence intended. I thought we were all in agreement in the ticket that the users had spoken.

**Comment by joolswills** [comment]
We were in agreement as to how the results looked - but bear in mind how few people responded considering the size of the userbase. I am not as convinced as you, hence I want to make other changes alongside it which you will see I have mentioned on the ticket and would have been brought up had you asked before jumping ahead.

**Comment by joolswills** [comment]
anyway - no offence, just don't want this rushed - you will get your change. We also need to consider whether it's worth changing the shader default from off to on (but the shader unset), as this was all connected to the change to video smooth being set on originally.

**Comment by joolswills** [comment]
We should probably move discussion to ticket but I agree there are things to be considered. ;-)

**Pull request closed without merging**
