### PR TITLE
initial version of module to use Steven Selph's scraper #945

### PR DESCRIPTION
**Pull request by joolswills**
@HerbFargus please give this a go - no config options yet, but it can go in as a basic scraper and be improved later. i've only tested a little bit.

### CODE REVIEW

**Comment by HerbFargus** [comment]
will do

**Comment by HerbFargus** [comment]
So I take it you opted for .emulationstation storage by default. on inital tests it all seems to work fine. 

I'm working on a theme right now with rookervik that will be meant for use with screenshots instead of thumbnails so at least those two options would be good- I don't know how many other people use different settings. I know thumbnails is preferable for the pi in general just to keep the memory usage down.

**Comment by HerbFargus** [comment]
except images don't show...

**Comment by joolswills** [comment]
I probably made an error with a path. I'll check / debug

**Comment by HerbFargus** [comment]
the other metadata shows up fine

**Comment by joolswills** [comment]
I just scraped mame-mame4all and the images are showing up here. I may need to see copies of your gamelists and have you verify if images were downloaded etc ~/.emulationstation/downloaded_images

**Comment by HerbFargus** [comment]
Yeah they were downloaded, its possible I have conflicts from the manual install i did of sselphs scraper before this. I'm reimaging with a fresh 3.0 image just to make sure.

**Comment by HerbFargus** [comment]
Ok must have been something with my build. works perfectly on a fresh image

**Comment by joolswills** [comment]
I'm going to merge it now, and then do improvements later then (configs etc and so on - and tweaks of parameters). Will be good to get feedback from users. Thanks for the help.

**Comment by HerbFargus** [comment]
No thank YOU! :)

**Comment by robertybob** [comment]
I think now that new themes are being made, that the thumbs option shouldn't be the default. With more users running the RPi2 and some themes being image-only (no release date, details etc), I think scraping the largest size photos possible is the best idea. ES will always resize them down after all. 

Tbh I scrape using the Windows version of sselph's scraper so never use any -flags, then I use an image resizer software to make all images the same size (I'm OCD like that). What I've found is that not all images are the same size on TGDB and it can take a couple of months for replacement images to me moderated. 

Perhaps in the future there could be an option of resizing images through RetroPie - we could come to some kind to agreement here on idea sizes for each console and have one option per system.

**Comment by joolswills** [comment]
The ticket would be a better place as this request is now closed :)

**Pull request merged**
