### PR TITLE
Incorporate Herb's mkdocs work into a module

### PR DESCRIPTION
**Pull request by joolswills**
Renamed existing docs module to apidocs.
Added this one as wikidocs.

```
sudo ./retropie_packages.sh wikidocs
```

to generate

```
sudo ./retropie_packages.sh wikidocs upload
```

to push to the site (requires your ssh public key in retropie account on our server - we can sort that if you want to test).

docs end up here

https://retropie.org.uk/wikidocs/

thanks for your work on this

### CODE REVIEW

**Comment by joolswills** [comment]
Still uses github for the assets - was thinking we could download all the assets and rewrite the markdown or something so the assets are hosted with the docs etc.

**Comment by joolswills** [comment]
That can be done later of course - just an idea.

**Comment by HerbFargus** [comment]
It's looking good so far and the modules are working

But it seems that it isn't changing with updates:

for example I added a line about exiting emulationstation before manually editing gamelist.xmls right above the following heading:

https://github.com/RetroPie/RetroPie-Setup/wiki/Scraper#emulationstation-built-in-scraper

I built the site with

    sudo ./retropie_packages.sh wikidocs

and in `~/RetroPie-Setup/tmp/wikidocs/Scraper` the edits show  but on deploying with

    sudo ./retropie_packages.sh wikidocs upload

It doesn't show the latest edits so I'm not sure if the sync or copy is working or perhaps it's cached. I ran it under a private window in firefox but still no change

**Comment by HerbFargus** [comment]
And yes down the road might be worth considering hosting out own assets once the pages are cleaned up and we have our assets sorted.

**Comment by HerbFargus** [comment]
Oh and one other idea that may be worth looking at is perhaps a webhook of sorts that automatically generates the wiki at end of day or listens for changes in the wiki and updates anytime an edit is made.

**Comment by joolswills** [comment]
Not sure about the updating - but can't test current as the yml needs updating with the page name changes. Please can you provide me with an updated/working yml and I will look into that issue.

**Comment by joolswills** [comment]
Aah you have done the changes on the other repo? I will change the script to pull from there as discussed.

**Comment by joolswills** [comment]
I changed the script to use the other repo - building and uploading was fine and the changes were shown up so I can't reproduce the issue. Please test though and if you still have the issue post a log.

**Comment by HerbFargus** [comment]
I ran a few tests last night after our discussion and was able to get it working and pushed online. I'll test again this evening but as far as I can see it functions as intended.

**Comment by joolswills** [comment]
thanks.

**Pull request merged**
