### PR TITLE
added some lipebello's themes

### PR DESCRIPTION
**Pull request by meleu**
Namely:
- retrorama: https://www.youtube.com/watch?v=xZo3tmqqkhM
- strangerstuff: https://www.youtube.com/watch?v=Avtqd0lthMg
- spaceoddity: https://www.youtube.com/watch?v=HixjBvEzx7w
- swineapple: https://www.youtube.com/watch?v=inCWJwXr6B0

### CODE REVIEW

**Comment by joolswills** [comment]
Please can you confirm they want them added. I don't want to have to remove them as before - they re-uploaded but it's worth confirming.

**Comment by meleu** [comment]
@lipebello would you like to see your themes installable via RetroPie-Setup?

**Comment by lipebello** [comment]
Sure, that way people can install them easly. Thanks a lot!

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
