### PR TITLE
retroarch - update to v1.8.5 and rebase/rework patches

### PR DESCRIPTION
**Pull request by joolswills**
* remove patch 04_fix_corrupted_widgets as fixes are in v1.8.5
 * 01_hotkey_hack and 02_disable_search needed reworking due to source changes

### CODE REVIEW

**Comment by joolswills** [comment]
Tested working on rpi4 only so far.

**Comment by hhromic** [comment]
Tested working on rpi3b with legacy drivers here. All seems fine.

**Comment by joolswills** [comment]
Thanks. I tested on Mali also. I will merge and rebuilt binaries later.

**Comment by macropin** [comment]
@joolswills Sure it's working on rpi4? I tested, and it fails to link
```
--- snip
CC cores/libretro-ffmpeg/packet_buffer.c
CC cores/libretro-ffmpeg/video_buffer.c
CC libretro-common/rthreads/tpool.c
CC tasks/task_decompress.c
CC led/drivers/led_rpi.c
LD retroarch
/usr/bin/ld: obj-unix/release/gfx/drivers_shader/shader_gl_core.o: in function `gl_core_shader::Framebuffer::init()':
shader_gl_core.cpp:(.text+0x334): undefined reference to `glTexStorage2D'
/usr/bin/ld: shader_gl_core.cpp:(.text+0x484): undefined reference to `glTexStorage2D'
/usr/bin/ld: obj-unix/release/gfx/drivers_shader/shader_gl_core.o: in function `gl_core_shader::Pass::build_semantic_uint(unsigned char*, slang_semantic, unsigned in
t)':
shader_gl_core.cpp:(.text+0xa24): undefined reference to `glUniform1ui'
/usr/bin/ld: shader_gl_core.cpp:(.text+0xa58): undefined reference to `glUniform1ui'
/usr/bin/ld: shader_gl_core.cpp:(.text+0xaa0): undefined reference to `glUniform1ui'
/usr/bin/ld: shader_gl_core.cpp:(.text+0xabc): undefined reference to `glUniform1ui'
/usr/bin/ld: obj-unix/release/gfx/drivers_shader/shader_gl_core.o: in function `gl_core_shader::Pass::build_commands(gl_core_shader::Texture const&, gl_core_shader::
Texture const&, gl_core_viewport const&, float const*)':
shader_gl_core.cpp:(.text+0x1810): undefined reference to `glBindBufferBase'
/usr/bin/ld: shader_gl_core.cpp:(.text+0x19dc): undefined reference to `glBindBufferBase'
/usr/bin/ld: obj-unix/release/gfx/drivers_shader/shader_gl_core.o: in function `gl_core_cross_compile_program':
shader_gl_core.cpp:(.text+0x5774): undefined reference to `glGetUniformBlockIndex'
/usr/bin/ld: shader_gl_core.cpp:(.text+0x5794): undefined reference to `glGetUniformBlockIndex'
--snip
/usr/bin/ld: gl_core.c:(.text+0x343c): undefined reference to `glClientWaitSync'
/usr/bin/ld: gl_core.c:(.text+0x3444): undefined reference to `glDeleteSync'
/usr/bin/ld: gl_core.c:(.text+0x3588): undefined reference to `glFenceSync'
/usr/bin/ld: obj-unix/release/gfx/drivers_font/gl_core_raster_font.o: in function `gl_core_raster_font_upload_atlas':
gl_core_raster_font.c:(.text+0x1d0): undefined reference to `glTexStorage2D'
collect2: error: ld returned 1 exit status
make: *** [Makefile:201: retroarch] Error 1
/home/pi/RetroPie-Setup
Could not successfully build retroarch - RetroArch - frontend to the libretro emulator cores - required by all lr-* emulators (/home/pi/RetroPie-Setup/tmp/build/retroarch/retroarch not found).
```

**Comment by joolswills** [comment]
Fine here yes. You need to provide more details of set up.

**Comment by macropin** [comment]
@joolswills RPi4, running Raspbian buster. Building using Retropi-Setup branch master. Let me know if I've missed anything.

**Comment by joolswills** [comment]
I will need a full log (use a pastebin site rather than including a large log here). Binaries are available so it should be using that also unless you are forcing a source install.

**Comment by macropin** [comment]
@joolswills https://pastebin.com/w2VR7FCP

**Comment by joolswills** [comment]
Don't have time to compare logs until later today but it builds fine here on buster. Just did a quick test. For now I recommend using the binary install.

**Pull request merged**
