### PR TITLE
Update esthemes.sh

### PR DESCRIPTION
**Pull request by RetroHursty69**

### CODE REVIEW

**Comment by joolswills** [comment]
Please can you use a more detailed commit message in the future - eg

```es-themes - added RetroHursty69 snazzy theme```

**Comment by RetroHursty69** [comment]
Hi Jools, sorry I did not know. Will do.

Regards
Dwayne

**Comment by joolswills** [comment]
No probs. I did a squash merge and adjusted the description this time. Thanks for your contributions/themes.

**Comment by RetroHursty69** [comment]
Do you mind if I ask about ES? I was wondering DEV’s have anything on their to do list to try and improve theme performance so it can handle loading more images without getting white screens. I usually have to push VRAM to 150MB.

Regards
Dwayne

**Comment by joolswills** [comment]
The forum would be the best place for ES discussion. The white screen issue should have been mostly solved though (images are loaded/freed on demand).

**Pull request merged**
