### PR TITLE
Support multiple device IDs when auto-mapping controllers.

### PR DESCRIPTION
**Pull request by MisterTea**
The script that auto-configures retroarch assumes that there's only one inputconfig.  In my case, I have two different usb joysticks that I'm using, so there are two entries.  With the current script, it concatenates the scripts and is not desired behavior.  With this pull request, it loops through the configs and handles each inputconfig correctly.

### CODE REVIEW

**Comment by joolswills** [comment]
I thought that the temporaryinput.cfg which it works off only has a single entry for the last configured controller though ? Unless I am misunderstanding your change ?

**Comment by joolswills** [comment]
Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.

**Comment by MisterTea** [comment]
Hey, I haven't had a chance to look at this yet but I'll take a look later
this week.

**Comment by joolswills** [comment]
Closing due to no activity. Can be re-opened if needed.

**Pull request closed without merging**
