### PR TITLE
Added experimental script for ResidualVM

### PR DESCRIPTION
**Pull request by zerojay**
Using pretty much the exact same setup as SCUMMVM with the exception of one particular configure flag. Tested with Grim Fandango in software mode on an overclocked Raspberry Pi 2, working well aside from laggy movies as far as I've seen to this point. OpenGL crashes the program entirely. Disabled "Fullscreen" to get full screen, ironically. Recognized joystick controls on its own without issue. Loading games directly from emulationstation works however it appears that the settings used in the ResidualVM GUI are ignored when launched in this manner. Might have to take a look and see if SCUMMVM has similar behavior. 

(I appeared to be unable to squash this for whatever reason.)

### CODE REVIEW

**Comment by joolswills** [comment]
it needs squashing as we don't want the merge commit you have on your branch. you did  git rebase -i HEAD~2 ?

**Comment by zerojay** [comment]
When I attempt to do so, the merge commit does not come up as one of the potentials for squashing. I get this when I attempt to rebase. Could it be because I branched after I made the merge commit?

pick 3943cf4 Fix MESS BIOS hashes incorrect placement.
pick 80ff31d Added ResidualVM script.

# Rebase 37452a6..80ff31d onto 37452a6 (2 command(s))

**Comment by joolswills** [comment]
ill do it manually.

**Comment by joolswills** [comment]
I cherry-picked it from your branch. Your main problem is you are committing stuff to master on your fork - much easier to keep that synced with ours (so no merge commits needed), and then branch that off for doing pull requests.

**Comment by joolswills** [comment]
(you can then throw away those branches once they are merged)

**Pull request merged**
