### PR TITLE
added ppsspp experimental emulator

### PR DESCRIPTION
**Pull request by joolswills**
Please give it a go. Works here - testing with the excellent "Suicide Barbie" demo currently.

Performance probably could be a bit better as we are not building for arm7 due to current problems with ppsspp and arm7 target on the rpi.

### CODE REVIEW

**Comment by HerbFargus** [comment]
I'll give it a go- whats the estimated compiling time on the rpi2?

**Comment by joolswills** [comment]
The demo crashed - but it worked for a while :) There will be lots of bugs and unplayable stuff of course. 

Not too about build time as not timed it building just on the rpi2. 30 mins + ?

**Comment by HerbFargus** [comment]
just under an hour to build on the rpi 2- testing games shortly

**Comment by joolswills** [comment]
note you will need to add some config to platforms.cfg - ive not committed that yet (or run it manually from terminal)

**Comment by HerbFargus** [comment]
That is Brilliant! I am really surprised at how well this works. I tested it out with Harvest Moon Hero of Leaf Valley.  There was a bit of an audio lag at parts but ran quite well. haven't changed any default settings or anything. and yeah I noticed the lack of platforms .cfg simple enough to add .iso to the es_systems.cfg

**Comment by joolswills** [comment]
should the libretro core work ok - I will do some de-duplicating between them, and push it to this branch also.

**Comment by joolswills** [comment]
glad it's working for you. :) and it built/ran. which is the main thing

**Comment by HerbFargus** [comment]
Granted it wasn't a direct launch, selecting the game opened up the ppsspp menu and then I had to navigate to my game from there. I also didnt test with a controller, I only tested with a keyboard.  and hopefully the libretro core will work as well :) lr configs would be ideal

**Comment by joolswills** [comment]
the libretro core works, so ill push that shortly

**Comment by HerbFargus** [comment]
This will make many people happy. Brilliant mate :)

**Comment by joolswills** [comment]
added libretro core to this branch now.

**Comment by joolswills** [comment]
if you installed it earlier and you reinstall, you will need to delete /opt/retropie/configs/psp and /home/pi/.config//ppsspp or else the symlinks won't get recreated correctly - I make a few symlinks so that homebrew installed from the ppsspp gui will end up in ~/roms/psp

**Comment by HerbFargus** [comment]
here's the build log for lr-ppsspp that failed:

http://pastebin.com/pnczMbF8

**Comment by joolswills** [comment]
as discussed on hangouts - that's due to not having latest version of all files here - lr-ppsspp relies on ppsspp for building ffmpeg, so there is no code duplication. should be fine now you have a full checkout of my branch.

**Comment by joolswills** [comment]
squashed.

**Pull request merged**
