### PR TITLE
Mupen64plus

### PR DESCRIPTION
**Pull request by joolswills**
de-duplicated getBinds

added workaround for 8bitdo controllers that need +11 hack (or -11 in this case)

### CODE REVIEW

**Comment by joolswills** [comment]
@gizmo98 This has had very limited testing - and it's possible when de-duplicating your getBinds function I missed something. If you have any time, it would be good if you could test it - cheers.

**Comment by gizmo98** [comment]
This looks good. I will try to test this this weekend.

**Comment by gizmo98** [comment]
I just tested one controller. Mupen64plus.cfg looks good. In my opinion this can be merged.

**Comment by joolswills** [comment]
Thanks! :)

**Pull request merged**
