### PR TITLE
Allow KDE Neon and Elementary OS Support

### LINKED ISSUE #1786: Enable Support for KDE Neon
KDE Neon is an Ubuntu based OS. Retro Pie will run on Neon but the setup script needs to edited to prevent the 'Unsupported OS' install error.

Edit line 84 of system.sh. Change from:

`Ubuntu|LinuxMint)`

To

`Ubuntu|LinuxMint|neon)`

### PR DESCRIPTION
**Pull request by MrDiamond123**
Fixes #1786 and also is similar to #1751 but with KDE neon. 

I run KDE neon and RetroPie is so fun! So please merge this pull request.

### CODE REVIEW

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/pull/1751

**Comment by MrDiamond123** [comment]
@joolswills i saw that pull request but i also have KDE neon support in mine, I might add more distro's to the pull request if they are Ubuntu /Debian based so they can work with RetroPie too

**Comment by MrDiamond123** [comment]
oh now i see, your adding os compatity 1st got it 

Closed

**Comment by joolswills** [comment]
I need some code so I can match all the various distros up to the parent version they are based off, to handle things like packages that get renamed and so on.

**Pull request closed without merging**
