### PR TITLE
--frames isn't used by retroarch anymore

### PR DESCRIPTION
**Pull request by boarpig**
This error is preventing netplay from working in recent release. --check-frames is new sort of similar(but not the same) option but isn't necessary to be adjusted if it works with default values.

### CODE REVIEW

**Comment by joolswills** [comment]
thanks.

**Comment by joolswills** [comment]
I removed this from the retropie-setup configuration also

**Comment by boarpig** [comment]
Nice, I was so concerned with fixing the bug so I could get back to playing that I forgot other consequences

**Comment by joolswills** [comment]
NP. The configuration tools is one of the older parts of retropie-setup and needs some further updating too.

**Pull request merged**
