### PR TITLE
xpadneo: bump version to v0.9

### PR DESCRIPTION
**Pull request by cmitu**
Update to v0.9

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks, but I think I will prefer to keep it locked at a tag and manually incremented for now.

**Comment by joolswills** [comment]
BTW note that I am planning on removing of wget usage in favour of curl in the future.

**Comment by cmitu** [comment]
Ok, so then just bump the version, v0.9 has some new controller support, plus some bug fixes and rumble improvements.

**Comment by joolswills** [comment]
Thanks!

**Pull request merged**
