### PR TITLE
updated scummvm to 1.8 - use github directly for source, and enable sdl2

### PR DESCRIPTION
**Pull request by joolswills**
The only thing I'm thinking of changing is a few of the parameters which are set when building for the RPI. The savegame timestamps are switched off - this was because the RPI doesn't have a battery backed up clock, but internet connected RPI do have the correct time, so we might want this.

Also the hq scalers are switched off. Sure for performance we don't want them, but some people may want to run in a higher res with a scaler to get a "better image". so It might be worth including them. The event recorder is also switched off, but i dont personally think it will cause any sd card wear to worry about (no more than the system logging etc).

### CODE REVIEW

**Comment by HerbFargus** [comment]
Looks good to me. I can give it a test

**Comment by joolswills** [comment]
you can switch on opengl rendering and it will switch the interface to a higher res and do scaling with bilinear filtering.

**Comment by HerbFargus** [comment]
## Default: 

## OpenGL

## OpenGL (no filtering)

## Myst


## Pajama Sam

**Comment by HerbFargus** [comment]
Works great :)

**Comment by joolswills** [comment]
thanks - looks good - im just building binaries and then I will merge.

**Comment by HerbFargus** [comment]
Perfect. I'll add a mention on the wiki for the rendering options

**Pull request merged**
