### PR TITLE
retroarch: prune unnecessary menu options

### PR DESCRIPTION
**Pull request by psyke83**
common: hide online/core updater menu options
xmb: prune history, music, image & import content menu tabs

### CODE REVIEW

**Comment by psyke83** [comment]
Not sure if this is something you'd consider appropriate, but I think the core/online update menu items are out of place for RetroPie considering that the cores are supposed to be managed via your script. Also, xmb presents a lot of unnecessary menus for those that change from the rgui default.

**Comment by dankcushions** [comment]
I 👍  this. I have seen users getting into trouble or not having the desired effect when attempting to update within RGUI. I didn't realise you could disable them.

**Comment by psyke83** [comment]
What about the xmb menus? Would people miss the image/music tabs? Maybe I'm overlooking an obvious use case (e.g. for playing custom music during games)...

**Comment by Darknior** [comment]
Good idea 👍 
I'm sure some other menu can be removed like in the SAVESTATE menu, you can activate an option to take screenshot of the save, but it doesn't work on PI.

**Pull request merged**
