### PR TITLE
Create lr-ppsspp

### PR DESCRIPTION
**Pull request by gizmo98**
A ppsspp module? Really? At least it compiles and builds a lib! I don't know if it is running. I have no iso's.

### CODE REVIEW

**Comment by joolswills** [comment]
What about ffmpeg etc ? I have a module btw, but it segfaults, so not going to merge anything until we have a working module

eg

```
#!/usr/bin/env bash

# This file is part of RetroPie.
# 
# (c) Copyright 2012-2015  Florian Müller (contact@petrockblock.com)
# 
# See the LICENSE.md file at the top-level directory of this distribution and 
# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
#

rp_module_id="lr-ppsspp"
rp_module_desc="PlayStation Portable emu - PPSSPP port for libretro"
rp_module_menus="4+"
rp_module_flags="!rpi1"

function depends_lr-ppsspp() {
    getDepends gcc-4.8 g++-4.8 libraspberrypi-dev
}

function sources_lr-ppsspp() {
    gitPullOrClone "$md_build" https://github.com/libretro/libretro-ppsspp.git
    git submodule init
    git submodule update
    # fix up library link path for GLES
    sed -i "s|LDFLAGS += -lGLESv2 -lEGL|LDFLAGS += -L/opt/vc/lib|g" libretro/Makefile
    # remove the lines that trigger the ffmpeg build script functions - we will just use the variables from it
    sed -i "/^build_ARMv6$/,$ d" ffmpeg/linux_arm.sh
}

function build_lr-ppsspp() {
    # build ffmpeg
    cd ffmpeg
    local MODULES
    local VIDEO_DECODERS
    local AUDIO_DECODERS
    local VIDEO_ENCODERS
    local AUDIO_ENCODERS
    local DEMUXERS
    local MUXERS
    local PARSERS
    # get the ffmpeg configure variables from the ppsspp ffmpeg distributed script
    source linux_arm.sh
    ./configure \
        --cc=gcc-4.8 \
        --cpu=cortex-a7 \
        --prefix="./linux/$(uname -m)" \
        --extra-cflags="-fasm -Wno-psabi -fno-short-enums -fno-strict-aliasing -finline-limit=300" \
        --disable-shared \
        --enable-static \
        --enable-zlib \
        --enable-pic \
        --disable-everything \
        ${MODULES} \
        ${VIDEO_DECODERS} \
        ${AUDIO_DECODERS} \
        ${VIDEO_ENCODERS} \
        ${AUDIO_ENCODERS} \
        ${DEMUXERS} \
        ${MUXERS} \
        ${PARSERS}
    # disable XVMC as it will be enabled if X headers are available, but we don't want to have to link with X
    sed -i "s/CONFIG_XVMC 1/CONFIG_XVMC 0/g" config.h
    make clean
    make install
    cd ..
    
    # build ppsspp
    make -C libretro clean
    make -C libretro platform=rpi DEBUG=1 CC=gcc-4.8 CXX=g++-4.8
    md_ret_require="$md_build/libretro/ppsspp_libretro.so"
}

function install_lr-ppsspp() {
    md_ret_files=(
        'libretro/ppsspp_libretro.so'
        'assets'
        'flash0'
    )
}

function configure_lr-ppsspp() {
    mkRomDir "psp"
    ensureSystemretroconfig "psp"

    mkUserDir "$biodir/PPSSPP"
    cp -Rv "$md_inst/assets/"* "$biodir/PPSSPP/"
    cp -Rv "$md_inst/flash0" "$biodir/PPSSPP/"

    addSystem 1 "$md_id" "psp" "$md_inst/ppsspp_libretro.so"
}
```

Btw the above needs new changing for recent code - I built with some changes earlier and it still segfaults - experimental is for working stuff with bugs :) thanks but we are not there yet :)

**Comment by joolswills** [comment]
Appreciative of efforts, but there is no point making pull requests for stuff that is untested, or unknown. On the same subject, I want the mupen64 vs mupen64-testing issue sorted - it's also a mess imho - I read that you said better performance is had from the testing module - well, then it needs to be merged. I am not currently comfortable with the unsupported 2 addons with the duplication between them and don't have the background to support them when people are not around etc (eg for most of this year)

**Comment by gizmo98** [comment]
Sorry. I was so excited getting a lib :-)

It should use the prebuild armv7 ffmpeg libs. No reason to rebuild these Libs. Don't wanted to merge it directly. Just wanted to open a ticket for discussion. Sorry, could be done somewhere else.

For the mupen64plus mess. Testing "had" different core and video plugins. Most parts are equal now. Yes. There is no reason to keep testing any longer.

**Comment by gizmo98** [comment]
Do you mean build lib segfaults or retroarch segfaults?

**Comment by joolswills** [comment]
the library. when I last built ppsspp and put it through GDB, it was related to some shader code afair.

**Comment by joolswills** [comment]
If you have it working I am of course interested - perhaps it's just me doing something differently. There is a ticket open regarding adding ppsssp perhaps we should discuss there - and of course we should definitely let each other know what we are working on so we don't duplicate efforts.

**Comment by joolswills** [comment]
OK. Starting again :) Let's keep this open whilst we discuss etc, and come up with a working core (hopefully).

**Comment by joolswills** [comment]
Gives me

**Comment by joolswills** [comment]
Gives me

```
RetroArch [ERROR] :: Error(s): /opt/retropie/libretrocores/lr-ppsspp/ppsspp_libretro.so: undefined symbol: _Z16QuickTexHashNEONPKvj
```

I came across this one previously, and I think I solved it with settings HAVE_NEON=1 in the makefile.

**Comment by joolswills** [comment]
here is my module - I just updated it to work with the latest upstream (probably similar changes to upstream makefile as your fork)

```
#!/bin/bash

# This file is part of The RetroPie Project
# 
# The RetroPie Project is the legal property of its developers, whose names are
# too numerous to list here. Please refer to the COPYRIGHT.md file distributed with this source.
# 
# See the LICENSE.md file at the top-level directory of this distribution and 
# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
#

rp_module_id="lr-ppsspp"
rp_module_desc="PlayStation Portable emu - PPSSPP port for libretro"
rp_module_menus="4+"
rp_module_flags="!rpi1"

function depends_lr-ppsspp() {
    getDepends libraspberrypi-dev
    [[ "$__default_gcc_version" == "4.7" ]] && getDepends gcc-4.8 g++-4.8
}

function sources_lr-ppsspp() {
    gitPullOrClone "$md_build" https://github.com/libretro/libretro-ppsspp.git
    git submodule update --init
    patch -p1 << _\EOF_
--- a/ffmpeg/linux_arm.sh
+++ b/ffmpeg/linux_arm.sh
@@ -119,6 +119,3 @@ make clean
 make install
 }
 
-build_ARMv6
-build_ARMv7
-echo Linux ARM builds finished
--- a/libretro/Makefile
+++ b/libretro/Makefile
@@ -75,17 +75,20 @@ ifneq (,$(findstring unix,$(platform)))
 	LDFLAGS += -lrt -ldl
 
 # Raspberry Pi
-else ifneq (,$(findstring rpi,$(platform)))
+else ifneq (,$(findstring rpi2,$(platform)))
 	TARGET := $(TARGET_NAME)_libretro.so
 	LDFLAGS += -shared -Wl,--version-script=link.T
+	FFMPEGINCFLAGS += -I$(FFMPEGDIR)/linux/$(FFMPEG_ARCH)/include
+	FFMPEGLIBDIR := $(FFMPEGDIR)/linux/$(FFMPEG_ARCH)/lib
+	FFMPEGLDFLAGS += -L$(FFMPEGLIBDIR) -lavformat -lavcodec -lavutil -lswresample -lswscale
 	fpic = -fPIC
 	GLES = 1
 	GL_LIB := -lGLESv2
-	INCFLAGS += -I/opt/vc/include
-	CPUFLAGS += -DARMv5_ONLY 
+	INCFLAGS += -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/
 	PLATFORM_EXT := unix
 	WITH_DYNAREC=arm
-	LDFLAGS += -lrt -ldl
+	LDFLAGS += -lrt -ldl -L/opt/vc/lib
+	HAVE_NEON=1
 
 # i.MX6
 else ifneq (,$(findstring imx6,$(platform)))
_EOF_
}

function build_lr-ppsspp() {
    # build ffmpeg
    cd ffmpeg
    local MODULES
    local VIDEO_DECODERS
    local AUDIO_DECODERS
    local VIDEO_ENCODERS
    local AUDIO_ENCODERS
    local DEMUXERS
    local MUXERS
    local PARSERS
    local OPTS
    if [[ "$__default_gcc_version" == "4.7" ]]; then
        OPTS="--cc=gcc-4.8"
    fi
    # get the ffmpeg configure variables from the ppsspp ffmpeg distributed script
    source linux_arm.sh
    ./configure \
        ${OPTS} \
        --cpu=cortex-a7 \
        --prefix="./linux/$(uname -m)" \
        --extra-cflags="-fasm -Wno-psabi -fno-short-enums -fno-strict-aliasing -finline-limit=300" \
        --disable-shared \
        --enable-static \
        --enable-zlib \
        --enable-pic \
        --disable-everything \
        ${MODULES} \
        ${VIDEO_DECODERS} \
        ${AUDIO_DECODERS} \
        ${VIDEO_ENCODERS} \
        ${AUDIO_ENCODERS} \
        ${DEMUXERS} \
        ${MUXERS} \
        ${PARSERS}
    # disable XVMC as it will be enabled if X headers are available, but we don't want to have to link with X
    sed -i "s/CONFIG_XVMC 1/CONFIG_XVMC 0/g" config.h
    make clean
    make install
    cd ..
    
    # build ppsspp
    make -C libretro clean
    if [[ "$__default_gcc_version" == "4.7" ]]; then
        make -C libretro platform=rpi2 DEBUG=1 CC=gcc-4.8 CXX=g++-4.8
    else
        make -C libretro platform=rpi2 DEBUG=1
    fi
    md_ret_require="$md_build/libretro/ppsspp_libretro.so"
}

function install_lr-ppsspp() {
    md_ret_files=(
        'libretro/ppsspp_libretro.so'
        'assets'
        'flash0'
    )
}

function configure_lr-ppsspp() {
    mkRomDir "psp"
    ensureSystemretroconfig "psp"

    mkUserDir "$biodir/PPSSPP"
    cp -Rv "$md_inst/assets/"* "$biodir/PPSSPP/"
    cp -Rv "$md_inst/flash0" "$biodir/PPSSPP/"

    addSystem 1 "$md_id" "psp" "$md_inst/ppsspp_libretro.so"
}
```

**Comment by gizmo98** [comment]
I have updated my module as well. Runs now.

**Comment by joolswills** [comment]
You don't get a segfault ? video works, but as soon as something else is happening, it segfaults for me.

**Comment by gizmo98** [comment]
Ok. I got video. But after intro video it returns to ES. Do you have a segfault message? My runcommand.log has a list of glError 0x500 listed.

**Comment by joolswills** [comment]
I don't think the glGetError is fatal.
 via GDB

```
pure virtual method called
terminate called without an active exception

Program received signal SIGABRT, Aborted.
```

the backtrace is not useful.

**Comment by joolswills** [comment]
It needs more time spent debugging - I did some more work before - but seem to have not made notes, I believe I found whereabouts it was breaking, and was related to some GPU/shader stuff.

**Comment by gizmo98** [comment]
Strange. It is not possible to save modified core options.

**Comment by gizmo98** [comment]
Jools. Your biosdir variable is wrong.

**Comment by joolswills** [comment]
Thanks yeh fixed - I had the files in place anyway - not that it will help us :)

**Comment by joolswills** [comment]
https://github.com/hrydgard/ppsspp/issues/7479#issuecomment-150843177

May also be the fix for the libretro core. I have PPSSPP working at least now - will clean up my module and test the libretro core. We should also look into why the NEON code is not working etc.

**Comment by joolswills** [comment]
Closing - will create a new pull request when something is working - in the meantime you can check out ppsspp - https://github.com/RetroPie/RetroPie-Setup/pull/1064

**Pull request closed without merging**
