### PR TITLE
Update esthemes.sh

### PR DESCRIPTION
**Pull request by blowfinger77**
I have uploaded a new ES theme called INFINITY

### CODE REVIEW

**Comment by cmitu** [comment]
@blowfinger77 you're supposed to add your theme before the `)`, like this:
```
[... other themes ..]
    'waweedman Spider-Man'
    'blowfinger77 Infinity'
)
...
```

**Comment by blowfinger77** [comment]
Dear Cristi,sorry for that mistake, do I have to do everything again?
________________________________
Van: Cristi Mitrana <notifications@github.com>
Verzonden: zondag 21 oktober 2018 23:33:57
Aan: RetroPie/RetroPie-Setup
CC: blowfinger77; Mention
Onderwerp: Re: [RetroPie/RetroPie-Setup] Update esthemes.sh (#2516)


@blowfinger77<https://github.com/blowfinger77> you're supposed to add your theme before the ), like this:

[... other themes ..]
    'waweedman Spider-Man'
    'blowfinger77 Infinity'
)
...

**Comment by cmitu** [comment]
@blowfinger77 just modify the file to be correct, then amend [1] you last commit in the PR.

[1] https://www.burntfen.com/2015-10-30/how-to-amend-a-commit-on-a-github-pull-request (option 2).

**Comment by blowfinger77** [comment]
I start all over again, I found out that another user used the same name for the theme.

**Pull request closed without merging**
