### PR TITLE
Move Eudora Repos

### PR DESCRIPTION
**Pull request by ChoccyHobNob**
Eudora appears to no longer be maintained by @AmadhiX so I have forked and updated locally

### CODE REVIEW

**Comment by joolswills** [comment]
Why did you close the other one - that was perfectly fine. This is wasting my time.

Also - while I have your attention, I do not appreciate what is happening on your RetroPie facebook page. I joined and soon after left. Your rules are lax, and most posts seem to be about obtaining and using images full of copyrighted software. It seems that only some posts when people directly link are removed - if someone just points someone in the direction of an image that is fine.

This is promoting piracy and is damaging to the RetroPie project.

**Comment by ChoccyHobNob** [comment]
I'm sorry I'm wasting your time, I'm new to git and github and I'm learning as I go. I just learned something new about branches that I didn't know before and I also learned that I _really_ need to stop using the desktop client and start using the command line!

I am sorry you don't like the Facebook group, I noticed that you joined and left shortly after, I went out of my way to avoid calling attention to you while you were there. Our rules are very clear but with few admins actively policing the posts and 16000 users, it's an impossible task to keep it in line. Any links to roms or pre-built images is a ban, selling pre-built systems or linking to sales pages is a ban, but someone has to report it or an admin has to notice it.  We are probably the least piracy promoting retropie group on facebook, the rest of the kodi/retropie type groups are all just blatantly linking to files/images or youtube videos with links to files/images, or writing scripts to install kodi addons or roms automatically. I don't like how much of it goes on in my group but there is only so much that I can do to stop it. Facebook groups don't work like a traditional forum, there are very few admin tools available and no way to get an unfiltered chronological stream of posts and comments.

**Comment by joolswills** [comment]
It would be best to learn git before submitting then closing opening multiple PR. You can practice on your own repository.

Regarding your group - it is clear a blind eye is being turned to it. I don't believe you that you can't moderate it properly - that is nonsense. I saw post after post in my feed which broke/bent your "rules". If it was made more clear that it is not allowed, people would do it less. Because they get away with it they continue.

I you cared you could not allow discussion of the pirate images, but that seems welcome - and not against your rules anyway. If you can't run it properly, perhaps you shouldn't at all.

II care about the future of RetroPie. You obviously don't.

**Comment by ChoccyHobNob** [comment]
Yes, yes it would be better to learn locally before making a fool of myself online, what can I say, I thought what I was doing was simple, I screwed it up and I fixed in in the only way the desktop client would allow. Lesson learned. 

Regarding the group (it's not mine, I'm just one of the admins) There is no blind eye being turned to any illegal activity from my part, I cannot speak for any other member of the team. I'm not there 24 hours a day and when I am I do what I can. If you don't believe that it can't be properly moderated you should create a group of your own and see what tools you have, then you can 'know' rather than just believe. Making it more clear that something isn't allowed and "people would do it less" is patent nonsense and you know it. While they get away with it they continue, when they get spotted they get removed, there isn't any more I can do than that. It's not possible to remove people if I don't see them. Try joining every group with kodi or retropie in the title if you want to get a balanced idea of how the group compares with the rest of them. 

You don't get to tell me what I do and don't care about, you have no idea. If I were to listen to the MAME team I'd think you didn't care about emulation at all and were one step worse than the libretro guys trying to steal glory off the back of real emulator programmers hard work by trying to shoehorn old inaccurate emulators onto inadequate hardware to help people who steal roms, play old games illegally. I'm old enough and wise enough to understand that there is always someone more pious who enjoys taking the high road so they can look down on those beneath them, you are unfairly doing that to me just as they unfairly do it to you. 

Discussing pirate images is not against the law, I always encourage people to use the official script (you did yourselves no favours making an image in the first place, should have stuck to terminal commands) and anyone who has a problem with an image is told to 'do it properly' and get the official build, you do that enough and they just stop mentioning the image they are using, they don't stop using it. 

I did notice that while you were a member of the group, you didn't report a singe post to the admins for breaking the rules. Just like everyone else with a beef, happy to complain about it, unwilling to help sort it out.

**Comment by joolswills** [comment]
If you can't see that open discussion of images full of copyrighted software (which is allowed by your own rules) is damaging then yes - it looks as though you don't care. 

I didn't report stuff since the posts looked clearly allowed. Don't you think I have enough to do.

I assume you are going to continue on anyway. When the project closes down, you can be happy to know you had a part to play in it.

**Comment by joolswills** [comment]
The facebook page admins are also happy with people announcing images there and saying "PM me for a link". So really, there the rules don't mean a lot. Hardly good for the project.

**Comment by ItsNotNitro** [comment]
...

**Pull request closed without merging**
