### PR TITLE
update pcsx2.sh. now crossbuild on ubuntu, amd64

### PR DESCRIPTION
**Pull request by nakatamaho**
I updated pcsx2.sh, and now it builds 32bit binary on Ubuntu, amd64. I tested with tekken4 and worked.

### CODE REVIEW

**Comment by nakatamaho** [comment]
@joolswills

**Comment by joolswills** [comment]
There is another PR for this btw - https://github.com/RetroPie/RetroPie-Setup/pull/2872 - I am leaning towards that one as it has some additional changes (removing the sdl2 check stuff which wouldn't be needed)

**Comment by joolswills** [comment]
What's the purpose of the bios code btw ?

**Comment by nakatamaho** [comment]
> 
> 
> What's the purpose of the bios code btw ?

there are a lot of bioses published for PS2. cf. http://redump.org/datfile/ps2-bios/ it was taken from this list.

**Comment by joolswills** [comment]
I merged the other PR. If you think the bios code is important feel free to open a new PR with details as I wasn't sure why it was needed. Thanks though for the work.

**Pull request closed without merging**
