### PR TITLE
added 320x240 crt themes push-a, push-a-v, 240p-honey, 240p-bubblegum…

### PR DESCRIPTION
**Pull request by arcadeforge**
…, pixel-heaven, pixel-heaven-text

I have added some 320x240 themes made by Asche76, skeletooooor, PietDAmore for use with a 15khz CRT

Have fun

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks. As they are other people's themes I would like to get a go ahead from the authors if that's possible before adding.

**Comment by asche76** [comment]
thanks for add push-a themes. feel free to use ist - best regards

**Comment by skeletoooooor** [comment]
Please go for it! Enjoy

**Comment by PietDAmore** [comment]
Thanks for sharing my theme! The more people can make use of it the better.

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
