### PR TITLE
emulationstation: add experimental parental control edition

### PR DESCRIPTION
**Pull request by gizmo98**
Add enhanced experimental emulationstation-kids modul for beta testers.
http://blog.petrockblock.com/forums/topic/kid-friendly-retropiees-ui-modes-favorites-hiding-items-s-testers-wanted/

Tested: Compiles, builds and runs.

### CODE REVIEW

**Comment by joolswills** [comment]
Although it might be useful for some people to have these features in ES, this needs to be a discussion first. Certainly

a) I do not want to maintain two ES branches, if we add for example required controller configuration changes.
b) we do not want to duplicate module code like this - it needs to be done in a different way if we do include it.
c) it might be better to think about including some stuff in our branch perhaps instead.

**Comment by joolswills** [comment]
If you crated a module that used functions from the main ES module, that would  solve the duplication issue.

**Comment by gizmo98** [comment]
This looks strange. I thought i squashed all commits.

I think this could be merged in the master branch some time in the future. Zigurana stated there are certainly bugs and he needs beta testers. So the easiest way to provide a test possibility for a bigger audience "could be" an experimental module.

**Comment by JustinAiken** [comment]
:+1: do want!!

**Comment by tehfink** [comment]
I too would love this feature

**Comment by joolswills** [comment]
I will include it when I have time (in a way that doesn't duplicate code from the main ES module).

**Comment by joolswills** [comment]
I have created a module for this - it just needs the kids edition to include our changes to the way ES starts/restarts etc.

```diff
diff --git a/scriptmodules/supplementary/emulationstation-kids.sh b/scriptmodules/supplementary/emulationstation-kids.sh
new file mode 100644
index 0000000..aca4eac
--- /dev/null
+++ b/scriptmodules/supplementary/emulationstation-kids.sh
@@ -0,0 +1,38 @@
+#!/usr/bin/env bash
+
+# This file is part of The RetroPie Project
+# 
+# The RetroPie Project is the legal property of its developers, whose names are
+# too numerous to list here. Please refer to the COPYRIGHT.md file distributed with this source.
+# 
+# See the LICENSE.md file at the top-level directory of this distribution and 
+# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
+#
+
+rp_module_id="emulationstation-kids"
+rp_module_desc="EmulationStation with additional UI modes (kids / kiosk)"
+rp_module_menus="2+"
+
+function depends_emulationstation-kids() {
+    depends_emulationstation
+}
+
+function sources_emulationstation-kids() {
+    gitPullOrClone "$md_build" "https://github.com/zigurana/EmulationStation"
+    # make sure libMali.so can be found so we use OpenGL ES
+    if isPlatform "mali"; then
+        sed -i 's|/usr/lib/libMali.so|/usr/lib/arm-linux-gnueabihf/libMali.so|g' CMakeLists.txt
+    fi
+}
+
+function build_emulationstation-kids() {
+    build_emulationstation
+}
+
+function install_emulationstation-kids() {
+    install_emulationstation
+}
+
+function configure_emulationstation-kids() {
+    configure_emulationstation
+}
diff --git a/scriptmodules/supplementary/emulationstation.sh b/scriptmodules/supplementary/emulationstation.sh
index fa4534a..8671777 100644
--- a/scriptmodules/supplementary/emulationstation.sh
+++ b/scriptmodules/supplementary/emulationstation.sh
@@ -72,7 +72,7 @@ function configure_inputconfig_emulationstation() {
     chown $user:$user "$es_config"
     mkdir -p "$md_inst/scripts"
 
-    cp -rv "$scriptdir/scriptmodules/$md_type/$md_id/"* "$md_inst/scripts/"
+    cp -rv "$scriptdir/scriptmodules/$md_type/emulationstation/"* "$md_inst/scripts/"
     chmod +x "$md_inst/scripts/inputconfiguration.sh"
     chown -R $user:$user "$md_inst/scripts"
 }
@@ -111,7 +111,7 @@ _EOF_
     if isPlatform "x11"; then
         mkdir -p /usr/local/share/icons
         mkdir -p /usr/local/share/applications
-        cp "$scriptdir/scriptmodules/$md_type/$md_id/retropie.svg" "/usr/local/share/icons/"
+        cp "$scriptdir/scriptmodules/$md_type/emulationstation/retropie.svg" "/usr/local/share/icons/"
         cat > /usr/local/share/applications/retropie.desktop << _EOF_
 [Desktop Entry]
 Type=Application
```

**Comment by joolswills** [comment]
(Updated diff)

**Comment by joolswills** [comment]
See https://github.com/RetroPie/RetroPie-Setup/pull/1329 which replaces this (uses main ES functions to avoid duplication)

**Pull request closed without merging**
