### PR TITLE
fs-uae integration

### PR DESCRIPTION
**Pull request by verybadsoldier**
This integrates Amiga emulator fs-uae into Retropie.
Multi-disk games are supported but will only use one drive.
Removed fs-uae-launcher since it is IMO not needed anymore after Retropie integration.

### CODE REVIEW

**Comment by joolswills** [comment]
as the default config is small it might be best to just generate it from the module (using iniConfig / iniSet). You also want to avoid overwriting existing configs. See vice.sh as an example

The launch script could do with a few styling tweaks - also use of local vars etc (and not using uppercase vars)

**Comment by joolswills** [comment]
I may hold off merging this as is, as mentioned on the forum I did do some code for uae4arm launching, and I may well combine the functionality / logic (The logic for getting set of disks etc could be shared)

**Comment by verybadsoldier** [comment]
Ok, so I better won't rework this according to your review?

**Comment by joolswills** [comment]
it's worth holding on for now - thanks.

**Comment by vincenzobluesparklabs** [comment]
I found a bug on fs-uae.sh script that prevents the correct installation on Ubuntu (and I guess on Debian as well).
The function depends_fs-uae install the dependencies needed to install the uae packages but the first "case" check is based on "__raspbian_ver" variable instead of "__raspbian_name". The _ver variable value is 8 in case of Ubuntu and 7 in case of Debian but the case statement checks "ubuntu" or "debian"

Hope to be helpful ;)

**Comment by joolswills** [comment]
@vincenzobluesparklabs thanks - fixed.

**Comment by verybadsoldier** [comment]
It just turned out that fs-uae-**launcher** is able to handle multi-disk games inside one zip nicely when passing a zipped game from the command line. So you can store the whole game into one ZIP (I would prefer ZIP anyway) and the launcher will take care to insert the disks into the floppies.
Maybe it should be considered to drop the whole multi-disk logic from Retropie (or better: do not write it :)) and just use fs-uae-launcher. It would make fs-uae integration in Retropie really lean and clean.
The downside would be that multi-disk games would be **only** supported insides ZIPs but I think it is ok.

**Comment by joolswills** [comment]
uae4arm will still require multi-disc logic which could still be useful to be shared with fs-uae for those that keep disks separately.

**Comment by stuaxo** [comment]
Seems like upstream in FS-UAE would might be the best place to patch / feature request for the multi-disk support.

**Comment by verybadsoldier** [comment]
You are right, it would only help fs-uae. Also it turned out that fs-uae-launcher is not part of the normal fs-uae package and would pull in lots of other dependencies... too much overhead just for the ZIP functions in my opinion...

@stuaxo 
Yes I did that and they told me that fs-uae-launcher is already capable of multi-disk ZIPs.

**Comment by verybadsoldier** [comment]
Going to rework this using the ZIP functions...

**Comment by joolswills** [comment]
You don't need to close it - can reuse this PR etc. but np.

**Pull request closed without merging**
