### PR TITLE
Fix 2x build errors, 1x gitPullOrClone bug 

### PR DESCRIPTION
**Pull request by hissingshark**
**1st commit:**
Reicast have restructured their branches.
Presently we pull the default branch which was `master`.  It is now `alpha` (and for a short time was `develop`) and breaks the build with new paths and renaming.
Recommendation [here](https://github.com/reicast/reicast-emulator/issues/1669) is to adopt the `beta` branch until further notice.

---
**2nd commit**
Builds fail on Vero4K/OSMC/Debian at the installation of the python `evdev` dependancy:

> Collecting evdev
>   Downloading https://files.pythonhosted.org/packages/fe/6e/3fa84a43571dec4d00dc26befccc9867b6b3263651531cbc1345f718860f/evdev-1.2.0.tar.gz
> Building wheels for collected packages: evdev
>   Running setup.py bdist_wheel for evdev ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-EavkPG/evdev/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpfnOGqwpip-wheel- --python-tag cp27:
>   usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: -c --help [cmd1 cmd2 ...]
>      or: -c --help-commands
>      or: -c cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   
>   ----------------------------------------
>   Failed building wheel for evdev
>   Running setup.py clean for evdev
> Failed to build evdev

Fixed by installing `wheel` first.
This may be a local package/user configuration issue so I've made the fix platform specific right now.  I doubt it would hurt to apply this generically so I could change that if you think appropriate.

Many Thanks,

### CODE REVIEW

**Comment by cmitu** [comment]
Unfortunately, this doesn't work - again - due to the source tree changes. The `Makefile` moved to `reicast/linux`.

**Comment by hissingshark** [comment]
Oh for crying out loud... Which is back to the original problem... 

Beta should have been ok and I think is meant to be the way to go. Rather than specify Master, which is on the way out, I'll keep pointing to Beta and change the path to match.

**Comment by hissingshark** [comment]
Nope.  `Beta` is still too unstable for building it seems. I hate to think what `alpha` would do.
I think we need to languish at `master` for now then, which at least builds.

Unfortunately it doesn't build in this context, because if you specify `master`, then `gitPullOrClone` ignores it, assuming that it will be the default branch and that gets us `alpha`...  So to build from within RetroPie I need to amend `gitPullOrClone`, although I suspect there was a reason for defining that behaviour?

**Comment by hissingshark** [comment]
I can't see what the benefit of ignoring a branch setting of `master` was, so I've changed it to not be ignored.

**If** we wanted the ability to let the repo offer its "default branch" then we could:
1. remove the initial `[[ -z "$branch" ]] && branch="master"` and add `master` to every gitPullOrClone call in every submodule that didn't specify a branch and the default was confirmed not to be master...
2. Or easier, add a "use default branch" argument!

Anyway, seems I've found a gotcha along the way.  It's fixed, provided I'm not misunderstanding the purpose and most importantly I can confirm Reicast builds again...

**Comment by joolswills** [comment]
The for branch fix seems ok. I think some logic got changed during some other overhauls and this case scenario was lost. I may rework the function myself but I appreciate the heads up. Short on time right now but will get back to you. Thanks.

**Pull request merged**
