### PR TITLE
Delete ARMSNES script as repo no longer exists

### PR DESCRIPTION
**Pull request by RetroPieNerd**

### CODE REVIEW

**Comment by joolswills** [comment]
thanks. Wonder why they removed it. I guess because not much development over the upstream pocketsnes.

After merging, I then found a fork, so I think I will add it back with a fork in RetroPie for now.

**Comment by HerbFargus** [comment]
Probably has something to do with this fiasco: https://t.co/dq8Ji8HVtC

**Comment by joolswills** [comment]
Aah. Removing the repository doesn't really help with that. I appreciate RetroArch are upset about it, but as we have learnt there is little that can be done about these people ripping off others work for profit. A shame though.

**Comment by joolswills** [comment]
Looks Looks like the project got pulled / removed ? good.

**Comment by HerbFargus** [comment]
See also: https://github.com/ekeeke/Genesis-Plus-GX/issues/109 but yeah. Glad they did the right thing. Unlike kickstarter....

**Comment by joolswills** [comment]
Yeah - Nice !

**Pull request merged**
