### PR TITLE
Uninstall

### PR DESCRIPTION
**Pull request by joolswills**
some uninstall functionality

### CODE REVIEW

**Comment by HerbFargus** [comment]
Works great. As the error text in the script mentions symlinks still have to be removed manually but it would seem everything else was uninstalled properly. 

list of symlinks left over:

.advance
.atari800.cfg
.dosbox
.eduke32
.fuserc
.gngeo
.hatari
.reicast
.scummvm
.scummvmrc
.vice

and I think kodi wasn't uninstalled either

**Comment by joolswills** [comment]
Thanks . The symlinks need to be dealt with in each module and I will do that later on. Kodi will need a remove function (as will some other experimental modules)

**Comment by HerbFargus** [comment]
not sure if we want to remove raspi-config though as its part of raspbian

**Comment by joolswills** [comment]
I don't ?

**Comment by joolswills** [comment]
ok it was removing alsa-utils which is a raspi-config dependency. I have changed this now.

**Pull request merged**
