### PR TITLE
wait for 5 frames when hotkey enable is pressed before blocking - wor…

### PR DESCRIPTION
**Pull request by joolswills**
…ks around some issues with sharing a hotkey with a button used in a game. based on https://github.com/recalbox/recalbox-buildroot/pull/72

### CODE REVIEW

**Comment by HerbFargus** [comment]
Looks really good. I'll give it a test

**Comment by HerbFargus** [comment]
Works great on my end. tested with cadillacs and dinosaurs on lr-fba

**Comment by HerbFargus** [comment]
Also tested on super mario world just to make sure that the hotkey blocking still carried over for the second keypress and it does, so very well done.

**Comment by joolswills** [comment]
thanks -  well kudos to the original author - it's a lot simpler than my attempt at a workaround, and seems to work around our problem cases.

**Pull request merged**
