### PR TITLE
Make lr-mame2010 experimental.

### PR DESCRIPTION
**Pull request by dankcushions**
Reflects the wiki: https://github.com/retropie/retropie-setup/wiki/MAME#lr-mame2010-mame-2010

I think it's right to be experimental as this one is missing some crucial features (<2 player, for example)

### CODE REVIEW

**Comment by joolswills** [comment]
It's likely that was written before it moved into optional which I think was done as it takes a long time to build on the rpi (experimental stuff is source only), and yet some people were saying it was useful for some games.

Please can you explain <2 player feature missing ?

**Comment by dankcushions** [comment]
It only supports 2 players. There's a few other issues but that's the big one for me. It's probably easy to fix but there's so many mame cores...

If it's useful for some games (I think some sega games have better sound in this) then that's probably a good enough reason to keep it in 'optional'?

**Comment by joolswills** [comment]
I'm ok leaving it in optional for now at least - despite limitations. Note that the experimental section often reflects the age of the retropie-setup module also (It's not always that the emulator is experimental, but the retropie module is experimental).

**Comment by dankcushions** [comment]
I have updated the wiki :) Sorry for the spam!

**Pull request closed without merging**
