### PR TITLE
Add L'Abbaye Des Morts

### PR DESCRIPTION
**Pull request by RetroPieNerd**
[Here is the website.](https://www.locomalito.com/abbaye_des_morts.php)
[Here is the Google Code archive.](https://code.google.com/archive/p/abbaye-for-linux/)
I had to make the necessary changes to the source code so it will run on RetroPie/Raspberry Pi.
[Here is my repository.](https://github.com/RetroPieNerd/LAbbayeDesMortsRPI)

### CODE REVIEW

**Comment by joolswills** [comment]
Your branch has hardcoded retropie paths which will need changing to use a PREFIX var or something. Your branch lacks the google code commit history which is worth preserving btw. Might just be worth having a RPI branch against the original code with the few changes needed for the RPI (unless I have missed something it looks like just a few makefile tweaks and the removal of HWSURFACE ?)

The module will also need to include dispmanx support (if it works with the dispmanx sdl2).

**Comment by joolswills** [comment]
sdl1.2 even

**Comment by RetroPieNerd** [comment]
Ok I will get that sorted out soon.

**Comment by joolswills** [comment]
Don't open a new PR btw - use this existing one.

**Comment by RetroPieNerd** [comment]
Never mind.

**Pull request closed without merging**
