### PR TITLE
packages - allow adding of 3rd party module repos

### PR DESCRIPTION
**Pull request by joolswills**
3rd party repositories can be checked out to RetroPie-Setup/ext

Repositories should be structured so you have:

ext/REPOSITORY/scriptmodules

Modules are only read from the following subfolders of scriptmodules
 * emulators
 * libretrocores
 * ports
 * supplementary
 * admin

### CODE REVIEW

**Comment by joolswills** [comment]
This replaces #3295 which was broken. Currently testing this but seems ok.

**Comment by joolswills** [comment]
I think I will change this around some more actually. Want it to be clear in the menus if something is a 3rd party repo and maybe display them separately. Sorry for prematurely merging previous commit as I hadn't thought it through completely.

**Comment by joolswills** [comment]
I have worked around the issue by adding a vendor record to the modules. It's also displayed in the setup menus along with the module type which should help with confusion of the ordering which has happened before. But it also makes it clear which are 3rd party modules and is a simpler solution that a whole new menu section set.

From the commit msg:

Used to separate 3rd party packages from RetroPie ones. Added some extra menu items in setup showing
above each type like a heading with

---- VENDOR - TYPE ----

Where:
 * VENDOR is RetroPie or the name of the folder the 3rd party repo is installed in
 * TYPE is the module/package type such as emulator, libretrocore, port etc

Some users have found the ordering of the menus confusing and this should help with that also.

3rd party packages always appear at the end of a section

**Comment by joolswills** [comment]
This is ready for testing if anyone has some time. Thanks.

**Comment by joolswills** [comment]
Added a check to make sure we don't have duplicate `rp_module_id` names when scanning. Skip and display a message if found.

This helps avoiding duplicate IDs but also 3rd party repos should not override our modules but have their own unique names, otherwise debugging issues could be confusing and it could break things if a RetroPie module is replaced by another.

**Comment by joolswills** [comment]
In the case of RetroPie-Extra it has two modules openbor and lr-bsnes that conflict (@zerojay - when this is included it's worth noting you willn eed to adjust your repo but it will make it easier to add your repo without mixing files with ours and making it easier for users to manage).

**Comment by joolswills** [comment]
This does increase module loading time a bit but I don't think it's a big issue as it's on setup/packages initial launch but I had some ideas to improve module scanning in general in the future.

**Comment by joolswills** [comment]
I'm going to merge. Hopefully no issues this time.

**Comment by arnaldovalente** [comment]
How to access to $md_data in ext folder. It point to vendor one

**Comment by joolswills** [comment]
Looks like I have a few issues to fix.

**Comment by joolswills** [comment]
The md_data issue should now be fixed. Thanks for the info.

**Comment by arnaldovalente** [comment]
Tank you for fix it

**Pull request merged**
