### PR TITLE
Create ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by adrianmoisey**
Will this help stopping people from filing support issues?

Details: https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by joolswills** [comment]
A good idea. thanks.

**Comment by adrianmoisey** [comment]
Hopefully it helps, if not, remove it.

**Comment by joolswills** [comment]
I thought it would require the checkbox be checked - but it doesn't - I might add some text to the beginning as with their examples (please make sure the checkbox is checked)

**Comment by joolswills** [comment]
ok works well. thanks (also means people will go to "preview" to check formatting before submitting)

**Comment by adrianmoisey** [comment]
> also means people will go to "preview" to check formatting before submitting

We can only hope :)

**Comment by joolswills** [comment]
either something is wrong with the markup or the github example isn't too useful as I am unable to check the checkbox before submitting an issue.

**Comment by HerbFargus** [comment]
I think you have to manually put in an x?
```
- [x] test
```

**Comment by adrianmoisey** [comment]
What @HerbFargus said, I think it's manual :/

**Comment by joolswills** [comment]
The github example is a bit rubbish then - as it expects people to know markdown. hmm.

**Comment by joolswills** [comment]
it might be easiest to remove the checkbox (since instructing users to put an X in it is not too helpful, especially when the links dont show as links unless you are in preview). Showing the markdown rendered above the issue would be better.

I will just add a line of text in the issue regarding reading the contributors link which is linked above the issue.

**Comment by adrianmoisey** [comment]
> I will just add a line of text in the issue regarding reading the contributors link which is linked above the issue.

That seems like a good compromise

**Comment by joolswills** [comment]
Please make sure you read the "guidelines for contributing" above before opening an issue. This tracker is for bugs and feature requests only.
Support questions should go to the forum. Please remove this text before posting.

**Comment by HerbFargus** [comment]
Sheerly cosmetic but do we want a .github/ folder for the template and contributing or does it not really matter?

**Comment by joolswills** [comment]
I think it's ok - contributing is useful to be seen in the root for devs etc moreso than the template.

**Pull request merged**
