### PR TITLE
autostart - use kodi-standalone for autostarting Kodi instead

### PR DESCRIPTION
**Pull request by diogomsantos**
Check pull #2605 for more info.

### CODE REVIEW

**Comment by hhromic** [comment]
@diogomsantos thanks, but you should provide a more clear commit log, for example:

    autostart - use new binary name for autostarting Kodi

Just amend the commit msg and force-push the new version, do not create a new PR :)

**Comment by diogomsantos** [comment]
No problem ;)

**Comment by hhromic** [comment]
You just updated the PR title, you should update the commit message in git :)

**Comment by diogomsantos** [comment]
The message was already updated.

**Comment by hhromic** [comment]
Mm it is not updated here, maybe you forgot to force push your local change?

**Comment by diogomsantos** [comment]
Nope, it is all good here, idk. Just commit it, it will be fine.

**Comment by hhromic** [comment]
I think you are confusing the PR title (which you changed ok) with the *commit* log message, which is what you pushed in the PR.

You should do `git commit --amend` , change the log message there and then `git push -f`.

If you are using the website only then I dont know how it works there :)

I will leave it to jools to decide. Thanks anyway!

**Comment by joolswills** [comment]
I'll just change it myself.

**Comment by diogomsantos** [comment]
Please do, I won't be able to change it till tomorrow morning. Thanks.

**Pull request closed without merging**
