### PR TITLE
help improvements

### PR DESCRIPTION
**Pull request by joolswills**
* get rid of _INFMSGS and instead have a rp_module_help field with information in.
   this can then be displayed in the setup menus, and not just after configuring.

### CODE REVIEW

**Comment by joolswills** [comment]
@HerbFargus if you want a not very fun documentation job - you could now improve the internal documentation for each module via rp_module_help. Not intended to replace the wiki, but just to give the basics (eg rom locations).

**Comment by joolswills** [comment]
No pressure though - completely optional ;-) Cheers.

**Comment by HerbFargus** [comment]
Sounds fun :)

**Comment by HerbFargus** [comment]
Just so I'm consistent with the docs would a good template be:

```
Copy your <emulator> roms to $romdir/<folder>.  

Copy the <BIOS name> to $biosdir
```

**Comment by joolswills** [comment]
sounds good to me - and then any extra info the users may need. note that only global variables like $romdir are usable in the help variable - not things like $md_id (due to the point at which they are processed).

**Comment by HerbFargus** [comment]
Yeah I figure I'll just hardcode in the rom folder names anyways as they don't match the module Id anyhow. In terms of line breaks do I need to keep them on the same line or can I add \n breaks?

**Comment by joolswills** [comment]
I think \n should work - please check. if you think it would be best split, that's ok too. bear in mind this all has to be maintained, so I think a summary is best, with the rest on the wiki (ie not too verbose).

**Comment by joolswills** [comment]
and thanks! sorry for suggesting the worst jobs for you ;-)

**Comment by HerbFargus** [comment]
Yep I'll just stick with rom paths and bios if applicable. Anything more than that can be referred to the wiki. Thanks

**Pull request merged**
