### PR TITLE
Cygnus

### PR DESCRIPTION
**Pull request by ChoccyHobNob**
Add new theme Cygnus and three variants

### CODE REVIEW

**Comment by joolswills** [comment]
Can't merge as it contains the changes from https://github.com/RetroPie/RetroPie-Setup/pull/1968

**Comment by ChoccyHobNob** [comment]
Doh!

**Comment by joolswills** [comment]
You don't need to close it. Just rebase / amend the commit.

**Comment by ChoccyHobNob** [comment]
I have no idea how... Git beginner

**Pull request closed without merging**
