### PR TITLE
start splash earlier, and wait for fs to be writable for video (requi…

### PR DESCRIPTION
**Pull request by joolswills**
…red by omxplayer), but not for images

### CODE REVIEW

**Comment by joolswills** [comment]
@HerbFargus really sorry, but please could you test this - I start earlier now, wait for fs to be writable for omxplayer. seems to work here. you might want to do inserv -r asplashscreen / insserv asplashscreen

**Comment by HerbFargus** [comment]
Ha ha no worries happy to do it. I'll test it right now.

**Comment by joolswills** [comment]
video shoudl work but start around the same time as before. images should appear a little earlier - before the root disk check as it works when the disk is read-only

**Comment by HerbFargus** [comment]
That's Brilliant! it works great :) now I see 3 out my list of 6 and the video boots a little faster too I think

**Comment by joolswills** [comment]
yay! :D awesome.

**Comment by HerbFargus** [comment]
I'll probably add another option in the menu to automate the randomiser at some point in the future- just for those that want it.

**Comment by joolswills** [comment]
we should move the splashscreen list to config area, and we can have another setting for the randomiser that the startup script looks for.

**Comment by HerbFargus** [comment]
That sounds reasonable

**Comment by joolswills** [comment]
but after 3.0 of course :)

**Comment by HerbFargus** [comment]
of course :P It will be a part of the new menu options

**Pull request merged**
