### PR TITLE
Remove 'eudora-updated'

### PR DESCRIPTION
**Pull request by ChoccyHobNob**
Now all the changes I made for this have been pushed to AmadhiX’s
version, it’s no longer required.

### CODE REVIEW

**Comment by joolswills** [comment]
You have multiple commits here - have just removed myself rather than merging and squashing. You can reuse PRs btw, and you can rebase / squash commits and push back to the same branch without opening a new PR.

**Comment by joolswills** [comment]
While you are here. It has been brought to my attention you are selling stickers with our logo on. I don't remember you asking permission for this. Care to explain?

**Comment by ChoccyHobNob** [comment]
I asked Florian at the beginning of last year

**Comment by ChoccyHobNob** [comment]
Would you like me to remove the logo now?

**Comment by joolswills** [comment]
I will speak to Florian.

**Comment by joolswills** [comment]
You asked Florian and he specifically said you couldn't sell them.

he wrote to you:

> as long as you are not selling these, but are only for your private
> usage in a limited number (how many are we talking about?), it would
> be ok to use the logo. The logo must not be used, e.g., for t-shirts
> that should be sold for any kind of profit / markup.

After the whole facebook piracy nonsense with you, I am disappointed again with your attitude towards our project. You have no respect for the project. Please cease selling artwork that isn't yours.

**Pull request closed without merging**
