### PR TITLE
#2749 fix reicast and RPI4 can do with -j4

### PR DESCRIPTION
**Pull request by rafal-prasal**
reicast for RPI4 needs to be alpha in order to work properly, at least at this time

### CODE REVIEW

**Comment by rafal-prasal** [comment]
Basically makes reicast available for RPI4

https://github.com/RetroPie/RetroPie-Setup/issues/2749

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/pull/2857

I'd prefer to wait for this. But thanks. We won't switch to -j4 globally for rpi4.

**Comment by rafal-prasal** [comment]
it is your choice of course, 

in the meantime I would merge that and then replace when #2857 becomes available.

**Comment by joolswills** [comment]
That would just make extra work. Sorry but I'd prefer to use the other PR. I'm in no rush.

**Comment by psyke83** [comment]
Just to clarify some issues re: reicast and RPI4.

If this PR worked successfully for you, it's possible that you might be running an improperly configured RetroPie installation that runs in an Xorg context, which is not going to be the supported configuration for the upcoming release.

The current reicast `alpha` branch (as well as `beta` and `stable`) are not capable of building with SDL2 support for any targets, so they won't be able to run on RPI4 unless you prefix the emulator command with `xinit` (which you didn't do in your PR) or if you already run emulationstation within an Xorg session (which as I said, is not how the upcoming release will work).

Although my PR is working, I'm also not happy with the state of my PR due to the fact that the master branch seems to run very slowly, and keyboard inputs are leaking into the background terminal. We could switch to newer branches and run in xinit, but that will break the`+Start reicast.sh` launcher (as runcommand doesn't know to pass the xinit supplementary arguments to these shell scripts).

It seems that upstream is in the process of refactoring the code related to SDL2 (and have also broken RPI3 and earlier builds). It may be a good idea to hold off on merging anything until those branches have settled and SDL2 support works again (which means that we can run without Xorg). Fortunately, it seems that `lr-flycast` is in a pretty good state and runs faster than the standalone `master` branch.

**Pull request closed without merging**
