### PR TITLE
Added performance fix for RPI darkplaces quake

### PR DESCRIPTION
**Pull request by madmodder123**
Without "gl_nopartialtextureupdates 1" the Raspberry Pi version of darkplaces-quake runs at ~5 FPS, with it enabled you can get 30fps without issue

### CODE REVIEW

**Comment by cmitu** [comment]
Your `.sh` file has DOS line-endings, making the `.diff` to the previous module version basically 100%. You should correct that first.

**Comment by madmodder123** [comment]
Fixed it :)

**Comment by joolswills** [comment]
Formatting is still wrong - I will look into this as I didn't need this change when I last run this on the rpi4.

**Comment by joolswills** [comment]
Unable to reproduce the issue on my set up. I have 30+ FPS without this option (@ Adding it made no difference. I'm going to close, but feel free to provide more info.about your config. Maybe it's another configuration related to your set up (you're not running from the desktop environment right?)

**Comment by joolswills** [comment]
Sorry I had made an assumption that this was a rpi4 issue. But I just reread, and you don't specify. I'll re-open and test on rpi2/3

Details of your set up would be useful btw.

If it's needed for rpi1/2/3 videocore drivers, i will add it, but not via this PR as currently your code will add the line again and again. Also it.may he better to use the config.cfg and via our iniSet functions.

**Comment by madmodder123** [comment]
Ah yeah I forgot my details:
Raspberry Pi 4 2gb
Retropie 4.6

When you load up the game the demo works fine, but when  you start a new game it goes to 5FPS without that option toggled.

**Comment by joolswills** [comment]
Can't reproduce it - this is better dealt with on the forum first.

**Comment by joolswills** [comment]
Ok I can reproduce the issue with the new information provided. Will implement the workaround or another fix.

**Comment by madmodder123** [comment]
I also wanna add that the reason I put the option in "autoconfig.cfg" and not "config.cfg" is that if you put it in the latter, it will be erased if you set everything to default.

**Comment by joolswills** [comment]
Thanks.

**Comment by joolswills** [comment]
Please see #3179

**Pull request closed without merging**
