### PR TITLE
Add GLupen64 N64 libretro core

### PR DESCRIPTION
**Pull request by gizmo98**
Optional module for now. Better alternative for lr-mupen64plus.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks! :)

**Comment by gizmo98** [comment]
@joolswills 
Thanks! 👍 

@loganmc10
There is a module now!

**Comment by loganmc10** [comment]
@gizmo98 have you tested it? How does it work for you? I would love some more people to test it

**Comment by gizmo98** [comment]
I have tested it. F-Zero, Mario games, Goldeneye, Perfect Dark and other games run fine. Speed is much better compared to mupen64plus-libretro. The only game i had a serious problem was Yoshis Story. My PI seemed to hang up.

**Comment by loganmc10** [comment]
When the module is built do you guys use "platform=rpi" or "platform=rpi2/3"?

**Comment by joolswills** [comment]
looking at the module it uses platform=rpi1 or platform=rpi2  / rpi3

**Comment by loganmc10** [comment]
OK good then it will pull in the correct cflags

**Comment by loganmc10** [comment]
Just FYI I've got Framebuffer Emulation working with this core, so it should be pretty much at feature parity with mupen64plus+GLideN64

**Comment by joolswills** [comment]
thanks! :)

**Pull request merged**
