### PR TITLE
Update pcsx2.sh

### PR DESCRIPTION
**Pull request by angrystar170**
Add dependency package "libportaudio2:i386" and "libsdl2-2.0-0:i386"

### CODE REVIEW

**Comment by cmitu** [comment]
Aren't those packages pulled automatically - as dependencies - by installing the `pcsx2` package ?

**Comment by angrystar170** [comment]
Yes. 

For reference, I am using Debian-based Linux (MX-19).

**Comment by cmitu** [comment]
If those packages are already installed as dependencies, what's the point of installing them separately ?
Also, the `i386` architecture is added separately in the as part of the `depends` function, it doesn't need to be added again.

**Comment by angrystar170** [comment]
I manually installed "libportaudio2:i386" and "libsdl2-2.0-0:i386" using the apt command.

**Comment by cmitu** [comment]
> This is because the retropie installation script cannot automatically import dependency packages.

This is not the job of the installation script (to import dependency packages), but something that should be handled by `apt`. If the `pcsx2` package doesn't list the necessary dependencies, then there is a problem with the DEB package, not an problem of the install script.

**Comment by joolswills** [comment]
Thanks. But closing based on comments etc.

**Pull request closed without merging**
