### PR TITLE
Add support of Orange Pi Zero 2+ (H5) 

### PR DESCRIPTION
**Pull request by shim80**
Hi.
Can you add support of retropie to Orange Pi Zero Plus 2 (H5 version)?

### CODE REVIEW

**Comment by joolswills** [comment]
Not via this PR I'm afraid. I don't have the hardware either.

**Comment by joolswills** [comment]
(there are conflicts and lots of changes that are not suitable for our repository).

**Comment by robertybob** [comment]
@shim80 Are there any advantages of using the OrangePi at the moment? ..are the emulators even optimised to make good use of the 4 cores? @joolswills Would you accept a donation of the hardware?

**Comment by shim80** [comment]
@robertybob , I'd talked about the model Orange Pi Zero 2+ H5 version.
Avantages? Yes: Price (<20$), power (4 cores 64bit and GPU mali 450) and size (4,8cm x 4,6cm. Good for portable gaming).

**Pull request closed without merging**
