### PR TITLE
pegasus-fe: Added Raspberry Pi 3 release

### PR DESCRIPTION
**Pull request by mmatyas**
There is now a Raspberry Pi 3-optimized build of Pegasus, which might provide improved performance.

### CODE REVIEW

**Comment by joolswills** [comment]
This could be simplified by using something like.. if isPlatform "rpi" then platform="$__platform" or similar. On phone so untested.

**Comment by mmatyas** [comment]
I see, but is that alright? `$__platform` seems kind of an internal variable to me; is it guaranteed that its value will match rpi1/2/3 (ie. it's not a field in `$__platform_flags` or somewhere else instead)?

**Comment by hhromic** [comment]
@mmatyas on RPI devices, `$__platform` is guaranteed to be one of `rpi1`, `rpi2` or `rpi3`:
https://github.com/RetroPie/RetroPie-Setup/blob/a571418bbd19b74f05eedf162d8303dfdabebbb6/scriptmodules/system.sh#L221-L246

**Comment by joolswills** [comment]
It's fine to use that variable as @hhromic says above. Thanks.

**Comment by mmatyas** [comment]
All right then, I've just pushed an update with this change.

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
