### PR TITLE
remove delay from omxplayer start and fix up depdencies

### PR DESCRIPTION
**Pull request by joolswills**
@HerbFargus please try this - please run the script again, so it updates it, and then do enable.

This is the last thing to sort before the release...

### CODE REVIEW

**Comment by joolswills** [comment]
The other thing is currently there is a 12 second delay before another image is shown - and now that only a single image is passed to the script at a time, the slideshow functionality with timeout doesn't work correctly, so the previous patches have sort of broken multiple image functionality..

**Comment by joolswills** [comment]
im inclined to change it so it can have a single movie or multiple images.. My bad for not thoroughly checking the patchset.

**Comment by HerbFargus** [comment]
yeah I can do that, I'm just finishing up squashing some commits for my most recent pull request (to add art to videopac and sg-1000) and then I'll give this a go

**Comment by HerbFargus** [comment]
seems to be working fine on my rpi2

**Comment by joolswills** [comment]
I have made some further changes - Would you mind trying it again with the new code. Works here. I have changed Required-Start - I think it starts slightly earlier now. It should work with multiple images (displayed for 5 seconds each), and for a single image it will be shown for 25 seconds (5 seconds + 20 for last image).

**Comment by HerbFargus** [comment]
it froze on me- might have a corrupted sd card. multiple splashscreens worked, I'm just testing out the video splash now

**Comment by HerbFargus** [comment]
I can't seem to get the video splashscreen to boot.

**Comment by joolswills** [comment]
Looks like the Required-Start change isn't working after all - nothing is output because I was redirecting errors. Reverted - it wasn't working here either so no idea how it was before - I am pretty tired though.

**Comment by joolswills** [comment]
Would you mind giving it another go - sorry.

**Comment by HerbFargus** [comment]
yep testing it right now

**Comment by joolswills** [comment]
There are still problems I'm afraid - I am trying to end fbi processes if there are more to display, and then wait for the last one for longer. However, it seems to sometimes leave the system in a bad state and if emulationstation is not running, you can see the shell prompt. Thinking about another workaround.

**Comment by HerbFargus** [comment]
yeah... with the revert the video splash is working now at least.

**Comment by HerbFargus** [comment]
I'm testing multiple images right now.

**Comment by HerbFargus** [comment]
multiple images work too.

**Comment by HerbFargus** [comment]
when I enable custom splashscreens and then go to choose a video it sometimes freezes on me... I wonder if its my pi or if it has something to do with the processes of splashscreen.sh

**Comment by joolswills** [comment]
when you say crashed - is anything displayed ? can you ssh in ? it might just be the framebuffer left in a certain state - also please clarify on what you mean by "choose a video" ?

**Comment by HerbFargus** [comment]
the dialog menu just freezes- so I can't do anything. I choose enable custom splashscreen and then when am going through the list to choose my video splashscreen it just freezes randomly.

**Comment by joolswills** [comment]
it may be related to the parsing/creation of the list - put set -x in the script and you will see the output if its in an infinite loop.

**Comment by HerbFargus** [comment]
actually scratch that- its happening in any of my menus. would this be a sign of a corrupted sd card? or would it have something to do with the splashscreen stuff?

**Comment by joolswills** [comment]
no idea - check the output of dmesg etc.

**Comment by joolswills** [comment]
you could disable the splashscreen stuff and see if it makes a difference.

**Comment by HerbFargus** [comment]
yeah once disabled it works find so it has something to do with the asplashscreen code

**Comment by joolswills** [comment]
I have some new code almost ready - i believe fbi was not exiting cleanly in the way I was trying to manage it before.

**Comment by joolswills** [comment]
ok. I give up trying to make it clever for now. Back to old behaviour, with the video support, so you can have a single video or you can have a few pics. the delay between the pics is set to 20, but i should probably make it 20/number of pics, so more pics, the quicker they are displayed etc.

**Comment by joolswills** [comment]
couple more fixes coming.

**Comment by joolswills** [comment]
ok. really hope it's ok now. functionality is much the same as before, but the timing is better - the splash is shown for 20 second for an image, but if two images, 10 seconds each - but using the slideshow mode as before.

if the first line is a video, only the video is shown. we do not process each line by line and send to FBI as it is problematic.

**Comment by HerbFargus** [comment]
ok, testing with a video now

**Comment by joolswills** [comment]
Thanks.

**Comment by HerbFargus** [comment]
video works. now testing with multiple images

**Comment by HerbFargus** [comment]
my rpi2 boots too fast to see any more than one image if I only have two images on the list- but it isn't a big deal, as I'll only ever use one image or one video. I'll throw on a bunch of images just for kicks though and see what it does

**Comment by joolswills** [comment]
yeh emulationstation shows up in front - if you disable that you get to see more. on a pi1 it can take up to 20 seconds. ideally we would have it so its shown, then killed when the machine is finished, but fbi doesn't like being "killed". Anyway, I don't consider the splash important and would rather work on other things, so I will not revisit this anytime soon I hope. Time to build images again.. about the 6th time today :)

**Comment by joolswills** [comment]
thanks for the help.

**Comment by HerbFargus** [comment]
with 6 on the list it shows two before emulationstation boots so the rpi 2 would just have to have a huge list, but its all good- its more for people with an Rpi 1 anyhow. All that's left is to add a randomiser :P but we can look into that another time. Thanks for giving up your sleep to help get this to work. I appreciate it. 

it's about time 3.0 is finally released :)

**Comment by joolswills** [comment]
Those that want it random can put

```
sudo shuf /etc/splashscreen.list -o /etc/splashscreen.list
``` 

into /etc/rc.local - and be done with it :)

**Comment by HerbFargus** [comment]
ha ha fair enough. thanks for the tip

**Pull request merged**
