### PR TITLE
WIP: amiberry: add support for whdload auto-load

### LINKED ISSUE #2327: Amiga LHA File Support
Apologies in advnace that I am having a bit of a blonde moment in trying to add this code myself, and failing miserably at finding the right places to make the changes, so i will have to revent to making a request...

Amiberry’s development branch has just had a new file support added, LHA. This is commonly used as a single file solution to packaged WHDLoad games, as this format is able to accommodate certain constraints of the Amiga filesystem within a contained archive. (Eg. Issues with certain filenames etc)

The support is fairly simple. Just by adding `-autowhdload=gamefile.lha` on the command line.

For RetroPie to fully take advantage of this (and it was designed with RetroPie in mind) I’d like to suggest that the `es_systems.cfg` has .lha as a supported Amiga filetype and that the following be added to the Amiberry launch script on line 13 (right after the .uae file support)

```
[elif [[ "$rom" == *.lha ]]; then
"$emulator" -autowhdload="$rom" -G]) 
```

Details on how the system is able to have game-specific settings, without using individual Config files, is provided on the Amiberry Wiki Page , and you can expect a large number of game-specifics to be added very soon.

I appreciate that the devs here might want to wait until this change reaches the master branch, but I anticipate that will be quite soon anyway.

Thanks!

### PR DESCRIPTION
**Pull request by psyke83**
Recommend to delay merging until the master branch has been updated.

Fixes #2327.

### CODE REVIEW

**Comment by HoraceAndTheSpider** [comment]
Hi psyke83

You’ve probably seen already,  but just to let you know the LHA file support and booter has been pushed to Amiberry’s master branch (v2.18) today :)

**Comment by HoraceAndTheSpider** [comment]
hi psyke83 - there is no reason the .zip file wouldnt be supported from command line for other distros, but appreciate that there is a limitation on processing of ZIPs on the Amiberry script, so that will just need reflecting the the RetroPie pages.

The DOS screen suggests that whdboot\boot-data  is not being correctly mounted?

I will try manually updating a fresh install with your changes, and see what needs to happen to make it work....

**Comment by HoraceAndTheSpider** [comment]
Hi again,

The good news is, i was able to reproduce this problem, using a fresh RetroPie install, your updates here, and installing from source. 

Rectified with a simple permission reset for `sudo chown -hR pi:pi /opt/retropie/emulators/amiberry/whdboot` which i assume can be done with the install script?

**Comment by HoraceAndTheSpider** [comment]
An unrelated (bur revealed by checking this) bug is that two folders are misisng from the master branch (skipped because they would be empty by default)

I will get this fixed asap....
```
boot-data/WHDBooter/Autoboots
boot-data/WHDBooter/Debugs
boot-data/WHDBooter/Savegames
```

**Comment by joolswills** [comment]
Don't want to chown that folder - the area should not need to be writeable and would like to avoid it if possible. If it needs to create a temp file or something we should either put it somewhere else, via a symlink (if possible), or another method.

**Comment by HoraceAndTheSpider** [comment]
Makes sense.
I would suggest then simply having the RP script relocate  the whole `whdboot` folder (rather than just the xml file) to be in `configs` in the same way as the `conf` Folder is.

**Comment by joolswills** [comment]
Yes. move ConfigDir - https://retropie.org.uk/api/helpers_8sh.html#aaafeb636990e5b88398fafd9856ef211

**Comment by HoraceAndTheSpider** [comment]
Perfect. Should be an easy fix then :)

Psyke83 will probably beat me to it, but if not I’ll give it a try tomorrow.

**Comment by psyke83** [comment]
Using moveConfigDir (like below) would still necessitate changing permissions on the folder, otherwise no user modifications would be possible. Additionally, this is going to expose executables via ```boot-data/WHDBooter``` - not sure if that's a good idea.

```
diff --git a/scriptmodules/emulators/amiberry.sh b/scriptmodules/emulators/amiberry.sh
index 07f7f96d..7b6f71ef 100644
--- a/scriptmodules/emulators/amiberry.sh
+++ b/scriptmodules/emulators/amiberry.sh
@@ -73,6 +73,7 @@ function configure_amiberry() {
     moveConfigFile "$md_inst/conf/retroarch.cfg" "$configdir/all/retroarch.cfg"

     # whdload auto-booter user configuration
+    moveConfigDir "$md_inst/whdboot" "$md_conf_root/amiga/$md_id/conf/whdboot"
     moveConfigFile "$md_inst/whdboot/hostprefs.conf" "$md_conf_root/amiga/$md_id/conf/hostprefs.conf"
     chown $user:$user "$md_conf_root/amiga/$md_id/conf/hostprefs.conf"
 }
```

**Comment by joolswills** [comment]
@psyke83 As discussed on hangouts (putting here for reference), permissions can be changed fine if it's symlinked. I just don't want user saved/changed files stored in the `md_inst` folder. But perhaps as you mentioned we should just symlink the game data folder.

@HoraceAndTheSpider When looking over this I saw https://github.com/midwan/amiberry/tree/master/whdboot/boot-data - where are these files from ?

**Comment by HoraceAndTheSpider** [comment]
I would have taken them from my original AMOS setup, as it’s an AMOS coded booter, or other items like the joystick tester have come from Aminet.

If there are concerns over any standard commands then i would reproduce then using AMOS executables to do the same, but I don’t think it should be necessary hopefully.

**Comment by HoraceAndTheSpider** [comment]
@psyke83

I think the WHDBooter probably does want to “exposed” anyway - firstly people may want to copy their saves to another machine and these are contained here. Also I may pre-package a large number of austobooter files at some stage, which would speed up loading.

Lastly, most users for this feature have been using an older version of this anyway which has previously been in the roms/Amiga folder, and some may want to simply manually update the booter of changes are made.

**Comment by joolswills** [comment]
@HoraceAndTheSpider The workbench commandline tools and amiga system librarys are not re-distributable. They are copyrighted - they cannot be included with RetroPie.

**Comment by HoraceAndTheSpider** [comment]
For absolute clarity I have just created a version with 100% AROS equivalents, for all Command line and Library files which i will test tonight and merge in if working.

**Comment by HoraceAndTheSpider** [comment]
All sorted with no issues, and will be pushed straight to the master branch, I hope this eases any concerns.

I had hoped to try out a solution for the script myself tonight now I understand it from this conversation but sadly did not get the chance. 

I think at least the 3 folders which were/are empty would need to be moved with user permissions.

**Comment by HoraceAndTheSpider** [comment]
I've done a bit of testing with this, and I think it is best (and more workable) to simply relocate and symlink the whole whdboot folder. There are planned changes for such things as downloading an updated XML file, and this probably gives the most flexibility to allow for booter updates, moving of savefiles etc, without ever needing to revisit this section again.


so my proposed change is:

```
    # whdload auto-booter user configuration
    moveConfigDir "$md_inst/whdboot" "$md_conf_root/amiga/$md_id/whdboot"
    chown $user:$user -hR "$md_conf_root/amiga/$md_id/conf/whdbooter"
```

I have tested this as follows;

+ Installed a fresh RetroPie SD Card
+ updated RP scripts
+ manually added the RP script changes from here, including my lines above.
+ Installed Amiberry from Source (which takes in the the updated whdbooter inc. AROS)
+ Added kickstarts to `BIOS/` and LHA files to `/roms/amiga`
+ Launched LHA files from ES and all working. 

This way seems to work 'out of the box' as best as possible, which is obviously the long term plan here.

Hope this is acceptable

**Comment by Shawson** [comment]
Following the procedure above, worked for me also!

**Comment by HoraceAndTheSpider** [comment]
@psyke83 @joolswills 

Any further thoughts on this? Is this all OK with the proposed changes i made above? If needed I can create a fresh pull request now I know where I am looking. 

I have an anxious Facebook group waiting to take advantage of this feature and I would like to try and close the matter out! 

I am sure  there is probably still a separate piece of work to do re: the Amiberry binary updater, but hopefully that is all covered separately.

Thanks

**Comment by joolswills** [comment]
There is a problem actually, with packaging of this and usingMoveConfigDir.

It will need to be implemented differently, moving the folder name before packaging, and then doing a "copyDefaultConfig" function for any user configurable configs there (Assuming some of the shipped xml configs are meant to be editable - if not it may be a bit simpler).

Which folders definitely require to be writable. The AROS executables dont for example do they ? It may be best as @psyke83 mentioned to not copy them.

**Comment by HoraceAndTheSpider** [comment]
Can you explain a bit more about what needs to differ? I am happy to help implement it, but have the above already working, so I guess I’m just a little confused on what I’d need to do to help: I did test scenarios such as having saves / user modified settings etc and the. Re-updating Amiberry (from source) from wishin Retropie script, and it performed in the intended way. Is the problem because of the option to update from binary?

Although not at the moment, all of whdboot has the potential to need to be writable I’m afraid, as both the game-data (custom setups) and boot-data (AMOS and AROS commands) are likely to become updateable from within Amiberry, and I’d like to avoid having to give anybody more work to make changes when that is implemented,

**Comment by joolswills** [comment]
When we distribute a binary package we archive up the install folder. In this case it will be a symlink so none of the files that get moved will be included. If you can tell me exactly which folders need to be writeable I can come up with a solution.

Ideally I would like so we have static unchanged files in /opt/retropie/emulators/amiberry with symlinks to the configs area for stuff that needs to be writeable. if they need to contain default configs, they will need to be copied, but they will need to be included as a different name - eg "example.config.dist" so they are included in the binary package, and we then copy them to the correct names in the configs area.

**Comment by joolswills** [comment]
if you could separate writeable areas from the distributed files, it would make it easier - then they would be easily upgradable. If you can give me a detailed breakdown of the existing structure it would help - I have a lot of things on, and it would save me some time (and what needs to be writable currently)

**Comment by joolswills** [comment]
looking at the current structure

```
boot-data - does this need to be writeable ?
game-data - this contains a single xml - is this customisable by the user or do they just add more files here ?
hostprefs.conf is this user editable ? How should updates be handled ?
```

**Comment by HoraceAndTheSpider** [comment]
Hi @joolswills 

No problem to explain further... appreciate your help.

What i will do, is in the next version, do as i said and package the booter into something more manageable as a single file. Which i understand much more the benefit of now i think. This will result in that separation of writable files. It's not something that i can do without a change to Amiberry itself though, so it will take a little while, but if lucky i can do something this weekend!

Basically `boot-data` is mounted as a writable `DH0:` folder at present, so preferably it should all be writable, but i can see why it would be beneficial to understand the 'essential' writable areas. I save all the debug, boot, and savegame stuff in here also. This has everything it needs to mount and load the LHA game data which is placed in `DH1:`

In the future what i''ll do I think is have a ZIP or HDF read-only file mounted to `DH0:` and the saves stuff to folders in `DH2:` (so that this is one of the bits that would be in the RP Configs section)

The `game-data` has a single XML which we will be producing from an online database, and we'll have a download button in the next major version release. You can also place single-game preferences here also, which follow the same format but are labelled `.whd` (they are basically very simplified `.uae` files.  So again, `game-data` is definately an area for the RP Configs.



For now, the In normal circumstance, the following would applied.... 

(folders) 
`boot-data/C/`  - non-writable
`boot-data/Devs/` - non-writable *
`boot-data/Libs/` - non-writable
`boot-data/S/` - non-writable
`boot-data/WHDBooter/Autoboots/` - essential writable
`boot-data/WHDBooter/Debugs/`  - essential writable
`boot-data/WHDBooter/Savegames/` - essential writable
`boot-data/WHDBooter/Splash/` - non-writable but contents updateable from RP
`boot-data/WHDBooter/WSConfigs/` - writable

(files)
`boot-data/WHDBooter/Find_AutoStartup`   - non-writable but updateable from RP
`boot-data/WHDBooter/GameBootLoader`  -non-writable but updateable from RP
`boot-data/WHDBooter/SplashScreen`  - non-writable but updateable from RP


`game-data/`  - writable (user may place who config files in here)
`game-data/whdload_db.xml` - essential writable  (User will be able to download update of this file from Amiberry, but also should be updated with Amiberry)

`game-data/hostprefs.conf ` - essential writable (sets global options, and ideally should never be updated by RP, although the default is OK... a bit like `adfdir.conf` )


* although, argh! removing system-configuration is good for debugging.. i will worry about that myself!

**Comment by HoraceAndTheSpider** [comment]
Sh*t. I have just realised why i cannot have Devs being non-writable... the damn kickstart files that i set up symlinks for (certain WHDLoad games need this for compatibility)

I will see if i can make an option that creates a second DEVS folder in the saves 'drive' for this, and uses Assign ADD

**Comment by HoraceAndTheSpider** [comment]
@joolswills  I have had a play around and hopefully have a scenario that works better for RP integration.

The file/folder breakdown is like this: (all paths 'relative' to Amiberry)

`whdboot/boot-data.zip`  - single file solution for all the AMOS / AROS bits. It would be nice if this was writable for the purpose of updating within Amiberry. Should be overwritten during any RP package downloads though.

`whdboot/game-data/whdload_db.xml` - as above, single file solution for game-specific settings. Again, would be useful if writable for updating.

`whdboot/save-data/Autoboots`
`whdboot/save-data/Debugs`
`whdboot/save-data/Kickstarts`
`whdboot/save-data/Savegames`

All writable folders, but also all empty by default. (Kickstarts will be filled with Symlinks if the user has the right file available). There should be no problem if you need to create this 'new' in the installation process (if they dont exist) and would be best places in `configs/amiga/amiberry/whdboot/save-data/`

Hopefully this makes things easier for implementation?  I will push this to an Amiberry update as i think it's quite a nice solution anyway, and see about having it in the master branch ASAP

**Comment by HoraceAndTheSpider** [comment]
And with today’s master branch update, it is done.

Let me know if there is any extra information you need @joolswills @psyke83

**Comment by joolswills** [comment]
(Actually will wait for @psyke83 as it's his PR :-) )

**Comment by Shawson** [comment]
I've got a fresh install of Retropie raring to go to test out the release version of the script with new Amiberry stuff as soon as it's merged! :)

**Comment by joolswills** [comment]
apologies for the delay - have been busy. This is next on my list.

**Comment by Shawson** [comment]
@HoraceAndTheSpider Does all the rejigging of folder locations above affect where users have to dump the kickstarts & lha files?

**Comment by joolswills** [comment]
>All writable folders, but also all empty by default. (Kickstarts folder will be filled with Symlinks if the user has the right files available in the bios folder). There should be no problem if you need to create these folders as 'new' in the installation process (if they dont exist) and would be best places in configs/amiga/amiberry/whdboot/save-data/ - like the conf/ folder they should be left alone if they are already there and have contents/

amiberry automatically creates the symlinks here or do you need RetroPie to as we do with the `/opt/retropie/emulators/amiberry/kickstarts` folder (we just symlink it directly to the retroarch BIOS folder)

**Comment by joolswills** [comment]
Also should `hostprefs.conf` be overwritten on upgrade, or is it changed one a user changes around configs etc ? (eg should it be considered a one time default config?)

**Comment by HoraceAndTheSpider** [comment]
@joolswills 
> will amiberry automatically create the symlinks here or do you need RetroPie to 

No, Amiberry does all this itself - so it just needs the new `save-data/Kickstarts` folder to be there, which it can perform an internal (Amiga) assign on so they are picked up inside the emulator environment. The first time you use the booter, Amiberry will then symlink them from whatever kickstarts folder is specified in the 'paths' panel. (So, as you say, they will be picked up by default from the `\bios\` location)  

I figured this was best for me to automate internally because that way it uses the Amiberry validation of Rom files to make sure it only links the appropriate revisions.


> Also should hostprefs.conf be overwritten on upgrade,

Nope, exactly as you have said, it's a one time default (practically an 'example' really) - although it's possible some options could be added, they will be documented on the WIKI and mentioned in any changelogs.

@Shawson 
> Does all the rejigging of folder locations above affect where users have to dump the kickstarts & lha files?

No, the kickstarts can be wherever you point them to in the 'paths' panel. Default being the BIOS folder.

The LHA files should be in `/roms/amiga` following the changes being implemented here.

**Comment by joolswills** [comment]
Please can you try https://github.com/RetroPie/RetroPie-Setup/pull/2352 - will close this PR.

**Pull request closed without merging**
