### PR TITLE
Update dolphin.sh to include other settings

### PR DESCRIPTION
**Pull request by retropieuser**
Adds a symlink to .local/share/dolphin-emu into /opt/configs/gc. The local share directory includes items like the memory card data, game specific configs, Wii Nand, Save states etc which users may want easier access to

### CODE REVIEW

**Comment by cmitu** [comment]
I think `$HOME/.local/share/dolphin-emu` should be moved under `gc/dolphin-emu/Local`, just like the configuration is under `gc/dolphin-emu/Config`.
Is the 2nd change related or is just a correction ?

**Comment by retropieuser** [comment]
The second change would line the configs all under a dolphin-emu folder inside GC, it's strange, dolphin on linux, it separates out the config folder into it's own location .config/dolphin-emu and leaves the rest of the settings under .local/share. But on Mac I'm looking at it right now and the folders are all under one dolphin-emu:-

Screenshot 2024-06-21 at 12 37 49

**Comment by cmitu** [comment]
@retropieuser that's fine, but it doesn't answer or address my questions.

**Comment by retropieuser** [comment]
It's comestic tbf that's the bit I was driving at above as you end up with a local directory and a config directory when imo it's tidier in one directory inside configs/gc. Anyway I've made the adjustment to only symlink the local directory

**Comment by cmitu** [comment]
Thanks, I'll merge as is.

**Pull request merged**
