### PR TITLE
Add "Sonic Robo Blast 2 Kart"

### PR DESCRIPTION
**Pull request by SuperFromND**
**Maintainers: Please read this entire text before accepting this PR!**

This PR adds [Sonic Robo Blast 2 Kart](https://mb.srb2.org/showthread.php?p=802727) (a modification of [Sonic Robo Blast 2](https://www.srb2.org/), which is itself based on the [Doom Legacy](http://doomlegacy.sourceforge.net/) source port) to RetroPie, as an experimental port.

Before accepting this PR, [this file archive](https://www.dropbox.com/s/xe8pzukzby1bwrj/srb2kart-assets.tar.gz?dl=1) (which contains all the files needed by the scriptmodule; these files are dropped by [the game's installer](https://mb.srb2.org/showthread.php?p=802727) and they don't appear to be hosted anywhere online) should be uploaded to [RetroPie's file hosting server](http://files.retropie.org.uk/archives/), similarly to how [Sonic Robo Blast 2](https://github.com/RetroPie/RetroPie-Setup/tree/master/scriptmodules/ports/srb2.sh)'s assets are handled.  

Just like when SRB2 was PR'd to RetroPie ( #1951 ), it might be a good idea to ask the developers of SRB2Kart (and potentially SRB2's dev deam as well; this *is* a mod of a mod after all) for hosting permissions.

### CODE REVIEW

**Comment by Awesomegamer6566** [comment]
THANK YOU

**Comment by Awesomegamer6566** [comment]
They need to update SRB2 because it is stuck at 2.1.13

**Comment by jw0z96** [comment]
Good stuff! I've been testing SRB2Kart through RetroPie on a pi 3B+, but can only seem to get it working in software render mode as it segfaults with OpenGL enabled (using the `-opengl` flag).

Have you tried running this with OpenGL enabled by any chance?

**Comment by SuperFromND** [comment]
@jw0z96 I just now got around to testing it on my Pi 4 after writing [https://retropie.org.uk/forum/topic/20025/srb2-kart-on-retropie/20](this post on the thread about SRB2Kart on the RetroPie Forums), and I *was* able to get the game to start with OpenGL.  Unfortunately, at least for me, it runs significantly worse than the software rendered mode.

Oh!  I should also post that, as that aeformentioned post probably indicates, I've tested this and can confirm it works on the Pi 4 on RetroPie 4.6 (albeit with a hack to "emulate" fetching the assets from RetroPie's file archive, as the post instructions detail).

**Comment by SuperFromND** [comment]
Closing since I've recently deleted the repository with the PR in question; I may revive this PR at some point in the future..

**Pull request closed without merging**
