### PR TITLE
wifi configuration script - thanks to herbfargus for the initial work.

### PR DESCRIPTION
**Pull request by joolswills**
@HerbFargus here you go - please try this

### CODE REVIEW

**Comment by joolswills** [comment]
it only edits the wpa_supplicant.conf and leaves /etc/network/interfaces as is - which by default should be fine for it to work. tested with wpa/wep/open network but can't guarantee it doesn't have bugs :)

**Comment by HerbFargus** [comment]
already found some :P my ssid has spaces so it calls it "the" when it should be "the network"

**Comment by joolswills** [comment]
thanks. ill sort that

**Comment by joolswills** [comment]
that should be sorted now.

**Comment by HerbFargus** [comment]
Its still saying unable to connect, but the ssid is correct now at least. I tried twice just to make sure the password was correct. might have something to do with it checking the encryption type. my router is both wpa and wpa2

**Comment by HerbFargus** [comment]
is there a way I can get it to give a verbose output of what its doing?

**Comment by joolswills** [comment]
add set -x to the script somewhere ? you can check the contents of wpa_supplicant config also.

it only waits 20 seconds for a connection, but that should be long enough.

**Comment by HerbFargus** [comment]
its reading it as WEP for some reason- it should be WPA

**Comment by joolswills** [comment]
you can see if the list function works correctly by doing `sudo ./retropie_packages.sh wifi list` note should output wpa for either wpa or wpa2, wep for wep, and open for unencrypted.

**Comment by joolswills** [comment]
please can you give me the output of iwlist scan ?

**Comment by HerbFargus** [comment]
yeah just a moment

**Comment by HerbFargus** [comment]
Cell 02 - Address: C8:D3:A3:70:C1:77
                    Channel:3
                    Frequency:2.422 GHz (Channel 3)
                    Quality=70/70  Signal level=-31 dBm  
                    Encryption key:on
                    ESSID:"The Antisocial Network"
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 9 Mb/s
                              18 Mb/s; 36 Mb/s; 54 Mb/s
                    Bit Rates:6 Mb/s; 12 Mb/s; 24 Mb/s; 48 Mb/s
                    Mode:Master
                    Extra:tsf=0000004aceb81f09
                    Extra: Last beacon: 50ms ago
                    IE: Unknown: 001654686520416E7469736F6369616C204E6574776F726B
                    IE: Unknown: 010882848B961224486C
                    IE: Unknown: 030103
                    IE: Unknown: 2A0104
                    IE: Unknown: 32040C183060
                    IE: Unknown: 2D1A6E1013FFFF000001000000000000000000000000000000000000
                    IE: Unknown: 3D1603000700000000000000000000000000000000000000
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD180050F2020101000003A4000027A4000042435E0062322F00
                    IE: Unknown: 0B05040015127A
                    IE: Unknown: 4A0E14000A002C01C800140005001900
                    IE: Unknown: 7F0101
                    IE: Unknown: DD07000C4303000000
                    IE: Unknown: 0706555320010B10

**Comment by joolswills** [comment]
aha. I need to make my grepping stricter.

**Comment by HerbFargus** [comment]
running `sudo ./retropie_packages.sh wifi list` almost all are listed as WEP but they are all wpa or wpa2

**Comment by joolswills** [comment]
your wireless card outputs a lot more IE lines than mine so I just need to improve the pattern matching.

**Comment by joolswills** [comment]
Strange as I just used your output instead of calling iwscan and it correctly identified it as wpa. was that the full output ? Please can you put set -x at the top of the list_wifi function and paste me the debug output of `sudo ./retropie_packages.sh wifi list`

**Comment by joolswills** [comment]
```
pi@retropie ~/RetroPie-Setup $ sudo ./retropie_packages.sh wifi list
The Antisocial Network
wpa
```

**Comment by joolswills** [comment]
if there are other networks, it might be I need the entire output not just some - you can email it to me privately at buzz[at]exotica.org.uk if you prefer.

**Comment by joolswills** [comment]
I have made a change which might help, but the only way it could end up with wep is if no lines after Encryption key:on have IE: with WPA on them - but I have just committed a change which makes the grep stricter.

**Comment by joolswills** [comment]
ok I can see the problem with your full output. debugging.

**Comment by HerbFargus** [comment]
I tried with the stricter grep and still logs it as wep

**Comment by joolswills** [comment]
I have a fix now - I needed to reset the "parser" differently due to field ordering. Just testing with wep/open network

**Comment by joolswills** [comment]
Please try with above fix.

**Comment by HerbFargus** [comment]
Brilliant! It works. I'll switch my router encryption to test the other types but it looks like it all should work

**Comment by HerbFargus** [comment]
I tested them all and they all work brilliantly including hidden SSID's. Thanks!

**Comment by joolswills** [comment]
Cheers for the help - will merge.

**Pull request merged**
