### PR TITLE
Adding install script for rigelengine

### PR DESCRIPTION
**Pull request by Exarkuniv**
Install script for Rigelengine made by lethal-guitar, who also looked over and cleaned up the script a little. He also tested it on a Pi3 since I only have a Pi4. Both install and run correctly

### CODE REVIEW

**Comment by cmitu** [comment]
@Exarkuniv this contains just a LZDOOM update now ? Did you push to the wrong branch ?

**Comment by Exarkuniv** [comment]
opps yeah

my github desktop lost all my repos. and that must of happen my mistake as i was trying to get everything back and going again

let me know on how to undo it, since i have no clue. if i need to

**Comment by cmitu** [comment]
Normally you'd do a separate branch for the pull request if you want to keep working on your `master`/`main` branch. You can reset your `master` branch to https://github.com/Exarkuniv/RetroPie-Setup/commit/931bb0ae22c2f87c0cf877e1573198dcd9ba0783 and commit `lzdoom` into a separate branch.
Or you can close the PR, create a separate branch from a clean RetroPie-Setup clone and add just the new scriptmodule for a new PR.

**Comment by lethal-guitar** [comment]
I believe the actual commit that's meant to be in this PR is https://github.com/RetroPie/RetroPie-Setup/pull/3448/commits/10500042e0ed9c0aade1aa8cad68317df145a03b

**Comment by cmitu** [comment]
> the LZdoom was not meant to be a PR request or anything for that matter.

It's probably been pulled by a rebase from upstream. Either way, your PR now removes the `lzdoom` module, so it's not good. Try creating a branch from your current `master`, then removing the last commit, then compare with RetroPie's `master`. If it's just the new scriptmodule, then apply the modification on your `master` branch also and it will be propagated here in the PR. 
If that doesn't work, I think it's better to re-do the PR, but use a separate branch instead of your `master` branch.

**Comment by Exarkuniv** [comment]
im just going to redo the PR, so that way i dont mess anything up. 
i barely know how to do a PR, 

and ill make a new branch as you said

**Pull request closed without merging**
