### PR TITLE
dosbox-staging: updates for 0.80

### PR DESCRIPTION
**Pull request by cmitu**
Added a few modifications needed to build & install the new 0.80 version:

 * Meson version needed is 0.57, which is not available in Debian _bullseye_ yet. Install 0.61.5 locally for the build step. This is the last `meson` version not requiring Python 3.7, which should cover Ubuntu 18.04 (still at 3.6)
 * Changed the install command to `ninja`, since `meson install` requires a system install for `meson` and thus install would fail when using the locally downloaded `meson`
 * SDL_Image is now a dependency

The changes allow building and installing on Ubuntu 18.04, which was previously failing.

Notable changes from the Dosbox-Staging 0.80 release (excerpts from https://dosbox-staging.github.io/v0-80-0/):

 * ReelMagic DOS games are now playable thanks to the efforts of Jon Dennis, Chris Guthrie, and Joseph Whittaker, with testing and feedback from Vogons users Uka, DonutKing, and Vetz
 * Mouse emulation has been improved and now supports up to six independent mice, enabling split-screen play in games like The Settlers and The Settlers II
 * More settings, including video, audio, and MIXER effects, can now be changed on the fly
 * Post-rendered screenshots - use  Alt+F5 to capture the as-seen (post-rendered) image, in addition to the previous (Ctrl+F5) screenshot function that captured the emulated video card's image prior to rendering
 * More bundled OpenGL shaders. Launch DOSBox Staging with the --list-glshaders command-line argument to list the available OpenGL shaders
 * FluidSynth's specific reverb and chorus configuration settings are now applied and will replace the default values that were previously always applied
 * The modem's call now has a warm-up period where it will discard data

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks!

**Comment by kcgen** [comment]
@cmitu , nice work!

I unfortunately [wasn't able to go back to Meson 0.56](https://github.com/dosbox-staging/dosbox-staging/commit/d81eb96cf194ab7062c91706460565629f98401b); so your solution is perfect.

Regarding the SpeexDSP wrap using NEON instructions, that's now committed to `main` with a couple other minor fixes.

This will form the basis of 0.80.1. 

I was wondering if you'd be able to smoke-test the `main` branch on your side? To double-check that SpeexDSP is fixed up (and more importantly!) make sure we haven't introduced new regressions or build errors. 

Much thanks! :christmas_tree: :snowman_with_snow:

**Comment by cmitu** [comment]
> I was wondering if you'd be able to smoke-test the `main` branch on your side? To double-check that SpeexDSP is fixed up (and more importantly!) make sure we haven't introduced new regressions or build errors.

Seems to work fine now, thank you for the Wrapdb PR. `meson` properly enables NEON support:
```

...

Executing subproject speexdsp

speexdsp| Project name: speexdsp
speexdsp| Project version: 1.2.1
speexdsp| C compiler for the host machine: cc (gcc 8.3.0 "cc (Raspbian 8.3.0-6+rpi1) 8.3.0")
speexdsp| C linker for the host machine: cc ld.bfd 2.31.1
speexdsp| Fetching value of define "__thumb__" :
speexdsp| Compiler for C supports function attribute visibility: YES
speexdsp| Configuring config.h using configuration
speexdsp| Compiler for C supports arguments -march=armv7-a: YES
speexdsp| Compiler for C supports arguments -mfpu=neon: YES
speexdsp| Compiler for C supports arguments /arch:VFPv4: NO
speexdsp| Has header "inttypes.h" : YES
speexdsp| Has header "sys/types.h" : YES
speexdsp| Has header "stdint.h" : YES
speexdsp| Configuring speexdsp_config_types.h using configuration
speexdsp| Library m found: YES
speexdsp| Build targets in project: 2
speexdsp| Subproject speexdsp finished.
...
speexdsp 1.2.1

  Library Summary
    Optimization level: 3
    SIMD instructions : NEON (armv7-a)
    Numerical type    : floating-point
    FFT library       : OggVorbis FFT (built-in)

dosbox-staging 0.81.0-alpha
...
```

The above log is from a Pi3 with the RetroPie image (so using _buster_ for now).

Thank you for the follow-up and happy holidays !

**Comment by joolswills** [comment]
Issues building for rpi1 with 0.80.1 - https://github.com/RetroPie/RetroPie-Setup/issues/3651

**Pull request merged**
