### PR TITLE
Update esthemes.sh

### PR DESCRIPTION
**Pull request by blowfinger77**
I have uploaded a new ES theme called LOCOMOTION

### CODE REVIEW

**Comment by joolswills** [comment]
Can I ask why all caps for the name ?

**Comment by blowfinger77** [comment]
Sorry if this is not allowed, I did not know.There is no reason.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Jools Wills <notifications@github.com>
Verzonden: Monday, October 22, 2018 8:29:20 PM
Aan: RetroPie/RetroPie-Setup
CC: blowfinger77; Author
Onderwerp: Re: [RetroPie/RetroPie-Setup] Update esthemes.sh (#2517)


Can I ask why all caps for the name ?

**Comment by joolswills** [comment]
Since the name is used for the folder, I would prefer it to be lowercase. Some people have the first character uppercased, but lowercase is preferable.

**Comment by blowfinger77** [comment]
Can I still change this, this is the first time I do this.I am still a beginner with the github.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Jools Wills <notifications@github.com>
Verzonden: Monday, October 22, 2018 8:42:26 PM
Aan: RetroPie/RetroPie-Setup
CC: blowfinger77; Author
Onderwerp: Re: [RetroPie/RetroPie-Setup] Update esthemes.sh (#2517)


Since the name is used for the folder, I would prefer it to be lowercase. Some people have the first character uppercased, but lowercase is preferable.

**Comment by joolswills** [comment]
https://help.github.com/articles/renaming-a-repository/

**Comment by blowfinger77** [comment]
Thank you for the link and the help.
I have changed it, then everything is fine, I hope?

**Comment by joolswills** [comment]
Please update the PR with the text in lowercase. If you are unsure, I will just add your theme when next working on the code.

**Comment by joolswills** [comment]
Thanks.

**Comment by blowfinger77** [comment]
I corrected it in the PR.
Thanks Jools for your help. I appreciate that.

**Pull request merged**
