### PR TITLE
Odroid XU support

### PR DESCRIPTION
**Pull request by joolswills**
This is a WIP. Put here for those that want to test while it's being worked on (no bug reports yet please). 

What is currently working:

RetroArch / ES / SDL2 and most main emulators build.

### CODE REVIEW

**Comment by cadsj** [comment]
Lakka and Batocera has Odroid XU support, can be useful?

**Comment by miloshdrown** [comment]
@joolswills I think when you added this most resent commit it dumped the patch you had that added the hard coded struct. Was that intentional?

**Comment by joolswills** [comment]
Yes. I upstreamed it.

**Comment by joolswills** [comment]
The last commit just removes a struct rename, which is no longer needed.

**Comment by joolswills** [comment]
(having said that - it's not in retroarch v1.5.0 yet - but this is a WIP).

**Comment by joolswills** [comment]
I needed to rebase over the latest master changes. I have done this and re-added the struct until retroarch v.1.5.1 or so. If master gets updated with the next retroarch before this PR is finished, I will rebase again and remove the patch.

**Comment by miloshdrown** [comment]
Perfect. Thanks.

**Comment by gefink** [comment]
Hi all,
I'm new to Retropie, but I have an odroid xu3 that I tried with this branch.  The installation went pretty smoothly but as mentioned the keyboard doesn't work.  I've been trying to run some nes games, mostly super mario bros, but the lag makes the game unplayable.  I've tried a couple of different usb game pads, a tv and a monitor, various resolution settings, and the three different emulators, but nothing seems to make any difference.   Has any body successfully played and games with this branch?

**Comment by stikoyan** [comment]
Hello all, 
Its been a while since ive done anything with retropie as ive been messing with recalbox due to having an Odroid XU4, id like to test this branch on my XU4 but ive forgotten how to do so, can someone provide basic insturctions on how to get this branch installed.

thanks

**Comment by gefink** [comment]
You need to checkout this pull request:
See https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by joolswills** [comment]
Keyboard should work in ES so long as the running user can access /dev/input (`usermod -a -G input youruser`)

**Comment by gefink** [comment]
Thanks joolswills, you were right the default period user was not part of the group input. They keyboard works now, but I still have the big lag problem.

**Comment by gefink** [comment]
*period=odroid

**Comment by joolswills** [comment]
I don't want this PR to become a support ticket for odroid - prefer a forum thread. There are various ways to reduce lag. TV game mode / retroarch settings. etc

**Comment by joolswills** [comment]
Right now im concentrating on getting modules built. I will do some more testing once that is done. I pushed some more changes to the branch to solve some build issues, and allow adding the groups via retropie-setup.

**Comment by joolswills** [comment]
I'm going to merge this now. All the packages from core/main should build, and most of the optional packages. Some issues still with PPSSPP and others. I will do more work over the coming weeks.

**Pull request merged**
