### PR TITLE
Add Raspixel 320x240 theme

### PR DESCRIPTION
**Pull request by cjonasw**
https://github.com/cjonasw/raspixel-320-240

### CODE REVIEW

**Comment by cmitu** [comment]
Thank you for submitting your theme.
Is there any license associated with the theme ? Is the artwork done by you or is it from other theme ?

**Comment by cjonasw** [comment]
The artwork is a combination of my work and theme it was based on. That person's theme was also based on another. 

I believe the license is the same as the one it's based off of, to respect that person's wishes too. Creative commons

**Comment by cjonasw** [comment]
Added license on repository for clarity, realised it was missing.

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
