### PR TITLE
improved bluetooth pairing - Support DisplayYesNo / and parse output …

### PR DESCRIPTION
**Pull request by joolswills**
…of bluez-simple-agent to decide whether to ask for a pin, or display an automatically provided pin. #980 

@biscuits99 I would be very interested to see how this works for you with your controllers. Also if anyone can test with keyboards that would be great.

### CODE REVIEW

**Comment by biscuits99** [comment]
No problem, I'll try it out.
So on RetroPie 3.1, if I update the setup script then use the inbuilt BT pairing menu item?

**Comment by joolswills** [comment]
you can do

```
git remote add jools https://github.com/joolswills/RetroPie-Setup.git
git fetch jools
git checkout bluetooth
```

and when done

```
git checkout master
```

**Comment by joolswills** [comment]
(and then try out the bluetooth pairing module from the setup / configuration menu)

**Comment by biscuits99** [comment]
I ran a test (https://youtu.be/Ky2wxpmwXWw) pairs really well on both the 8bitdo controllers I have.
Oddly they behaved differently, one asked for a code, one didnt - as seen in video.

Couldnt get emulation station to detect (or try to connect) on startup though. Not sure if the pairing process above tells the Pi to connect on boot up?
If already connected from the setup script and ES is started from command line, it happily uses its controller input script to log the buttons on the controller though.

I tried going back to the setup script to re-connect to the pro controller - but an error came up saying it already exists - although I just wanted to re-connect, as opposed to re-pair.

**Comment by joolswills** [comment]
Thanks for the video - it should reconnect on restart, but perhaps ES is loading too quickly. 

Can you try booting up, exiting out of ES, and then waiting and reloading ?

I'll check with my BT keyboard also.

Not sure why it asked for a pin the second time, but I will likely switch the options over as I think the DisplayYesNo works for more devices.

I can see a few other tweaks to do also.

**Comment by gizmo98** [comment]
If bluetooth is down controller does not pair at startup. You could add the same "hciconfig hci0 up" udev rule as our ps3controller module.
https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/ps3controller.sh#L83  

You can check if bluetooth is up with "hciconfig".

**Comment by joolswills** [comment]
it shouldn't be down at startup though by default?, at least when I have tested previously with my keyboard it always paired at startup.

**Comment by gizmo98** [comment]
Is a ps3 controller installed? If so remove udev rule "10-local.rules" and try again. If bluetooth is down udev rule is necessary.

Some users with ps3 controllers had problems with their bt dongles. They were down at startup. That's the reason udev rule was added.

**Comment by biscuits99** [comment]
Still no joy getting ES to pick it up on start up (other than its inbuilt register controller menu). I tried getting the joypad to start searching at various points during the boot up process.
To confirm, no ps3 controller is plugged in or installed when I tested in video.

Happy to try any specific test again, just shout.

**Comment by joolswills** [comment]
The output of "hciconfig" ?

**Comment by gizmo98** [comment]
Yeah hciconfig.
hciconfig without any parameter shows all hci devices and their state. Is hciconfig not present? Raspbian jessie?!

**Comment by biscuits99** [comment]
I was running 3.1 from main website, using the torrent image for RPi2.
Bluetooth dongle and keyboard plugged into USB.
No changes at all other than extending the filesystem - plus what you see in the video.

Just ran hciconfig: (my joypad isnt connected at this point)

```
pi@retropie ~ $ hciconfig
hci0:   Type: BR/EDR  Bus: USB
        BD Address: 5C:F3:70:69:F9:7F  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING PSCAN
        RX bytes:1545 acl:0 sco:0 events:79 errors:0
        TX bytes:1308 acl:0 sco:0 commands:79 errors:0
```

The bluetooth display tool currently shows both my joypads as registered, with neither having an active connection.

**Comment by joolswills** [comment]
if you manually pair them from the commandline without using the script do they reconnect on reboot ? In case I've missed something obvious it would be useful to see what you do if that works Does it make any difference if you use DisplayYesNo to pair them with the script? 

The script should be doing the following:

```
bluez-simple-agent -c DisplayYesNo hci0 MACADDRESS
bluez-test-device trusted MACADDRESS yes
bluez-test-input connect MACADDRESS
```

**Comment by joolswills** [comment]
I just fixed the wrong variable use in the code, but it should still have run the command but please git pull the latest code in and try removing/readding.

**Comment by joolswills** [comment]
I have just tested again with my bluetooth keyboard and everything connected as it should after a reboot.

**Comment by biscuits99** [comment]
Still no joy in getting it to connect on start up, details here (https://youtu.be/XrSieJHIgZ0).
It pairs and connects fine, but doesnt reconnect on boot-up for me.

It seems the only way I could do it is with Step 4 listed here:  
https://github.com/RetroPie/RetroPie-Setup/wiki/Setting-up-a-Bluetooth-controller

**Comment by joolswills** [comment]
do you have any bluetooth keyboards you can test with ? Maybe gamepads don't auto connect in the same way. I guess I'll have to get myself one to come up with a solution.

**Comment by joolswills** [comment]
Also after a reboot, what is the output of `bluez-test-device trusted MACADDRESS` - just to make sure the pads are still trusted.

**Comment by joolswills** [comment]
Also - can you test changing the file /etc/default bluetooth

there are two settings

```
HID2HCI_ENABLED=0
HID2HCI_UNDO=0
```

please can you try switching them to one ?

**Comment by joolswills** [comment]
Also even though your bluetooth controller was in PSCAN mode, if you don't have the connect line in /etc/rc.local but put "hciconfig hci0 pscan" there - does that make any difference? Appreciate your patience in helping me :) Just want to make sure the controller is in the correct mode etc.

**Comment by joolswills** [comment]
Also which controllers do you have - please can you provide me with an amazon link - I may buy one for testing.

**Comment by biscuits99** [comment]
No luck I'm afraid, tests here (https://youtu.be/-webiOk5wdQ)

I'm happy to post you the 2 bluetooth controllers for a couple of weeks if you want to test them out.
I have these:
http://www.amazon.co.uk/8Bitdo-FC30-Wireless-Controller-Android/dp/B013B48POY/
http://www.amazon.co.uk/8Bitdo-GamePad-Wireless-Controller-Android/dp/B013B4MNW4/

**Comment by joolswills** [comment]
Thanks - but might be worth me buying one of them for future dev etc - not too much and saves you being without gamepads etc. I see the snes styleone on one website for £20 also.

I'm wondering if other bluetooth gamepads have the same issue, so it would be useful if anyone else could test this branch out - perhaps I should ask on the forum.

**Comment by joolswills** [comment]
I'm going to squash and merge the improvements so far, and look at sorting out automatic connection for gamepads once I have one for testing.

**Comment by gizmo98** [comment]
@joolswills 
Do you have an idea how to run hciconfig devices/hci up at startup? It seems to be not every bt dongle is up at startup. Floob/biscuits99 added a wiki entry to add this line to rc.local. https://github.com/RetroPie/RetroPie-Setup/wiki/Setting-up-a-Bluetooth-controller/_compare/07585a7^...07585a7#diff-25912177cd7927b81d9025271662b8bfR92

PS3 controllers do not have this problem because sixad sets hci devices up if sixad daemon starts.

**Comment by joolswills** [comment]
As I remember it, the problem floob was having was with the controller devices not connecting when trusted, which was not down to the bluetooth dongle, but the controllers themselves (and some incompatibility with the stack or something). Although not actually sure why the changes highlighted above are needed as that looks like something else.

**Comment by joolswills** [comment]
The wiki has another section for the connecting on startup. In regards to his above change, I guess I need to ask him more about it.

**Comment by biscuits99** [comment]
Yes, the issue I had was that I couldnt connect to the paired device when restarting the Pi, this is resolved by Step 3 here: https://github.com/RetroPie/RetroPie-Setup/wiki/Setting-up-a-Bluetooth-controller

I added the extra step in troubleshooting, as many people had asked how to re-connect without restarting the Pi - and a couple of users have posted that solution in the forums. As the device may go into sleep mode, there wasnt a way to reconnect without explicitly running the connect request again. So that may help in that respect. Although it seems recalbox does this pretty well with my limited testing.

**Comment by gizmo98** [comment]
I had this issue to with ps3 controllers. After the first controller paired pscan was disabled. A sixad udev rule enables pscan again if it is disabled.

**Comment by joolswills** [comment]
In terms of the connecting controllers devices, I was hoping the bluetooth stack in Jessie would sort it. I still didn't get myself one of these to test though, which might be an idea. A udev rule could possibly fix up the other issue, but I would like confirmation that this is needed with some actual hardware to test first.

**Pull request merged**
