### PR TITLE
add Digger Remastered to experimental

### PR DESCRIPTION
**Pull request by proyvind**
screwed up previous pull request, recreating again with issues fixed

### CODE REVIEW

**Comment by joolswills** [comment]
You can re-use existing PRs by fixing / rebasing and force pushing btw.

**Comment by psyke83** [comment]
Adding to what @joolswills said - make sure to re-open the PR before force-pushing a change or else you'll need to jump through hoops to make the PR track your branch again.

**Comment by joolswills** [comment]
Thanks for the module.

**Comment by joolswills** [comment]
Probably should have done more testing before accepting this, but assumed the folders were correct. 
There is nothing saved to `$home/.config/digger"` so it makes an unneeded symlink. digger uses a `$home/.digger.rc` and a `$home/.digger.sco` though. I will fix this up.

**Comment by joolswills** [comment]
the pushd and popd are also not needed.

**Pull request merged**
