### PR TITLE
Update mupen64plus.sh

### PR DESCRIPTION
**Pull request by solskogen**
Add back support for compiling it with distcc

### CODE REVIEW

**Comment by joolswills** [comment]
This was disabled for a reason so I will need more information to re-enable it.

**Comment by solskogen** [comment]
I guess it was, so I enabled it just for test and it seems to work just fine on a up-to-date Raspbian 64bit (at least) - I don't have 32bit available at the moment, but I could get my hands on it if you wish.

**Comment by joolswills** [comment]
It's still an issue so I'd rather not change this. The distcc support is included primarily for my purposes so it's probably best to just your own branch with the changes if you need them.

**Comment by solskogen** [comment]
Could you post the error you get?

**Comment by solskogen** [comment]
I'm closing this. I've confirmed that it still fails on 32bit.

**Pull request closed without merging**
