### PR TITLE
helpers - document and improve the ask() function

### PR DESCRIPTION
**Pull request by hhromic**
Someone forgot to document the `ask()` function in `helpers.sh`.  Fix that :)

### CODE REVIEW

**Comment by hhromic** [comment]
fine-tuned the function a bit too on the spot:
* set `ans` as local variable
* do not allow backslashes to escape any characters in `read`

**Comment by joolswills** [comment]
Actually it was intentional as the function will be removed - it's a leftover from very early versions of RetroPie-Setup and isn't used anywhere. I will remove it at some point.

**Comment by hhromic** [comment]
Ah, a vestigial function. oh well.. you can discard this PR then if that is the case.

**Comment by hhromic** [comment]
I can confirm (via grep) that no script in the repository is using ask() currently.
What stops its removal?  I can modify this PR to remove the function instead and keep RetroPie tidy.
Let me know.

**Comment by joolswills** [comment]
I just haven't got around to it. Appreciate the offer, but I don't think it's needed to do a PR for the removal.

**Comment by hhromic** [comment]
No problem. I will close this PR then. Cheers and great job in general with RetroPie, very impressive bash programming.

**Comment by joolswills** [comment]
Thanks for your support.

**Pull request closed without merging**
