### PR TITLE
Update the Minecraft Pi module

### PR DESCRIPTION
**Pull request by RetroPieNerd**
I have updated the Minecraft Pi module to be more convenient and relevant.
:)

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks - can you be more specific as to improvements with the packaged version.

I would probably avoid the module rename - saves having an extra update hook to run and it will need to clean up the old folder etc. I think it might just be best to leave it called minecraft for now - if we need the namespace in the future that can be changed then.

**Comment by RetroPieNerd** [comment]
The packaged version throws Python 2 out the window as it is legacy stuff now, in favor of Python 3.

**Comment by RetroPieNerd** [comment]
Also, the accompanying Python module will be installed globally along with the game.

**Comment by joolswills** [comment]
Thanks. The update hook won't be needed now since the install folder will now exist - I will need to perhaps remove the contents of it though if not empty. If you can remove the update, I will merge and do the folder cleanup bit.

**Comment by RetroPieNerd** [comment]
Well, thanks! I just learned a little more about the RetroPie module format!

**Comment by joolswills** [comment]
I made a couple of changes - also keeping the addPort name as just "Minecraft" otherwise you get an additional launch script (which means we would need to clean up the old one - but I'm ok with just plain Minecraft.sh)

**Comment by RetroPieNerd** [comment]
Ok.

**Pull request merged**
