### PR TITLE
added opentyrian - in experimental for now. Works well on my system -…

### PR DESCRIPTION
**Pull request by joolswills**
… thanks to Herb / dudleydes #1050

### CODE REVIEW

**Comment by HerbFargus** [comment]
@joolswills works brilliantly mate. Thanks!

**Comment by dudleydes** [comment]
I cannot build OpenTyrian on the Raspberry Pi 1 but it builds fine on the Pi 2.

The issues I raised in https://github.com/RetroPie/RetroPie-Setup/issues/1050 regards hqNx only appears to affect the Pi 1. I can build successfully by deleting video_scale_hqNx.c and commenting out lines 53, 56 and 58 in video_scale.c.

Sorry, should have mentioned this earlier.

**Comment by joolswills** [comment]
out of memory issue - well you can check by looking at dmesg.

256 or 512 pi ? you can reduce gpu mem perhaps - I can add a minimum so more swap gets added, but not major as in experimental etc.

**Comment by dudleydes** [comment]
It's a 512 pi. I tried to build by setting the gpu mem to 16 without success.

What should I be looking for in dmesg?

**Comment by joolswills** [comment]
the system running out of memory and killing gcc. post it on pastebin.com or similar if unsure and ill check.

**Comment by dudleydes** [comment]
Here is the output from dmesg:

http://pastebin.com/pJY8XNmU

**Comment by joolswills** [comment]
Yeh - out of memory

 1664.813469] Out of memory: Kill process 2608 (cc1) score 836 or sacrifice child

**Pull request merged**
