### PR TITLE
System reorg

### PR DESCRIPTION
**Pull request by joolswills**
Reorganisation of system splitting out some code into functions

__jobs var with a simple default based on memory and nproc
Set MAKEFLAGS -jX based on this
some memory var changes
Rework of all compiler flag logic

### CODE REVIEW

**Comment by joolswills** [comment]
I'm leaning towards removing the auto vectorization flags. They can cause issues and
I have not managed to measure any performance apart from synthetic floating point benchmarks.

Better to enable them if and when is proven useful imho. The default flags should be reliable.

**Comment by joolswills** [comment]
Will rebase this soon.

**Comment by joolswills** [comment]
This is rebased. I'll do a few checks but unless anyone sees any issue will merge soon.

**Comment by cmitu** [comment]
(not a bug) Because of `platform_all` , the unknown message platform shows `all` as one of the possibilities:

> Unknown platform - please manually set the __platform variable to one of the following: **all** armv7-mali generic-x11 imx6 odroid-c1 odroid-c2 odroid-xu rpi1 rpi2 rpi3 rpi4 tinker vero4k x86

**Comment by joolswills** [comment]
Ah good spot. I'll rename the function.

**Comment by joolswills** [comment]
I made a set_plaform_defaults for the default optimisation and put it before to simplify things (removes a check). Tbh it doesn't need to a function really, but I had some ideas for future defaults.

**Pull request merged**
