### PR TITLE
drastic: workaround faulty input handling in a KMS context

### PR DESCRIPTION
**Pull request by cmitu**
_DraStic_ has input problems when running in a KMS context, reported a few times in the forums.
There is a workaround by running it a X11 session, with a minimal window manager (similar to Steam Link). 

Tested on a PI3 (Stretch) and PI4 (Buster), I don't know if the bug is present on Pi3 (Buster) with the legacy BRCM drivers

### CODE REVIEW

**Comment by psyke83** [comment]
Have you tried checking if `SDL_HINT_NO_SIGNAL_HANDLERS` or `SDL_HINT_VIDEO_DOUBLE_BUFFER` helps with this issue?

**Comment by cmitu** [comment]
@psyke83 I tried a few hints, but the ones you mentioned, but it doesn't seem to make a difference.

**Comment by joolswills** [comment]
Just to note drastic also crashes on exit here (launching with no parameters).

I'm not that keen on such a drastic workaround :-) but will consider options.

**Comment by cmitu** [comment]
We don't need to merge it, we can look further for a solution.

What I notice it's different on X11 than on KMS/DRM is that my touchpad gets activated (the DS has a touchpad) on X11. On a RPI 3 system, where the RPI driver is used, the issue doesn't occur and the left analog joystick acts as a mouse.

**Comment by psyke83** [comment]
I haven't looked at drastic yet, but in case it helps, the issue that affected steamlink and DualShock controllers was caused by a systemd bug: https://github.com/systemd/systemd/issues/5703

I'm not 100% sure if the buster version includes that fix, but I imagine it should?

**Comment by cmitu** [comment]
@psyke83 if any, this bug would break the gamepad appearing correctly under X11, but I can check via `udevadm` what's reported for the controller. SDL2 seems to get the inputs alright (tested via the SDL_EVENT_LOGGING hint), but what happens inside `drastic` with the events it's probably the issue.

**Comment by cmitu** [comment]
I checked, but the `udev`/`systemd` but is not present, instead the `ID_INPUT_JOYSTICK` is set correctly.

**Comment by Bluebotlaboratories** [comment]
Is there a way for me to install this version of DraStic?

**Comment by joolswills** [comment]
As we didn't find a solution I think your changes are the best bet @cmitu

Merging. Thanks!

**Pull request merged**
