### PR TITLE
lr-flycast: (QOL) add to Arcade system (redux)

### PR DESCRIPTION
**Pull request by s1eve-mcdichae1**
Ref: https://github.com/RetroPie/RetroPie-Setup/pull/3517

(Revisited for `defaultRAConfig`)

### CODE REVIEW

**Comment by joolswills** [comment]
Why are you not using the original PR ?

**Comment by s1eve-mcdichae1** [comment]
> Why are you not using the original PR ?

Still getting my GIT legs, I guess. I figured the old one was outdated since the code had changed "underneath" it, so to speak. So I made this new one based on the most recent version.

is it preferable, then, to continue building off the original, even when the current version diverges from that?

**Comment by joolswills** [comment]
It's possible to make the changes in the old branch, then squash them together and force push back. But if new to git, that's ok. This change looks good thanks - I will give it a test then merge.

**Comment by joolswills** [comment]
I will squash this also.

**Comment by cmitu** [comment]
@s1eve-mcdichae1 don't use the web interface. 
From the CLI, run `git rebase -i <commit-ish>` to squash all commits (including the one chosen) into a new one. Then push again (using `--force`) to your branch the new commit.

**Comment by s1eve-mcdichae1** [comment]
@cmitu huzzah!

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
