### PR TITLE
remove retropie-manager.sh

### PR DESCRIPTION
**Pull request by meleu**
The repository owner deleted his github account and so the retropie-manager repository.

In 27-August-2019 I received an email from github saying that he tried to transfer the ownership of the repository to me and that the transfer would expire in about a day. I've read the message today (02-September-2019) and noticed the transfer expired and the repository is gone.

### CODE REVIEW

**Comment by joolswills** [comment]
I have a copy I think so I'll re-upload.

**Comment by joolswills** [comment]
My copy is old I reckon.

https://github.com/RetroPie/RetroPie-Manager

@botolo78 should have a local version he can repush. Also anyone who has it installed - I can rebuild the repo from.

**Comment by joolswills** [comment]
GitHub may be able to recover it also if the owner contacts them. Annoying - why did they remove it before the transfer was done.

**Comment by cmitu** [comment]
@joolswills I have a (shallow) copy from Dec 2018 from an installation.
[retropie-manager.zip](https://github.com/RetroPie/RetroPie-Setup/files/3567687/retropie-manager.zip)

**Comment by joolswills** [comment]
If you push that to your account I can update our fork. Will miss individual changes but will be more up to date. Thanks

**Comment by joolswills** [comment]
Missed the link. Would be easier if you can put the checkout to a repo though - but more work your end I realise.

**Comment by cmitu** [comment]
@joolswills will give it a shot.

**Comment by joolswills** [comment]
Actually don't worry. I'll use your archive. It has the .git folder I guess. Thanks

**Comment by cmitu** [comment]
Too late - https://github.com/cmitu/retropie-manager.

**Comment by joolswills** [comment]
No worries. Thanks. Only a few changes anyway. Pushing to our fork in a min and I'll update module.

**Comment by joolswills** [comment]
Should be sorted now. Thanks for the help.

**Comment by meleu** [comment]
Nice job guys. :+1: 

I'm closing this PR.

**Pull request closed without merging**
