### PR TITLE
es theme modern addition

### PR DESCRIPTION
**Pull request by HerbFargus**

### CODE REVIEW

**Comment by HerbFargus** [comment]
... once rook adds it to github.... we'll leave this til he does.

**Comment by joolswills** [comment]
I merged before reading comment. Sorry :-)

**Comment by joolswills** [comment]
Well, doesn't matter. Do you want me to revert it or leave it for now?

**Comment by HerbFargus** [comment]
eh we can leave it, I'll chat with rook when he's around

How I figure is we can just find a swanky default image and then if people want to modify it we'll have a tutorial for it on the forum thread or something

**Pull request merged**
