### PR TITLE
Replaced old version of Space with 2.0 (video support)

### PR DESCRIPTION
**Pull request by robertybob**
I've done some testing on my spare RPi2 with GB,GBC and SNES. Seems to work ok!

### CODE REVIEW

**Comment by joolswills** [comment]
This won't allow people to update or remove the old space - it will be a new install - if it's just the addition of video support it might be worth using the same repo so people can update ?

**Comment by robertybob** [comment]
Fair comment, I'll just rename the new branch the same as this

**Comment by joolswills** [comment]
If you mean deleting the old repo and renaming the new one that will break updating also. The only way would be to update the old repo with the new code.

**Comment by robertybob** [comment]
Hm, so giving it the same name won't work? Is that due to the way the theme installer/updater works?

**Comment by joolswills** [comment]
No - you will need to update the old repository - which would also seem the logical way if adding video support. It's because it does a `git pull` to update.

**Comment by robertybob** [comment]
Ok I think I've done it correctly, should be sorted out now :)

**Pull request closed without merging**
