### PR TITLE
Add console font scriptmodule

### PR DESCRIPTION
**Pull request by psyke83**
Allows convenient configuration of certain preset font type/sizes
appropriate for viewing on large screens.

### CODE REVIEW

**Comment by psyke83** [comment]
@joolswills,

I made the changes you requested on the forum, with the caveat that I decided to move the lines to check the current font into a new function in order for the GUI to report them twice - for the menu subtitle, and once a selection has been made.

**Comment by joolswills** [comment]
Looks good - thanks.

**Comment by joolswills** [comment]
I will need to add another option - the Fixed font is not the default (VGA is the default, but `/etc/default/console-setup` doesn't include anything for that)

**Comment by psyke83** [comment]
During the process of writing the module, I was experimenting with inserting values via "echo ... | debconf-set-selections". I ultimately decided that it was making things overly-complex, so I scrapped the idea and instead opted for direct config editing (since you have already functions intended for this kind of purpose).

I purge-removed console-setup and re-installed console-setup in order to check the font size/type default, and that results in Fixed 8x16 being filled. Does Raspbian change the package default when building images?

**Comment by joolswills** [comment]
I have no idea, but the default Raspbian image doesn't have that as the default. Perhaps it's due to reinstalling the package. I can confirm that behaviour - so understand the confusion. The fixed font is thinner than the default Kernel font (which basically looks like the VGA 8x16 with minor differences) and less readable on my screen. Anyway - I made the changes now - so the Fixed is still available but you can switch to use the Default Kernel font (reboot is needed).

**Comment by joolswills** [comment]
default Raspbian console-setup config -

```
# CONFIGURATION FILE FOR SETUPCON

# Consult the console-setup(5) manual page.

ACTIVE_CONSOLES="/dev/tty[1-6]"

CHARMAP="UTF-8"

CODESET="guess"
FONTFACE=""
FONTSIZE=""

VIDEOMODE=

# The following is an example how to use a braille font
# FONT='lat9w-08.psf.gz brl-8x8.psf'
```

after purging and reinstalling console-setup

```
# CONFIGURATION FILE FOR SETUPCON

# Consult the console-setup(5) manual page.

ACTIVE_CONSOLES="/dev/tty[1-6]"

CHARMAP="UTF-8"

CODESET="Lat15"
FONTFACE="Fixed"
FONTSIZE="8x16"

VIDEOMODE=

# The following is an example how to use a braille font
# FONT='lat9w-08.psf.gz brl-8x8.psf'
```

**Comment by psyke83** [comment]
Ah... thanks - I neglected to backup the original file before I started messing around. A way to avoid the reboot for changes to take effect would be to set the font twice; i.e:

```
            5)
                 set_consolefont "Fixed" "8x16"
                 set_consolefont "" ""

                 ;;
```

The check_consolefont could be cleaned up slightly to report empty results as "defaults" or whatever. Will I send a PR to add that to your changes or are you happy to leave as-is?

**Comment by joolswills** [comment]
Your code above would leave it as "Fixed". If the fields are cleared, you don't get the Kernel font without a reboot. the VGA 8x16 is virtually the same, but not quite (hard to tell though).

**Comment by joolswills** [comment]
i'm happy to leave it as is.

**Comment by joolswills** [comment]
(apart from perhaps adding some more choices).

**Comment by psyke83** [comment]
I edited Fixed -> VGA moments before your reply, but I missed your explanation that it's slightly diff. to the kernel font, so it's not exactly true that it avoids the need for reboot anyway.

Sorry for the mess. Yes, let's wait and see if users have a need for other sizes, perhaps. I'm restricted to testing on a 720p capable TV, so "Medium" is the only realistically usable size for me.

**Comment by joolswills** [comment]
Aah. Could do a switch to VGA before, but it's not a big deal I guess.

**Pull request merged**
