### PR TITLE
changing retropie defaults to allow easier switching of video smoothi…

### PR DESCRIPTION
**Pull request by joolswills**
…ng by only setting it in the core - and turning it on my default. This should look better for most users without having to configure shaders. with the new configuration tool this can easily be changed. also default threaded video to off for better sync. #933

### CODE REVIEW

**Comment by joolswills** [comment]
@biscuits99 @HerbFargus @petrockblog 

Here's the default config changes.

Video smoothing on by default, but not overridden in per core configs. 

per core configs by default now look like

```
# Settings made here will only override settings in the global retroarch.cfg if placed above the #include line

input_remapping_directory = /opt/retropie/configs/gb/
# video_smooth = false
video_shader = /opt/retropie/emulators/retroarch/shader/hq4x.glslp
# video_shader_enable = true

#include "/opt/retropie/configs/all/retroarch.cfg"
```

and with the new config edit tool it is easy to switch video smoothing off for those that prefer it (and video threading on etc).

**Comment by joolswills** [comment]
Whether smoothing is on or off by default could be debated, but for most users on modern LCD, i think it looks better on - as scaling artifacts are less obvious (imho), but at least now it can be switched easily for those that dont want to configure shaders for each platform.

**Comment by HerbFargus** [comment]
looks good to me

**Comment by biscuits99** [comment]
sounds good

**Comment by robertybob** [comment]
Does this affect performance on RPi 1?

**Comment by joolswills** [comment]
video threading off could perhaps reduce performance slightly, but from my own testing, it only made a slight different on emulators that were pushing the limits of the pi1 capability. So long as we document the changes it's not an issue to me - we can document how to use the new config editor etc.

Thankfully we have people like @HerbFargus and @biscuits99 to help with all that :)

**Comment by joolswills** [comment]
Im ready to merge this and push out a new image. @robertybob please email me at buzz[at]exotica.org.uk and I will give you an image to test before release.

3.0 is too long coming.. you can never be bugfree. If testing from you guys turns up stuff, mayhbe a rc2, but its been sooo long since 2.6 - I really want people to use the newer versions. so much has changed. cheers

**Comment by joolswills** [comment]
I'm going to merge and offer up a build to you guys.

**Comment by joolswills** [comment]
I would also add, I read a post from a user that tried retropie and thought it looked all "blocky" and then switched to recallbox os. I'm still with the thinking that we should offer basic defaults but adhere to the needs of power users. the video smooth value is on by default on retroarch - and I think it's a better default. Now it can easily be switched, even from a controller.

**Comment by HerbFargus** [comment]
As soon as I've tested the new image I'll overhaul the wiki again and update it to 3.0

**Comment by joolswills** [comment]
thanks. let me know anyway - ill post it via g+ i guess, but you know the url, and should it pass your tests I'll send it on to @petrockblog for release. I will need to make a changelog also i guess, with the most important stuff between releases.

**Comment by joolswills** [comment]
2.6 to 3.0 was too long.. it should have been 3.0 last year and 4.0 now..

**Comment by HerbFargus** [comment]
Maybe this should be a separate ticket but I think maybe it would be a good idea to have a prioritised list of improvements that are reasonable to pursue for future releases.

**Comment by joolswills** [comment]
I think a wishlist is ok, but I may be retiring - well not really, but I need to put some more love into http://www.xbmc4xbox.org.uk ...

**Comment by joolswills** [comment]
maybe a spreadsheet would be useful though

**Comment by HerbFargus** [comment]
Sure, I'll set one up and open up a ticket. (even if you take a leave of absence for a bit, 3.0 is a pretty good place to be. thanks for all the work :) )

**Comment by robertybob** [comment]
@joolswills Thanks for the offer - I don't currently have the time to do any testing (it's a struggle to get a lot of time to play tbh!) however I still follow progress regardless :)   I trust your judgement that it's a worthwhile addition, with minimal slowdown, for the RPi1

**Pull request merged**
