### PR TITLE
Rock64 support

### PR DESCRIPTION
**Pull request by joolswills**
WIP rock64 support using https://github.com/ayufan-rock64/linux-build/releases/download/0.5.15/xenial-minimal-rock64-0.5.15-136-armhf.img.xz as a base.

### CODE REVIEW

**Comment by Ntemis** [comment]
Hi, can i ask why the decision to use armhf image on an arm64 soc?
You are treating the soc as you did with C2 but did you use 32bit release on that one too?
 Newbie at retropie build system and i am trying to figure out some bits that look out of order in my mind.
At Lakka we use gbm with arm64 and 32bit userspace and everything work fine.
Checked ppa and has the blob libmali-rk-utgard-2th-r7p0_1.5-4ayufan12_armhf.deb we use on lakka
Also in my opinion it would be better if you upgraded to 0.6.1 image vs 0.5.15 :)

**Comment by joolswills** [comment]
emulation is better optimised for 32bit arch (eg armv7 / neon asm optimisations). Only ppsspp has aarch64 asm opts. The image is a 64bit kernel with 32bit userland - which imho suits emulation better than aarch64.

A 64bit userland should work - although I haven't tested.

I used the base image the rock64 devs linked me to - I would assume it's working on the newer one also so long as packages are similar etc.

**Comment by raidensnake** [comment]
On a separate note I did get part of retropie working on arm64

**Comment by joolswills** [comment]
Have rebased the PR. Currently testing onagainst this image https://github.com/ayufan-rock64/linux-build/releases/download/0.6.36/bionic-minimal-rock64-0.6.36-220-armhf.img.xz

**Comment by Ntemis** [comment]
@joolswills i have a question
Is there any door stopper preventing if you merge all KMS/DRM platforms into one vs trying to add support individually?
Ex.Given: why cant merge all rockchips socs rk3328/rk3288/rk3399 and future ones with Odroid XU4  and allwinner as they all have GBM and DRM(KMS) support.
Also merge all fb_dev socs into another one and so on.
This way adding new socs would be a breeze vs the current way.

**Comment by joolswills** [comment]
Currently yes, due to different vendor package names etc, and different locations for libraries afair. However perhaps we can look into improving this in the future.

One of the problems is there are very few people contributing stuff like this, so it's mostly down to me. I still need to revisit this branch. It's been very hot here, and I've not felt like doing a lot of code after work.

**Comment by v9999** [comment]
> Currently yes, due to different vendor package names etc, and different locations for libraries afair. However perhaps we can look into improving this in the future.
> 
> One of the problems is there are very few people contributing stuff like this, so it's mostly down to me. I still need to revisit this branch. It's been very hot here, and I've not felt like doing a lot of code after work.

Hey joolswills, let me know if you need help testing this thing out! I've been messing without success with this idea of retropie in the Rock64, but I have faith that this thing can work.

**Comment by MattAndrzejczuk** [comment]
Try my fork:
https://github.com/MattAndrzejczuk/RetroPie-Setup-for-ROCK64-PINE64

So far, I've been able to get the installer up and running on Ubuntu 16.

**Comment by v9999** [comment]
> Try my fork:
> https://github.com/MattAndrzejczuk/RetroPie-Setup-for-ROCK64-PINE64
> 
> So far, I've been able to get the installer up and running on Ubuntu 16.

I've unfortunately got a bunch of errors while doing the basic install. It didn't work.
Which OS image did you use to build this?

**Comment by methanoid** [comment]
Is anyone still working on this?

**Comment by joolswills** [comment]
I haven't checked it for a while. I need to revisit after I have got retropie 4.5 out. Just lack of free time I'm afraid.

**Comment by joolswills** [comment]
Was cleaning up my old branches and removed. I restored as I plan to revisit this soon. Probably nothing much reusable but may use for reference.

**Comment by Ntemis** [comment]
Now days is better you use mainline kernel with mesa3d (lima). Libmali is eol

**Pull request closed without merging**
