### PR TITLE
minor cosmetic tweak to bash welcome

### PR DESCRIPTION
**Pull request by HerbFargus**
### Original
bash_original
### New Changes
bash_1

### CODE REVIEW

**Comment by joolswills** [comment]
I'm not sure - I did actually try increasing the size of the bottom, and I thought it looks the wrong shape then. I'll ask rook.

**Comment by joolswills** [comment]
Unless it was supposed to have that, and the bottom was cut off in the ascii I file I had

**Comment by joolswills** [comment]
(or maybe with `"` chars so it's not as tall)

**Comment by joolswills** [comment]
eg

bash

ill get some feedback from the ascii artist though.

**Comment by HerbFargus** [comment]
yeah either way, it just seemed a little squatty without that last line (whichever characters we end up using) 

I apologise for my recent absence, in the process of moving/ new jobs etc.

**Comment by joolswills** [comment]
No worries - it's just a hobby - hope all goes well with your move/job :)

**Pull request closed without merging**
