### PR TITLE
fix #2783, reicast alpha branch path

### LINKED ISSUE #2783: Building reicast from source on Ubuntu 18.04
It has been released alpha branch (reicast) as default.
The "shell" path has changed to "reicast"

https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/emulators/reicast.sh

### PR DESCRIPTION
**Pull request by manzolo**
fix source path from shell/linux to reicast/linux

### CODE REVIEW

**Comment by manzolo** [comment]
after this fix i got:
cat /dev/shm/runcommand.log 
Parameters: 
Executing: bash "/home/manzolo/RetroPie/roms/dreamcast/+Start Reicast.sh"
/opt/retropie/emulators/reicast/bin/reicast.sh: riga 88:  1852 Rilevato trace/breakpoint (core dump creato) "$rootdir/emulators/reicast/bin/reicast" "${params[@]}" > /dev/null

**Comment by cmitu** [comment]
There is already a PR to fix building Reicast through the RetroPie scriptmodule - https://github.com/RetroPie/RetroPie-Setup/pull/2775.

**Comment by joolswills** [comment]
The for branch fix seems ok. I think some logic got changed during some other overhauls and this case scenario was lost. I may rework the function myself but I appreciate the heads up.

**Comment by joolswills** [comment]
Sorry. I replied on wrong PR. Removing.

**Comment by manzolo** [comment]
Duplicate https://github.com/RetroPie/RetroPie-Setup/pull/2775

**Pull request closed without merging**
