### PR TITLE
Add a "unified" Spear of Destiny startup script

### PR DESCRIPTION
**Pull request by gderber**

### CODE REVIEW

**Comment by joolswills** [comment]
Please can you provide a description /  some context? This is for a merged version of the game?

**Comment by gderber** [comment]
Yes, rather than a startup script for each episode of the game, you can use this to launch the game with all episodes.

**Comment by cmitu** [comment]
@gderber You can modify your PR by pushing to your branch, though you should squash the subsequent commits or use `--amend` when commiting.

You can also close this and re-open another PR (corrected).

**Comment by gderber** [comment]
I'm going to close this then.  I'll submit another one when I am 100% sure it's working as expected.

**Pull request closed without merging**
